### ISSUE TITLE
Get Server IPs

### ISSUE THREAD

**Issue by Blackgen** [TheCheatsrichter/Gw2_Launchbuddy#1]
Hey! I was working on a similar tool in Java while back and i thought this might help you.
You can get the current server IPs using a dns query. I don't know how to do this in C# but there is probably a simple way.
The Host addresses are these:
  assetServer = "assetcdn.101.ArenaNetworks.com";
  authServer1 = "auth1.101.ArenaNetworks.com";
  authServer2 = "auth2.101.ArenaNetworks.com";

You can try out dns queries here: http://www.dnsqueries.com/en/dns_query.php
Result for the Auth1 Servers: 
![arenanet auth server](https://cloud.githubusercontent.com/assets/9056038/17929744/d05f9d1a-6a02-11e6-9cb8-31409c55a903.PNG)

In Java there is a simple function to get the ips in an arrays so i guess it wont be too complex in C#.

I hope this is somewhat useful  ;)

**Comment by TheCheatsrichter** [comment]
Wow man you saved, thought it was way more complicated to get these.
The Dns.GetHostAddresses method does the exept same thing as your java equivalent and returns the IPs in a array.

**Comment by Blackgen** [comment]
No problem :D
Was about to try it myself in C#

You might double check the asset server ips, they seem to differ on the website "dnsqueries". In java i had the right addresses.

**Comment by TheCheatsrichter** [comment]
Thats because it's a hosted CDN by cloudflare. The query links you to the asset servers available near you location. This is done to provide a stable, near and fast connection to the newest gw image. :D

**Comment by Blackgen** [comment]
Ah well that makes sense ^^
