### ISSUE TITLE
1.8.1 Appears to be missing the ability to launch executables

### ISSUE THREAD

**Issue by SkilledAlpaca** [TheCheatsrichter/Gw2_Launchbuddy#100]
I am either missing where to add in executables or the option disappeared from the latest version. I found the spot to load in the DLL's. If this feature is missing, any chance on getting it back as I used it for YOLOMouse and GW2RPC.

**Comment by TheCheatsrichter** [comment]
Temporary reenabled the AddOnManager with Version 1.8.2
