### ISSUE TITLE
Updating to v1.7.0 erased all my stored accounts

### ISSUE THREAD

**Issue by kazerniel** [TheCheatsrichter/Gw2_Launchbuddy#101]
When I overwrote the v1.5.3 exe it forgot all my stored accounts :< I thought this wasn't the expected behaviour for portable programs.

**Comment by KairuByte** [comment]
Unfortunately, LaunchBuddy has gone through many back end changes for accounts. Each update that alters account storage has resulted in this. 

That said, 1.8 is likely going to be the last time this happens, and in the future if a major change is needed from the 1.8 version we will almost definitely include code to transfer forward without issue. 

Unfortunately there were just too many old versions to handle properly pulling settings forward.

**Comment by kazerniel** [comment]
Thank you for the improvements btw, the new features are cool :)
