### ISSUE TITLE
V 1.8 not opening

### ISSUE THREAD

**Issue by moviecritc21** [TheCheatsrichter/Gw2_Launchbuddy#102]
This is with all of 1.8 versions. I double click on the LB icon from the desktop and the wheel spins for a second then LB never loads. If it helps I have Avast and I have it set with an exception. It was working for a little while then nothing. Thanks for all of your hard work. Love the newest version. Had to revert back to previous version 1.7.0

**Comment by KairuByte** [comment]
Out of curiosity are you running with any command line arguments?

**Comment by moviecritc21** [comment]
i just attached Reshade and ArcDps dll files. I am not sure about Arguments. I was playing around with the new bells and whistles and new features of the 1.8.1 version.

**Comment by moviecritc21** [comment]
After thinking about it since my last reply I believe i did set an argument. I think it was the Mapinfo option. If there is something i can try to get v1.8 to work again that would be awesome.
