### ISSUE TITLE
Can't load 2 clients with Window 10.

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [TheCheatsrichter/Gw2_Launchbuddy#103]
Tried to load 2 clients on Win 10.  First client loaded fine,  2nd one displayed this error

![](https://i.imgur.com/wjWRfzx.png)

Hit no, and got this error
![](https://i.imgur.com/MHv5ydv.png)

Which tells me it's something mutex related.  Is there something that needs to be changed to avoid this?

**Comment by tr7zw** [comment]
Got the same problem. Trying to start 5 accounts, only three show up and the other 2 are in a loop because 'yes' and 'no' tries to restart the client which crashes again. Launchbuddy than has to be closed via task manager.

**Comment by KairuByte** [comment]
We've been trying a few different things with the mutex handler. Does this problem persist in the latest versions?
