### ISSUE TITLE
Could Not Open Crashlog! Value was Either too large or too small for UInt16.

### ISSUE THREAD

**Issue by Pikachewie** [TheCheatsrichter/Gw2_Launchbuddy#104]
What do I do with this error? Sorry just wondering.

**Comment by Pikachewie** [comment]
Also Client (username) got closed or cashed before a clean start error keeps happening.

**Comment by SaiyanOfDarkness** [comment]
Go to %appdata%\Roaming\Guild Wars 2 .. open ArenaNet.log file in a text editor.. erase everything.. and save the file.  (do this while game is closed).  Re-Open LB.. it should be gone now.

**Comment by Damevamp** [comment]
![image](https://user-images.githubusercontent.com/53595340/73811889-a6fd9e80-483f-11ea-9f9f-d0481f07953a.png)

Same here and cant up date as well or launch more than 1 account at a time.
