### ISSUE TITLE
[Question] Is it possible to set the same hotkey for multiple accounts?

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [TheCheatsrichter/Gw2_Launchbuddy#105]
I'm looking to run multiple accounts at once (obviously), but I wanted to set a hotkey to the same combination for all the accounts I plan to run at once.  So it would act more like a "bring all game windows to foreground" type hotkey, but of course it would only have the last window it brings forward active.

I just need this because when I need to check something in the background like on Chrome, I have a quick way to bring them forward.

If this is not possible, this would be a great feature.

**Comment by TheCheatsrichter** [comment]
Issues megre: https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/106
