### ISSUE TITLE
[Bug] Client crashes when using same HotKey for multiple clients.

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [TheCheatsrichter/Gw2_Launchbuddy#106]
App crashes immediately when opening.. Tells me the following..

    Problem signature:
      Problem Event Name:	CLR20r3
      Problem Signature 01:	Gw2.Launchbuddy.exe
      Problem Signature 02:	1.8.2.0
      Problem Signature 03:	5c3ce39b
      Problem Signature 04:	NHotkey
      Problem Signature 05:	1.2.1.0
      Problem Signature 06:	545e1fc8
      Problem Signature 07:	6
      Problem Signature 08:	37
      Problem Signature 09:	NHotkey.HotkeyAlreadyRegistered
      OS Version:	6.1.7601.2.1.0.256.1
      Locale ID:	1033
      Additional Information 1:	f75e
      Additional Information 2:	f75e2cd954580e4c521ce4d8f8ca3324
      Additional Information 3:	cea4
      Additional Information 4:	cea4405dbfb97d05981445d3493d8145

**Comment by TheCheatsrichter** [comment]
The WIN API Register Hotkey function actually does not support multiple Actions per Hotkey. Preventing invalid hotkey creation is needed.
