### ISSUE TITLE
White screen after gw2 update 22/01/19

### ISSUE THREAD

**Issue by Nasookd** [TheCheatsrichter/Gw2_Launchbuddy#107]
After gw2 new patch, launching game results in white screen, login details are correct, no aguments,authenticator is not a problem,win 10

**Comment by SkilledAlpaca** [comment]
They have disabled the -email and -password parameters. From what I can gather this kills the -autologin one. 
Source: https://en-forum.guildwars2.com/discussion/66631/command-line-options-changed

**Comment by SaiyanOfDarkness** [comment]
RIP LB :cry:
