### ISSUE TITLE
ANet disabled -email and -password , possible update as work around?

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [TheCheatsrichter/Gw2_Launchbuddy#108]
And I don't just mean to launch multiple clients at once.  I mean a way for LB to load the client with email and password already loaded into the launcher.

**Comment by tr7zw** [comment]
Anets side:
https://en-forum.guildwars2.com/discussion/66631/command-line-options-changed
Possible workaround:
Hotswapping the session file:
https://www.reddit.com/r/Guildwars2/comments/2y6s3g/how_do_i_set_up_shortcuts_to_log_into_different/cp6rqhz/

**Comment by SaiyanOfDarkness** [comment]
The problem with the Hot Swapping, it doesn't have a reliable way of using multiclient.

**Comment by SaiyanOfDarkness** [comment]
I feel like they should add multiple saved accounts to the client.  And add a drop down menu to select which account you want to use.  This would help a ton, but getting them to add anything like this is like pulling teeth.

**Comment by SaiyanOfDarkness** [comment]
@KairuByte Could this information be used to help out LB's future?  https://en-forum.guildwars2.com/discussion/comment/807464/#Comment_807464

**Comment by nevaahe** [comment]
I hope this doesn't come from the new multi-box policy and was an unintended bug. They've accidentally turned off those options in the past as well.

**Comment by SaiyanOfDarkness** [comment]
@nevaahe no this is intentional on their part. Said it was a security risk.

**Comment by Artanis** [comment]
> The problem with the Hot Swapping, it doesn't have a reliable way of using multiclient.

If the issue is the copy/launch commands multilaunch would have to run, would 
pointing Gw2 at entirely different locations for Local.dat by changing the `UserProfile` environment variable help?

**Comment by KairuByte** [comment]
The better option for hot swapping is symlinks. But there are other problems with local.dat. It holds settings, and the moment you use -sharearchive those settings are locked in. You can change them, but they will revert on next launch.

**Comment by Pikachewie** [comment]
Crap yeah launchbuddy doesn't work anymore now with this.

**Comment by SaiyanOfDarkness** [comment]
@Pikachewie It does sort of, just make sure email and password field is blank before hitting launch.  You can load as many clients as you want like this, but you have to pick a different account to hit launch again.  I just use 4 blank accounts and hit launch instead.  And when I'm done with those I move onto the next 4 using the same 4 blank accounts.

**Comment by tr7zw** [comment]
Btw I played around, using symlinks you can bypass the problem that the gw2launcher has the local.dat open. So create symlink to the profiles local.dat, start client, delete symlink. This allows multiboxing using the dat's for autologin.

**Comment by TheCheatsrichter** [comment]
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/commit/cae328ac0a1464df3222e387397522c6be47ff50#diff-d222811c46ec1da3699d488893558d87

**Comment by kazerniel** [comment]
I gave V1.8.4 a try, it worked with the account saved by default in the GW2 launcher, but couldn't make it work with my alt account. I tried to record the Loginfile multiple times - it either automatically logged in with my main account (despite launching the other one), or I had to manually enter the alt login details as it was when I turned off the autologin.

**Comment by kazerniel** [comment]
In v1.8.5 I tried to set up my loginfiles several times, I still have to enter the login details manually each time :/ Not sure what the issue is.
