### ISSUE TITLE
Misleading answer on faq conserning security

### ISSUE THREAD

**Issue by WaDelma** [TheCheatsrichter/Gw2_Launchbuddy#11]
It's true that the account details are encrypted, but that doesn't really help anything if the encryption key is hardcoded and available for anyone.
This fact should either clarified or better yet made safe by requiring master password when launch buddy is opened (Same way as password managers work).

**Comment by TheCheatsrichter** [comment]
Thats the old encryption of Version 1.0.0. The new Betarealese 1.0.5 actually uses the hardcoded AES encryption as before but additionaly hashes with your machines id.
