### ISSUE TITLE
[Request] .dat file naming suggesting

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [TheCheatsrichter/Gw2_Launchbuddy#113]
I know when adding new accounts, it creates each new .dat file as 1.dat, 2.dat, etc.  And the newest one created will always be the latest number.  However I was thinking why not have the .dat named which matches the "nickname"  So you would have ones named Alt 1.dat, Alt 2.dat, Main Account.dat, etc  So you know exactly which one is which.  Because sometimes you want to rearrange them in certain order, and they won't always match up with the original order created.

**Comment by underlinex3** [comment]
For me its not even working to log in an other account... no matter which one i choose it always takes the last used one... 
Does this work for you? 
where can I find the "1.dat" and "2.dat" files you are talking about :)? 
thx buddy

**Comment by TheCheatsrichter** [comment]
The problem with the files is that they actually represent the unique ID of an account. The nickname of the account can be switched anytime and therefore would require remake of the local.dat file

**Comment by SaiyanOfDarkness** [comment]
Yeah I was just thinking about that too before I passed out in bed.  The only way is if LB would rename that exact dat file once changes were made.

**Comment by SaiyanOfDarkness** [comment]
@underlinex3 Give this a try.  https://www.reddit.com/r/Guildwars2/comments/als6hu/gw2_launchbuddy_release_184_still_standing/efhdih7/

**Comment by underlinex3** [comment]
> @underlinex3 Give this a try. https://www.reddit.com/r/Guildwars2/comments/als6hu/gw2_launchbuddy_release_184_still_standing/efhdih7/

omg. you my hero <3 thx
