### ISSUE TITLE
1.8.7 STILL NOT FIXED Feb. 5th *** New Patch Broke LB ***  

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [TheCheatsrichter/Gw2_Launchbuddy#115]
### **LaunchBuddy needs a way to update all .dat files, like how GW2Launcher does**

Using the regular client works, but when I try to launch through LB, I get this after the update.

![](https://i.imgur.com/177PzLe.png)

**Comment by FoolMeOnce** [comment]
I have the same issue.
It attempts to update even though the client is already up to date, appears to download a part of something, then switches to that screen.

I was on 1.8.4 and updated to 1.8.6, it happened on both versions.

**Comment by SaiyanOfDarkness** [comment]
Just an update.  It seems the update broke the .dat files from working.  If you create a new one that one works.  Jesus christ I hope it isn't like this every patch.

**Comment by FoolMeOnce** [comment]
GW2 *just* updated after I posted my comment - I downloaded the new patch and now it's working fine.
Maybe launchbuddy caught the update before the normal client? Don't know if that's possible.

**Comment by SaiyanOfDarkness** [comment]
The regular gw2 client will work fine, but using LB with old .dat files won't work :(

**Comment by Noxicon7** [comment]
I got rid of the Error 5 thing by creating new login files, however it seems I can only get 2 to work simultaneously.  It doesn't seem to save the other login credentials.

**Comment by SaiyanOfDarkness** [comment]
@Noxicon7 You might have to set it twice in a row.

**Comment by SaiyanOfDarkness** [comment]
Ok so, this is what you can do for now.    You can download https://github.com/Healix/Gw2Launcher/blob/master/Gw2Launcher/bin64/Release/Gw2Launcher.exe?raw=true

And you add each .dat file you created with LB to it.  Once you have all your accounts added.. Right click on it. Go to All, then Update.  It'll prompt you to find the gw2.exe file, then just sit back and wait.  It should fix the .dat files for LB.

This is a feature LB needs!!

**Comment by TheCheatsrichter** [comment]
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/releases/tag/1.8.7

should solve this issue.
Please report back if the problem consists.

**Comment by SaiyanOfDarkness** [comment]
@TheCheatsrichter So stupid question, but where do I go to update the login files?  I try to launch an account that was affected by the update and it gives me the same error.

**Comment by Noxicon7** [comment]
Since I couldn't get things to work correctly, I deleted all my accounts storedin LB and tried readding them.  For some reason, I can add the first 2 fine, but after that it just doesnt record the login information.

**Comment by SaiyanOfDarkness** [comment]
I think what the problem is.. -shareArchive is being forced when trying to launch the client, when it should switch the .dat file first.. then run the client without -shareArchive in order to update the .dat file.

**Comment by jacob-keller** [comment]
I'm having a similar issue, the latest build does not seem to correctly save multiple account infos. Somehow it ends up storing only the first account, even if I delete everything.

I was able to create the account .dat files manually, and get things working again as a temporary work around.

**Comment by SaiyanOfDarkness** [comment]
> I'm having a similar issue, the latest build does not seem to correctly save multiple account infos. Somehow it ends up storing only the first account, even if I delete everything.
> 
> I was able to create the account .dat files manually, and get things working again as a temporary work around.

Now only if you could import .dat files in this case..

**Comment by SaiyanOfDarkness** [comment]
So I had to go through and manually update each one in order to get them to work.  However I saved one of the .dat files in its previous state before the update if it needs to be used to catch bugs with .dat file updating?

**Comment by TheCheatsrichter** [comment]
LB compares the Gw2 Build Number when the Local.dat file was created with the actual build number provided by the Gw2 API. If you try to launch an outdated Local.dat LB should automatically launch the account without any other settings, close it immediatly (local.dat is now updated) and then proceed with the normal launch.

- Added manual Update button in 1.8.8 to give users more options.

**Comment by FoolMeOnce** [comment]
Seems to work for me now, I'm able to launch multiple accounts without having to manually update anything.

**Comment by TheCheatsrichter** [comment]
> So I had to go through and manually update each one in order to get them to work. However I saved one of the .dat files in its previous state before the update if it needs to be used to catch bugs with .dat file updating?

Can you also confirm that it is working now?

**Comment by TheCheatsrichter** [comment]
> Seems to work for me now, I'm able to launch multiple accounts without having to manually update anything.

Thanks for the fast reply. Did the Gw2 Client update (the almost blank download window before login) or could this me a side effect from manually fixing it by yourself?

**Comment by FoolMeOnce** [comment]
> > Seems to work for me now, I'm able to launch multiple accounts without having to manually update anything.
> 
> Thanks for the fast reply. Did the Gw2 Client update (the almost blank download window before login) or could this me a side effect from manually fixing it by yourself?

I had launched my GW2 client earlier normally, updated it, and closed it.
Then I used Launchbuddy to start multiple clients - each one said something about 'fixing loginfile', then launched.

**Comment by SaiyanOfDarkness** [comment]
> > Seems to work for me now, I'm able to launch multiple accounts without having to manually update anything.
> 
> Thanks for the fast reply. Did the Gw2 Client update (the almost blank download window before login) or could this me a side effect from manually fixing it by yourself?

@TheCheatsrichter Manual repair brings up the little pop up window, but launcher never loads or does anything.  If you want I can send you a .dat file to see if you get the same problem on your end?

**Comment by TheCheatsrichter** [comment]
> > > Seems to work for me now, I'm able to launch multiple accounts without having to manually update anything.
> > 
> > 
> > Thanks for the fast reply. Did the Gw2 Client update (the almost blank download window before login) or could this me a side effect from manually fixing it by yourself?
> 
> @TheCheatsrichter Manual repair brings up the little pop up window, but launcher never loads or does anything. If you want I can send you a .dat file to see if you get the same problem on your end?

Sure would be great. :)

The repair button actually applies the local.dat of the account, launches the gw2 client without any additional settings and closes automatically after the Login window is reached. This updates the local.dat if it is outdated.

**Comment by SaiyanOfDarkness** [comment]
@TheCheatsrichter I sent the .dat file on reddit, with a bit of information included.

**Comment by TheCheatsrichter** [comment]
Thanks for the file. It seems to be a valid loginfile so the error might be seomething else.
Can you please try 1.8.9 or check your file at %appdata%/Gw2 Launchbuddy/accs.xml and see if the accounts ID is 0 on one or more accounts? If yes 1.8.9 should fix the isue

**Comment by SaiyanOfDarkness** [comment]
No account ID's are 0 on the .xml file.  Also the update to 1.8.9 didn't change anything.  I tried to run the manual update again, but I am getting a new error.  And I have nothing open but LB.

   Could not repair Loginfile. Please recreate a loginfile with Set Loginfile. 
   An error occured when Updating the Login file. The process cannot access the file '%appdata%\Gw2 
   Launchbuddy\Loginfiles\33.dat' because it is being used by another process.

**Comment by SaiyanOfDarkness** [comment]
@TheCheatsrichter I sent you an unlisted video link on reddit, basically showing exactly what happens, and what I have to do to fix it.

**Comment by TheCheatsrichter** [comment]
Added workarround via Logindata backup with version 1.9.

**Comment by SeparGW2** [comment]
I am having the same 'Download failed' problem with v2.2.  So after an update I delete the login files and Account Settings | Login Credentials | Set Logfile for each account.
