### ISSUE TITLE
how do I save settings now that we don't use the main local.dat?

### ISSUE THREAD

**Issue by jacob-keller** [TheCheatsrichter/Gw2_Launchbuddy#119]
Now that launchbuddy saves the local.dat per account, I'm unable to have it save the settings. Because every launch of the game runs with -shareArchive, the client can't make changes to the local.dat file permanent.

How do I launch the game in a way that lets me save the settings for that account?

**Comment by KairuByte** [comment]
There really isn't a way. Any setting saved within local.dat is impossible to change when running with LB at the moment. It's possible we may look into having specific accounts boot up without -shareArchive for simple settings changes, but that's going to be a weird workflow compared to anything we currently have,

**Comment by jacob-keller** [comment]
It would be nice to have a way to launch a single account without -shareArchive, as I currently have to manually copy the X.dat file into place of local.dat, load, edit and save settings, and then exit.

It's definitely a very weird workflow right now.
