### ISSUE TITLE
Mouse/ Keyboard capture

### ISSUE THREAD

**Issue by TheCheatsrichter** [TheCheatsrichter/Gw2_Launchbuddy#12]
When using the LB function keys and additional buttons on the mouse get captured by the app.
For example using the function key "mute" gets captured and therefore will not result in the audio to stop.

This might also be the source for those keys not working in the gw2 client childprocesses.

**Comment by KairuByte** [comment]
I am actually not seeing this behavior. Is there some specific state you noticed this in?

**Comment by TheCheatsrichter** [comment]
My Roccat keyboar functions keys dont work ingame and during usage of LB. Same goes for the logitech mouse buttons.

**Comment by KairuByte** [comment]
Hrm, I'll double check this, but I have Razor peripherals so I may not be able to replicate it. Typically windows does not allow input capturing when the application is not in focus, unless you register a global hotkey. At least with the methods I have used in the past.
