### ISSUE TITLE
v1.8.9 fixes and bugs

### ISSUE THREAD

**Issue by kazerniel** [TheCheatsrichter/Gw2_Launchbuddy#120]
With v1.8.9 (after wiping my accounts again) I still get an error at loginfile creation, BUT the loginfile is in fact created all right, and is working after I cancel the creation popup.

But another weird bug I came across is that if I clone an account, then the original and the clone's argument settings are still linked. If I toggle on/off some arguments for the clone, it changes the original too, and vice versa.

But thanks for the continued work on the app :) I know we users complain all the time, but your work is greatly appreciated :)

**Comment by kazerniel** [comment]
The graphic settings for cloned accounts also seem to stay linked. If I change one, the other changes too.

**Comment by TheCheatsrichter** [comment]
I could reproduce this error when cloning accounts without a LB restart in between. If you relaunch LB after a clone this link should no longer exists. Thanks for the report, I will try to fix this in an upcoming hotfix

**Comment by kazerniel** [comment]
It used to persist through restarts, but now that I re-checked it, it seems fixed for me.
