### ISSUE TITLE
LB needs to automatically delete gw2cache folders now more than ever.

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [TheCheatsrichter/Gw2_Launchbuddy#121]
Since the update to the .dat file system.  Every new game you launch creates a brand new gw2cache folder.

This creates a problem very quickly with anything Browser related in game, like PvP info, WvW Info windows, and more noticeably the TP window.

For the time being I had to create a .bat file to use before loading in my accounts from LB, but it would be nice if this did it automatically before loading the game.  You can even have it run after each account if you want, or just have it run only when you press Launch, that way it's not doing it for every account it loads.

**Comment by SaiyanOfDarkness** [comment]
So I let my gw2cache folders pile up for 1 week.  I had 54 GB of data to delete.  Having this feature would be an amazing help.

**Comment by KairuByte** [comment]
What's really weird is that I can't replicate the persistence. I'll see about hitting this when plugins get finished.

**Comment by SaiyanOfDarkness** [comment]
@KairuByte how many accounts did you try loading at once?  I think it has a higher chance to produce more gw2cache folders the more accounts you load up at one time.

Also, when you work on this, probably would be a good idea to make this optional, and not forced.

**Comment by TheCheatsrichter** [comment]
I am not able to duplicate this issue to such a big extend as you. How many accounts are you actively using?

**Comment by SaiyanOfDarkness** [comment]
@TheCheatsrichter at a time?  5.  Although I mostly login 4 at once.  Using 36 accounts total.  It's creating a new gw2cache folder every time I login.

**Comment by SaiyanOfDarkness** [comment]
I probably should have included I'm on Windows 7, and not 10.  Not sure if there is a setting in game or somewhere else to change the folder where gw2cache is created.  Because it's writing to my SSD, and basically each time it has to do that it's reducing the lifespan of the drive itself.

**Comment by SaiyanOfDarkness** [comment]
So additional details.  I believe this is related to `CoherentUI_Host.exe` being used multiple times.  Instead of being used once for multiple instances..

**Comment by TheCheatsrichter** [comment]
Added workarround with e923b0644347bec0979a8a114d5fa4991c52d28a.
Launchbuddy automatically cleans the cachefolder from folders which weren't used for 7 days.
