### ISSUE TITLE
Will not launch after first launch

### ISSUE THREAD

**Issue by Noxicon7** [TheCheatsrichter/Gw2_Launchbuddy#123]
Not entirely sure how to explain this.  Last night, LB stopped working for me.  However, when I download a new version, it launches the first time, but will NOT launch again a second time.  I'm not referring to GW2 accounts with that, but the actual program itself.  It repeats, if I remove the .exe and redownload, it will work the initial time, but not with any followup launches.

**Comment by SaiyanOfDarkness** [comment]
Do you have an antivirus installed, that could be quarantining it without your knowledge?

LB has been notorious for having a fake virus in it that some AV's trigger.

**Comment by Noxicon7** [comment]
I don't think its that as there's zero notification on it and it runs fine the first time it's launched.  Also, somehow, it's working fine again today with literally no changes made to my pc.  Technology is a hell of a thing.

**Comment by KairuByte** [comment]
I'm going to close this out as it sounds like it resolved itself. If it happens again and persists past a reboot, feel free to reopen.
