### ISSUE TITLE
Network Settings not actually doing anything?

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [TheCheatsrichter/Gw2_Launchbuddy#126]
So I have several accounts.  2 of Which were purchased through an official retailer, but they were from EU.  So the accounts Region is listed as EU, but are on NA servers for playing.  So by default it tries to login to the account with the EU authentication servers.  This at times can cause some delay (up to a few mins) before the account is able to get to character select screen.  I then try to select a server with a lower ping to my location, and attempt to login the account after getting the "check your firewall" error.  And it just sat there taking forever to login, but another account with region based in NA had no problem logging in.  So even though I clicked on a server with a lower ping, and made sure I selected the checkbox below to enable to use both the authentication and asset server.  It seemed like it didn't really change it at all.

Am I just imagining this, or is this really what's going on?

**Comment by TheCheatsrichter** [comment]
I just tried several times to reproduce this error. I started all my accounts on different login and asset servers. Checked the provided launch arguments and compared them to an actualy network traffic monitor software. For me everything seems fine. Is this error still persistend on the newset gw2 build? Is there a specific workflow to replicate this error?

**Comment by SaiyanOfDarkness** [comment]
So I have a few accounts.  Mostly listed in North America, but a few listed in Europe.  Not to be confused with the actual NA or EU game servers where characters are stored.  The accounts listed in Europe are shown as that on https://account.arena.net/overview .. but the characters themselves are on NA game servers.  When attempting to login such account on LB using an Authentication server from NA, it completely ignores it and chooses a server closer to EU based on the Region the account was created on (the account serial came from an EU retailer).

I was thinking if there was a way to include the IP Address the account is using to login to the game, possibly in the "Running" mouse over info on the front of LB itself.  And if possible, maybe to set asset and authentication servers per account?
