### ISSUE TITLE
LB doesn't remember the monitor 

### ISSUE THREAD

**Issue by Siofral** [TheCheatsrichter/Gw2_Launchbuddy#128]
I have two monitors, a 32" LCD tv and a 19" LCD monitor. I play GW2 on the 32" (obviously). LB insists on opening on that monitor. I drag it to the smaller monitor when it opens. It would be awesome of LB would remember where it should open.

**Comment by KairuByte** [comment]
IIRC this is the default for the client. It opens on whatever the PC sees as the primary monitor. 

LB doesn’t currently support moving client windows, but it may be added in the future.

**Comment by akeck** [comment]
That would be a killer feature! +1!

**Comment by TheCheatsrichter** [comment]
Added with advanced windowmanagement in Version 1.9+
