### ISSUE TITLE
LB created shortcut enhancement

### ISSUE THREAD

**Issue by KairuByte** [TheCheatsrichter/Gw2_Launchbuddy#13]
Shortcuts are fundamentally flawed, in that they try to replicate the functions of Launchbuddy in a way that was never intended. A long string of programs to start and specific arguments alongside plaintext passwords is unmaintainable.

Launchbuddy needs to support command line arguments itself. This would allow "secure" storage of passwords to continue, along with multibox support, and proper addon support.

I will work on this when I have time, unless TheCheatsrichter gets time to do it.

**Comment by TheCheatsrichter** [comment]
Before tackling the argument feature I want to finish the cinema mode etc. So when it gets implemented the argument list is allready complete and something hasn't to be changed afterwards.

**Comment by KairuByte** [comment]
Sounds perfect. 

After I work out the splitting of functionality into individual classes I'll take a look at shortcut/argument handling. Luckily a lot of the work needed for arguments was taken care of with the argument(s) object definitions I implemented last night. That is, unless you get to it first.

**Comment by KairuByte** [comment]
This might be better suited being tagged as an enhancement rather then closing, and closed when it gets knocked out and/or merged in.

**Comment by KairuByte** [comment]
Added rudimentary support to refactor branch. Currently just runs accounts by nickname and closes LB completely using Gw2.Launchbuddy.exe -s -l Nickname

Much more code separation from MainWindow.xaml needs to happen...
