### ISSUE TITLE
Latest "fix" is actually providing additional problems.

### ISSUE THREAD

**Issue by Siofral** [TheCheatsrichter/Gw2_Launchbuddy#130]
I'm getting a new error about additional information needed for an account with no key to what the additional information is. See the attached image. LaunchBuddy cannot decide where it should open. Sometimes it opens on my small monitor, sometimes on the large and this is *not* dependent on whether the app has been previously opened in the current boot-up. The Game Instances  window also can't decide. 

My preferred graphic layout is full screen windowed. If I use the Configure Windowsettings I do not get full screen windowed AND I get a change in the graphics quality. Something is causing settings to be adjusted in such a way that everything lightens and flattens. I can fix that by using Delete Windowsettings.

![LBError](https://user-images.githubusercontent.com/21143080/56458423-2ebefe80-633b-11e9-9e15-76141bc592df.png)

**Comment by TheCheatsrichter** [comment]
Added bugfixes in Module Collector and Client Launch sequence to remove this error. Please report back if it still exists.
