### ISSUE TITLE
App isn't loading at all

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [TheCheatsrichter/Gw2_Launchbuddy#131]
So not sure what is going on, but when I try to load the app.  It appears in my task manager processes that's running, but I see no window appear at all.  I've tried downloading other previous versions I had, even went as far as clearing out my  appdata folder.  Not sure what's causing it.

Ok I think maybe cuz the fact that the API is down is causing the app not to load?

**Comment by TheCheatsrichter** [comment]
Added additional APi downtime handling for LB in Version 1.9.1
