### ISSUE TITLE
Sound Settings

### ISSUE THREAD

**Issue by Munzy** [TheCheatsrichter/Gw2_Launchbuddy#136]
My Sound settings keep getting reset. I turn my  volume in game way down. Is there a way to save my sound settings so they constantly don't reset?

**Comment by Lego6245** [comment]
I'm experiencing this as well, on one specific account. The other accounts appear to persist their settings, but this account resets both audio and the graphical settings to GW2's defaults.

**Comment by Munzy** [comment]
It is very frustrating especially when your sound is blaring each time you log in.

**Comment by Lego6245** [comment]
I was able to resolve the issue by removing and re-adding the account in LB.

**Comment by Munzy** [comment]
> I was able to resolve the issue by removing and re-adding the account in LB.

I tried this on V1.9.3 Alpha and it did not work Audio reset back to full volume.

**Comment by Lego6245** [comment]
Hm. The exact set of steps I did was:

1. Remove the account from LB.
2. Launch GW2 normally (without LB), sign in with the account, set my settings, log out.
2a. Try logging into GW2 again to verify everything was working.
3. Add the account in LB.

**Comment by TheCheatsrichter** [comment]
> Hm. The exact set of steps I did was:
> 
> 1. Remove the account from LB.
> 2. Launch GW2 normally (without LB), sign in with the account, set my settings, log out.
>    2a. Try logging into GW2 again to verify everything was working.
> 3. Add the account in LB.

This is actually the way to go. This is a side effect LB can't handle because of the loginfile method. LB swaps each loginfile on the accs start and then swaps back to the "original" loginfile. A bad side effect of this is that settings which would normaly get set when the client closes (Audio etc.) get saved to the loginfile which actually does not correspond with the acc.

**Comment by Munzy** [comment]
This does seem to be the case. I was able to follow the steps above and have the settings save across accounts.

This would be something best documented somewhere. Do we have a documentation spot? I'll drop in a commit with instructions if we do.

**Comment by TheCheatsrichter** [comment]
Atm there isn't an up to date documentation of LB usage, as things changed a lot in the last few versions. Version 2.0.0 however will in junction with plugin support introduce one.

**Comment by CameronMunroe** [comment]
@TheCheatsrichter, 

Do we still need to write up some documentation on this, or is this a fully stale issue?
