### ISSUE TITLE
Accounts not using the saved Login Info

### ISSUE THREAD

**Issue by ahazen0052** [TheCheatsrichter/Gw2_Launchbuddy#138]
I've setup several accounts entered the backup info and used Recreate Loginfile for every account and watched the app enter the correct info and login. When I try to launch any account it does not fill in the correct account info for the selected account and uses the last set of login info instead. If I launch multiple accounts it will then launch one account multiple times.

**Comment by Enko63** [comment]
I've had this same issue since I tried using Launchbuddy as well.

**Comment by Kdowdall** [comment]
Also experiencing this issue on v1.9.3 alpha
