### ISSUE TITLE
Random Error Box appearing each time I launch an account

### ISSUE THREAD

**Issue by Canyonbydesign** [TheCheatsrichter/Gw2_Launchbuddy#139]
Each time I launch an account one of these error boxes appears and I am not sure what is causing it. If I attempt to close the error box it just opens a new one. It does not appear to be interfering with functionality at all, it is just annoying.
![a08020f4f13dac9eb1b67c9b3004a868](https://user-images.githubusercontent.com/50377775/58373762-0b1e4380-7ef9-11e9-9b43-be2cd4385c81.png)

**Comment by SaiyanOfDarkness** [comment]
This could be a guess but when's the last time you emptied your `%temp%`   of gw2cache folders?

**Comment by TheCheatsrichter** [comment]
Part of the new Windowmanagement.
GetWindowDimensions(Process pro) will get called when your game is started and refers to the MainWindowhandle of the process.
This handle changes during the startup of the game.

Added an additional handle refresh before calling GetWindowDimensions.
Please report back if it is fixed once 2.0.0 is released.
