### ISSUE TITLE
PvP Arena favorites are empty

### ISSUE THREAD

**Issue by akeck** [TheCheatsrichter/Gw2_Launchbuddy#140]
I've saved an arena in my favorites (PvP Game Browser -> Favorites).
When I launch GW2 using LB, the favorites list is empty. If I start it without LB, my favorites are there...
A fix for that would be very much appreciated :)

regards
Buffy

**Comment by TheCheatsrichter** [comment]
Sadly part of the loginfile method.

Can't be fixed or changed. Would need to modify the local.dat file itself, which is encrypted.
