### ISSUE TITLE
[Request] Help button and wiki overview for use.

### ISSUE THREAD

**Issue by mwrich4** [TheCheatsrichter/Gw2_Launchbuddy#143]
I was a long-time user of 1.05.  I tried 1.70, but the recent loss of autologin made that impossible.

Today, I tried 1.92(3) and after a couple of hours I finally figured out the necessary order of things.

The indicated help resources on the site are outdated. 
The program should have a simple walkthrough available from a help button.

**Comment by TheCheatsrichter** [comment]
An usefull wiki will be provided with 2.0.0. Things changed quickly and drastically over the last few versions so writting a wiki for everchanging system would have been way to much work.

**Comment by mwrich4** [comment]
A short narrative in the readme would have been plenty.
