### ISSUE TITLE
Request: Allow a command line list of account numbers for autolaunch

### ISSUE THREAD

**Issue by mwrich4** [TheCheatsrichter/Gw2_Launchbuddy#145]
I could create a program launch icon for a single account leaving myself the option to start more accounts later with this feature.

I think all that would be needed is to display the account id number you use for the .DAT file on the account list page.  Start launchbuddy with this number as an argument somewhere and then minimize launchbuddy.  Perhaps a 2nd use with the same list or a new list could be routed to the already running instance for handling.

**Comment by KairuByte** [comment]
Technically this is partially in place. You can already launch accounts by nickname.

Or at least, you could previously. And IIRC it handled multiple accounts seamlessly.

I can’t guarantee it made it through to the latest release though, I’d have to look into it and haven’t had time in... forever.

On Jul 8, 2019, at 3:13 PM, mwrich4 <notifications@github.com<mailto:notifications@github.com>> wrote:


I could create a program launch icon for a single account leaving myself the option to start more accounts later with this feature.

I think all that would be needed is to display the account id number you use for the .DAT file on the account list page. Start launchbuddy with this number as an argument somewhere and then minimize launchbuddy. Perhaps a 2nd use with the same list or a new list could be routed to the already running instance for handling.
