### ISSUE TITLE
[Request] Appointing gw2cache folder location

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [TheCheatsrichter/Gw2_Launchbuddy#146]
Would it be possible to have LaunchBuddy use the same gw2cache folder for all accounts?  This way the game loads smoother, and improves BLTC response.

**Comment by SaiyanOfDarkness** [comment]
If you can't use the same cache folder, than what about having LaunchBuddy remember the cache folder for each account?

**Comment by TheCheatsrichter** [comment]
This would require addtional symlinks which "redirects" the folder to a single one. Reading / writing to the same data from multiple clients may also cause a lot of instabilities. Therefore not considered as an improvement.

**Comment by SaiyanOfDarkness** [comment]
Then what about assigning gw2cache folder to each of the accounts.  So it doesn't create new ones each time the game is loaded?  This way it's not trying to use 1 single folder.

**Comment by KairuByte** [comment]
AFAIK this isn’t something that can be handled on the side of LaunchBuddy, as it’s a process completely internal to the client.

On Aug 12, 2019, at 11:51 AM, SaiyanOfDarkness <notifications@github.com<mailto:notifications@github.com>> wrote:


Then what about assigning gw2cache folder to each of the accounts. So it doesn't create new ones each time the game is loaded? This way it's not trying to use 1 single folder.
