### ISSUE TITLE
Launchbuddy opening the same account multiple times

### ISSUE THREAD

**Issue by tgdm** [TheCheatsrichter/Gw2_Launchbuddy#149]
I've tried restarting, deleting/recreating, repairing, re-entering credentials, etc. Every time I launch it's going to the same account now.

**Comment by efraimip** [comment]
same! autologin seems completely broken now.

i have it setup where i have 1 "main" account with all options/settings high.
then i have 4 "alt" accounts which have nosound, low settings, etc.
i have logged into each of them using the "create login file" button successfully, and then exited them.
i even put the emails and p/w for each of them on each acct in the acct info area.

then if i try to launch them all at once, it logs me into my main acct, but then for the 2nd to 5th acct it is only using the 5th acct info (5th acct email and pass). and it doesnt work then either - it stays at login screen and says "account name or password you entered is invalid" etc.... with the "OK" button.

so only the 1st account logs in. the others get stuck at login screen using the same acct info as last acct.

hope this is as helpful as possible.
great tool! thank you!
