### ISSUE TITLE
Launchbuuddy doesn't start anymore

### ISSUE THREAD

**Issue by PalantirTinuviel** [TheCheatsrichter/Gw2_Launchbuddy#150]
Since this morning I am not able to start Launchbuddy from the desktop or my LB folder anymore. After starting the LB.exe nothing happens, even not in admin-mode.
The weird thing is, I then deleted LB and downloaded it again. After this I was able to start the LB.exe out of the download folder (directly from Firefox or the download folder in Windows, makes no difference), but as soon as I move the LB.exe to my LB folder or any other folder it doesn't work.

Edit: I downloaded LB, left the LB.exe in the download folder and created a shortcut in my LB folder which seems to wok for now, although I could not solve the main problem.

Any Ideas?

**Comment by Neltisen** [comment]
It's true. Launchbuddy does not seem to work anymore

**Comment by TheCheatsrichter** [comment]
This issue should be fixed with version 2.0.1.
Please report back if the error persists.
