### ISSUE TITLE
Change -authserver and -assetserver to -authsrv and -assetsrv respectively

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [TheCheatsrichter/Gw2_Launchbuddy#155]
This is just an official report to fix this issue.

LB is using `-authserver`  and `-assetserver`  instead of `-authserv` and `-assetsrv`

This causing problems with the client actually using the server chosen by LB.  As the commands `-authserver` and `-assetserver` aren't actually commands you can use on the client itself.

Bonus info:  `-clientport` command isn't being run from LB.  Even though the checkbox is enabled to use 443.

**Comment by TheCheatsrichter** [comment]
Fixed with: c268a3b9b370a0494f12b5ff8f5d572ec60f380d

**Comment by SaiyanOfDarkness** [comment]
Being that 1.9.3 is still the current version according to https://github.com/TheCheatsrichter/Gw2_Launchbuddy/releases

How long before the update pushed?

**Comment by TheCheatsrichter** [comment]
https://www.reddit.com/r/Guildwars2/comments/elxj99/gw2_launchbuddy_21_release_not_over_til_we_say_so/

Done
