### ISSUE TITLE
2.1.1 isn't changing .dat files and only loading the same account

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [TheCheatsrichter/Gw2_Launchbuddy#157]
So I updated my older version of 1.9.3, and now when I hit launch on an account I selected, It's only using the default .dat file in the gw2 appdata folder and its not copying over the .dat file from LB folder before hand.

On top of that, the game client takes a while to appear, and it doesn't seem to be removing any gw2cache folders from my `%temp%` directory.

**Comment by brnbrito** [comment]
Same for me, set loginfile for Acc1 then Acc2 but both are launched as Acc2, seems like last loginfile to be set persists for all of the other accounts.

**Comment by hazenvirus** [comment]
This has been happening to me since 1.9.3

**Comment by watlok** [comment]
If this happens to you then delete all stored accounts. Close it. Reopen it. It should work fine from then on. Make sure you don't leave guild wars 2 open, or the launcher, when trying to enter credentials. It will cause launchbuddy to crash and can cause this problem.
