### ISSUE TITLE
Unable to open archive file.

### ISSUE THREAD

**Issue by brynlea** [TheCheatsrichter/Gw2_Launchbuddy#158]
On LB 2.1.1, trying to load an account gives me an error message.

"Guild Wars 2 is unable to access its archive file C:\address\to\roaming\local.dat
Please verify that this file is accessible and writeable, and that no other program is currently using it."

I am able to load the game through its .exe, and with "Set Loginfile," just not through the home page. Also tried after clearing the cache and a system restart. Not using any add-ons.
Redownloaded LB 1.9.3 and it launches fine there.

Using Windows 7 64-bit.

**Comment by SaiyanOfDarkness** [comment]
I had the same problem, but I was able to load the game if I had the .exe file inside a folder with both `CrashReporter.NET.dll` and `Xceed.Wpf.Toolkit.dll`  however the program wasn't changing .dat files for the accounts chosen.  On top of that the game client was appearing much slower than 1.9.3

**Comment by kazerniel** [comment]
+1

It's also not saving information to the dat files even after manually re-setting them. In the previous version at least that worked. Will have to roll back :S
