### ISSUE TITLE
LB cant start game

### ISSUE THREAD

**Issue by leovandavart** [TheCheatsrichter/Gw2_Launchbuddy#159]
i Installed the d912pxy mod and now i cant start 1 or 2 ... games 

its only say ... got closed or crashed before a clean start

**Comment by SaiyanOfDarkness** [comment]
You get this error too?  ![](https://i.imgur.com/aNR2GPn.png)

**Comment by leovandavart** [comment]
![Unbenannt](https://user-images.githubusercontent.com/51362702/72175555-b45c7000-33dc-11ea-851a-e28442cdded9.PNG) i get this error

**Comment by SaiyanOfDarkness** [comment]
Yeah it has a problem with switching .dat files properly for me.  Could be related.

**Comment by Frank-MC** [comment]
> You get this error too? ![](https://camo.githubusercontent.com/60bc84ba237afe2c88f699a7fca885bb60f6ccf0/68747470733a2f2f692e696d6775722e636f6d2f614e523247506e2e706e67)


yap getting the same error, and am un able to open more than 1 instance at the same time.

**Comment by 147172654** [comment]
me too......i DX9....
