### ISSUE TITLE
Error, request for log in as admin and general fail

### ISSUE THREAD

**Issue by Siofral** [TheCheatsrichter/Gw2_Launchbuddy#160]
"An error occured (incorrect spelling) while swaping (incorrect spelling) the Login file.Could (no space between period and the start of following sentence) not create Symbolic link. Please activate Windows Developer Mode or run Launchbuddy as Admin!"

Each of these errors opens a browser window regarding Windows Developer Mode.

Even starting as Admin does nothing. Nothing runs, nothing works, cannot login using LB and LB does not recognize Run as Admin has been used.

**Comment by SaiyanOfDarkness** [comment]
Have you tested 2.1.2 to see if this problem still exists?
