### ISSUE TITLE
Could not find file Arenanet.log

### ISSUE THREAD

**Issue by brnbrito** [TheCheatsrichter/Gw2_Launchbuddy#161]
Just formatted and been getting this error for a while, tried making the log file myself but didn't work, just wondering if anyone had the same issue as i couldn't find the answer.
![image](https://user-images.githubusercontent.com/45767422/72585680-af605a80-38cd-11ea-90ab-b4b26cc365aa.png)

**Comment by TheCheatsrichter** [comment]
9324423bbbdbe8202ea66c60c8616147eba986ca

Should solve this issue in the upcoming 2.1.2 version.

**Comment by brnbrito** [comment]
Working fine now, though i can't make it launch different accounts now.

 I set the loginfile for **Acc1**, then did **Acc2** and both get stuck with **Acc2** settings, for some reason last loginfile to be set is persisting and i can`t load both.
