### ISSUE TITLE
LB not deleting gw2cache folders

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [TheCheatsrichter/Gw2_Launchbuddy#162]
> Gw2 cache folders can eat up a lot of memory if not deleted regularly. Launchbuddy now automatically keeps track of your cache folders and deletes outdated ones to keep your pc clean and running smoothly.

Not sure when this kicks in, but I have over 9 GB of cache folders so far.   My temp folder location is `C:\Users\<ID>\AppData\Local\Temp`

I've been using a .bat file to delete them for a while now.  If anyone wants to use it until LB gets the issue fixed.

    for /D %%f in ("%temp%\gw2cache*") do rmdir %%f /s /q
    
    exit

**Comment by TheCheatsrichter** [comment]
Folders get deleted if the delta between the current date and the "last time used" date exceed 7 days.
Might be worth adding this timespan as a usersetting.

**Comment by SaiyanOfDarkness** [comment]
I was thinking, what if there was a way to have LB do this before loading the game.  So for example.  You click on the accounts you want to Launch, and it will proceed to remove the cache folders before starting the game.  However if the game is already running and you load another client up, LB will see the game is currently running and will not run the command.  It would only run when it doesn't detect gw2(-64).exe in the processes.

Not sure if something like that would be possible?
