### ISSUE TITLE
not detecting that loginfile is already updated

### ISSUE THREAD

**Issue by jacob-keller** [TheCheatsrichter/Gw2_Launchbuddy#166]
Recently launch buddy seems to be unable to detect properly that a loginfile has been updated. It tries to update the login file every launch, and always says "update required" regardless of how many times the file was updated.

It still seems to be able to load properly, but attempts to update the login file every time I load each account.

It also seems like the repair button doesn't help.

**Comment by jacob-keller** [comment]
This only occurs if the program is built manually using the DEBUG configuration.

**Comment by SaiyanOfDarkness** [comment]
> This only occurs if the program is built manually using the DEBUG configuration.

I'm using the latest build (not sure if the debug thing is on or whatever), but it does it for me too.  It stops after about 3-4 times.

**Comment by jacob-keller** [comment]
I'd be surprised if this exact issue is what you're seeing, given that it is specific to the DEBUG build which you'd have to have build manually. Seems like no one merged my fix tho :( If you can build the program, you could try out the suggested fix and see if it resolves your problem

**Comment by TheCheatsrichter** [comment]
Pull request has been merged. The leftover from debugging should now be gone and the loginfiles should update normaly. This issue is closed as this only affected the Debug version.
