### ISSUE TITLE
Malware

### ISSUE THREAD

**Issue by Samo276** [TheCheatsrichter/Gw2_Launchbuddy#167]
After downloading newest version my anrtivirus intercepted and deleted app, informing me it was infected with malware.

**Comment by dreamboatcap** [comment]
I have this problem as well. I'm using avast.

**Comment by SamoDziadostwo** [comment]
Same

**Comment by Yoza1** [comment]
This happend to me as well and avast put the game into quarantine, I solved the issue by removing it from quarantine hence restoring it and list it as a trustworthy application

**Comment by TheCheatsrichter** [comment]
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/207
