### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by TekkitsWorkshop** [TheCheatsrichter/Gw2_Launchbuddy#175]
Hey, I have this issue with LB in the past 3 days or so (update to 2.1.3 did not fix it or made it worse). Already launched accounts randomly crash with this error I've never seen before. I've checked my connection and also tried a different one, but still the same.
![vPmj](https://user-images.githubusercontent.com/65012550/81387378-d958b980-9116-11ea-8a74-2ddd79b354af.png)

**Comment by TheCheatsrichter** [comment]
Is this error stil reproduceable?
