### ISSUE TITLE
No way of turning off the "Game instances" window?

### ISSUE THREAD

**Issue by HGLatinBoy** [TheCheatsrichter/Gw2_Launchbuddy#179]
I hate it and i always have to manually close it whenever I launch an instance is there way to disable it?

**Comment by Explomatic** [comment]
You can. Under "LB Settings" there's a checkbox for "Use Game Instance GUI", simply untick that:
![use_game-instance-gui](https://user-images.githubusercontent.com/14542568/82543080-53dffb00-9b53-11ea-9156-4bbb5a0077b9.png)

Note though that this setting gets reset every time you update to a newer version of GW2 Launchbuddy, which is a bit annoying 😕
