### ISSUE TITLE
version number in master branch doesn't match latest release

### ISSUE THREAD

**Issue by jacob-keller** [TheCheatsrichter/Gw2_Launchbuddy#180]
The master branch, if built manually, ends up being detected as version 2.1.3, rather than the (correct based on git tag and commit id) 2.1.5

**Comment by TheCheatsrichter** [comment]
2.1.5 was allready given on the master branch.
2.1.5 Labels and assembly version should now be correct with:
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/commit/8ee9cc69fbb6fadfa1bde15374556a3cc8ee633f
