### ISSUE TITLE
Chinese client- Gw2.dat error

### ISSUE THREAD

**Issue by 147172654** [TheCheatsrichter/Gw2_Launchbuddy#181]
![image](https://user-images.githubusercontent.com/65840215/82744877-cb5e9600-9db0-11ea-9f49-bf0d335dbbff.png)
why i can't star....

**Comment by 147172654** [comment]
help....THX....

**Comment by 147172654** [comment]
only star one game...can't open 2....

**Comment by TheCheatsrichter** [comment]
I am sadly not familiar with the chinese client of gw2 and do not have the client to test it on my end.
My best guess would be that your Gw2.dat was not run with the -shareArchive argument. Have you been able to use older versions of LB?

**Comment by 147172654** [comment]
> I am sadly not familiar with the chinese client of gw2 and do not have the client to test it on my end.
> My best guess would be that your Gw2.dat was not run with the -shareArchive argument. Have you been able to use older versions of LB?

1.6   1.7  1.9 ALL don't star 2.......BUT,i copy 2 GW2 folder in  D and E ....Step1, LB GW2,ok,star,Install Path is D:\GuildWars2\GW2-64.exe...Step2,Set Directory,E:\GuildWars2\GW2-64.exe,and LB GW2.ok,star...Although it can be started in this way, I still hope not to copy multiple clients

**Comment by KairuByte** [comment]
This is likely a mutex issue. Someone would need to run the Chinese version to the point where the handle is set, and verify the string.

**Comment by 147172654** [comment]
> This is likely a mutex issue. Someone would need to run the Chinese version to the point where the handle is set, and verify the string.

...i need Someone,thank~.......and 2.20,Start crash...Exchange2.15

**Comment by 147172654** [comment]
> run the Chinese version to the point where the handle is set, and verify the string.

and how to run the Chinese version to the point where the handle is set, and verify the string....if i can,i do it...thank you ~

**Comment by 147172654** [comment]
> I am sadly not familiar with the chinese client of gw2 and do not have the client to test it on my end.
> My best guess would be that your Gw2.dat was not run with the -shareArchive argument. Have you been able to use older versions of LB?

how can run  Gw2.dat with the -shareArchive ....i use older LB also can't star 2 in ONE client...thank you~

**Comment by 147172654** [comment]
![1](https://user-images.githubusercontent.com/65840215/83465057-46a50380-a4a5-11ea-80e3-a13b4c3c5926.png)
![2](https://user-images.githubusercontent.com/65840215/83465060-486ec700-a4a5-11ea-8025-78ece1641e67.png)
![3](https://user-images.githubusercontent.com/65840215/83465064-4a388a80-a4a5-11ea-93ee-ff0c7f41b738.png)
![4](https://user-images.githubusercontent.com/65840215/83465066-4c024e00-a4a5-11ea-9fd3-f15a8f5ba3b2.png)
![5](https://user-images.githubusercontent.com/65840215/83465067-4d337b00-a4a5-11ea-9223-2c745e0a21b4.png)
.....What happened after I started LB now.....if i want STAR 3,4,5,must copy 3,4,5client in Different partitions...GOD~

**Comment by 147172654** [comment]
The Chinese version of the account is not only email, but also can use mobile phone and custom personalized account registration, now automatically login account can only add email, I hope you can open the function to add various accounts, thank you



---Original---

**Comment by KairuByte** [comment]
Unfortunately, unless one of us gets their hands on the client we are likely not going to be able to do much. The problem I have found while trying to accomplish this in the past, is that accounts seem to be directly tied to "you the person" meaning that it is exceedingly hard for someone outside of China to get and use an account.
