### ISSUE TITLE
Please add -mumble to the list of Arguments

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [TheCheatsrichter/Gw2_Launchbuddy#183]
Being that GW2Taco is now supporting multiboxing.  This would be a great addition for LaunchBuddy.

Quote from GW2 Taco:

> Enabling multiboxing support is a bit involved and will require the popular launcher applications to support the -mumble <filename> command line parameter for GW2. This parameter tells the game instance what to call the mumble connection instead of the standard name MumbleLink, and this allows multiple clients to communicate through this interface without overwriting each others' data. TacO now also supports the -mumble <filename> command line parameter which lets TacO know which Mumble interface to connect to. The rest is handled automatically. In order to be able to run multiple TacO instances, the overlay must also be started with the -forcenewinstance command line parameter.

**Comment by TheCheatsrichter** [comment]
I am allready in contact with the dev of TACO for several days now. We allready have a running prototype which is currently in it's testing phase.

**Comment by SaiyanOfDarkness** [comment]
When you release it, might want to include some type of "how to use" document.  As looking at it says something about needing a process ID, which might be confusing to some people.

**Comment by KairuByte** [comment]
I have yet to see the code, or work with the TacO changes, but there will likely be no need for any user interaction beyond the initial “I want TacO to multi box” checkbox/button/UI element/plugin interface/etc.
