### ISSUE TITLE
Version 2.2 Shows as V 1.9 Prerelease in Windows Task manager

### ISSUE THREAD

**Issue by SeparGW2** [TheCheatsrichter/Gw2_Launchbuddy#186]
![2_2 as 1_9](https://user-images.githubusercontent.com/31021448/83559582-cdc49c80-a4e2-11ea-8ccd-dc62edeaaeb1.PNG)

**Comment by SaiyanOfDarkness** [comment]
I was just about to mention that as well lol.. glad to see I wasn't the only one that noticed :zany_face:

**Comment by TheCheatsrichter** [comment]
Fixed with
4f40f33ced1075cd87f63b13c69d169bbd867a5c
