### ISSUE TITLE
Version 2.2.0 is detected as a virus when downloading in chrome

### ISSUE THREAD

**Issue by maelstromsh** [TheCheatsrichter/Gw2_Launchbuddy#187]

**Comment by Belelusat** [comment]
BitDefender's antivirus is also treating this as a virus. And a scan at virustotal doesn't look good.
https://www.virustotal.com/gui/file/60b35b65e151a7113697c66c346a3464aabcae8b79451c4bd9dd1759caa9b298/detection

**Comment by AMBonz** [comment]
McAfee is also detecting a virus.  I was wondering why when I upgraded the exe just disappeared instead of updating, and it was McAfee quarantining the file.

**Comment by Aleron82** [comment]
Same with Webroot. I created an override for it, but still getting deleted.

**Comment by TheCheatsrichter** [comment]
Closing. Further for further discussion please use https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/207
