### ISSUE TITLE
-nomusic doesn't do anything

### ISSUE THREAD

**Issue by kazerniel** [TheCheatsrichter/Gw2_Launchbuddy#190]
when selected for a profile. `-nosound` works all right. I tried adding `-nomusic` to an external shortcut and it works that way, so the issue must be with Launchbuddy,

**Comment by cyantheum** [comment]
I'm unable to get the nomusic arg working even outside of Launchbuddy, so it might be an issue with GW2 itself?

**Comment by kazerniel** [comment]
It worked for me back in July outside of Launchbuddy.
