### ISSUE TITLE
Blish HUD can no longer access Mumble Link

### ISSUE THREAD

**Issue by dlamkins** [TheCheatsrichter/Gw2_Launchbuddy#191]
Following the changes introduced in https://github.com/TheCheatsrichter/Gw2_Launchbuddy/commit/77315bab5d59e0eee7ae82048892fd73e6ee9e7c those using Blish HUD are now having issues.

For context, I am one of the main contributors for the Open Source project [Blish HUD](https://github.com/blish-hud/Blish-HUD).  In quick summary, Blish HUD is an alternative overlay with "module" support.   For instance, we have modules which re-implement TacO features such as marker packs, compass, etc.

The issue introduced is making it difficult for Blish HUD users to take advantage of features / modules that utilize the Mumble Link API.  This appears to be related to the naming scheme utilized in https://github.com/TheCheatsrichter/Gw2_Launchbuddy/commit/77315bab5d59e0eee7ae82048892fd73e6ee9e7c#diff-1dc9cdcb397b5f63e61dc9ab2ef6c12aR58 which deviates from the default which is what Blish HUD expects by default.  This would be expected for users utilizing the new TacO integration, but it seems to be affecting users that are not using the new functionality which is the main concern.

Additionally, this has broken the multi-box support for Blish HUD (which works similarly to how TacO now supports it) with a launch option changing the name (see our supported [launch options](https://github.com/blish-hud/Blish-HUD/wiki/Launch-Options#-m---mumble-)).

I'm asking primarily on behalf of our users.  We've seen a large spike in issues related to using Blish HUD with Launchbuddy in recent weeks.  Launchbuddy was also what we did our original testing with for multi-box support (adding a custom launch param in to the XML file, to add support manually) which naturally stopped working after the change.

As an aside, #188 could potentially be related, but almost certainly isn't the root cause we're experiencing here.

---

I'm not necessarily sure what the best way would be to resolve this for other projects attempting to utilize Mumble Link outside of TacO, but was hoping to open a dialogue here to determine our best steps going forward.

Thanks!

**Comment by TheCheatsrichter** [comment]
Commited changes accordingly for next release.
6702edf19336c95b98d2724d8807f03c79d18f48

Other test than TACO are pending.
