### ISSUE TITLE
Invalid Login file 1 please recreate this file in the account Manager

### ISSUE THREAD

**Issue by mrgrumpon** [TheCheatsrichter/Gw2_Launchbuddy#193]
It appear whenever i open LB, how to fix it, thank you.
![image](https://user-images.githubusercontent.com/69020950/88986193-80a35200-d2fc-11ea-83bb-71b9b208e7b8.png)

**Comment by kevklam** [comment]
This just started happening for me too today, one of my accounts. I tried setting a new loginfile but it never recognizes when I login.

**Comment by kevklam** [comment]
shrug it eventually accepted a new login so I guess issue closed for me...
