### ISSUE TITLE
Addon not loaded in second instance

### ISSUE THREAD

**Issue by Paroyer** [TheCheatsrichter/Gw2_Launchbuddy#194]
For some reason since the last version my addon (Reshade/Radial/Arcdps/d912pxy) only get loaded in the first instance I launch and wont load at all in the second one. Even when I try to inject the .dll the game launch with out prob but nothing in game while the first account dont even need .dll injection. 

Any help is appreciate tyvm!

**Comment by Swystix** [comment]
Having the same issue as above, no arc/radial/d912pxy/reshade on any alt accounts. Only working on main.

**Comment by unrelentingsarcasm** [comment]
My Arc/D912pxy/ReShade set up is working on all accounts for me, but I've never been able to get Radial to work, or Yolomouse for that matter.  How do you guys have Radial set up?

**Comment by paroyer** [comment]
In the end I think i found out to do, been a couples days im running it like this. I've downloaded the AddonManager and now I instal/update everything via this tool, except reshade infact. Then I just inject reshade (dxgi.dll next to the game launcher), d3d9.dll in /bin64 and finally gw2addon_d3d9_wrapper.dll in /addons/d3d9_wraper/ (Installed with the AddonManager). Both account are set up that way with LaunchBuddy and every addons work perfectly just some crash sometimes if I try to open both at the same time

**Comment by ihavenodamage** [comment]
I didn't understand, save me

https://youtu.be/38XJTWy0-KU
