### ISSUE TITLE
GW2 Launchbuddy fails to start since latest windows update.

### ISSUE THREAD

**Issue by FixedDevice** [TheCheatsrichter/Gw2_Launchbuddy#196]
Whenever I try to use the application, gw2.launchbuddy.exe doesn't even load up. It's not blocked by my firewall and I've tried running as admin.

My OS build is 18362.1016

**Comment by unrelentingsarcasm** [comment]
I am having the same issue, even after I uninstalled the Windows Update.  Also, ArcDps updated on 15 Aug, but I was having the issue with LaunchBuddy both before and after I updated Arc.

**Comment by unrelentingsarcasm** [comment]
Is anyone working on fixing this issue or have an idea about how to fix the issue?  LaunchBuddy was awesome for allowing me to use ArcDPS and still inject the d912pxy fix, and even let me load Reshade on top of those, but now its basically nonoperational.

**Comment by TheCheatsrichter** [comment]
Should be fixed with moving settigns to a custom xml fiel stored in the appdata folder.
Propertie.Settings.Deafult seems to hate List classes.

c56c7cfb45fcbe803bd934c6a7638c4ea1224459

**Comment by FixedDevice** [comment]
> Should be fixed with one of the lastest commits--> moving setting to a custom xml file stored in the appdata folder.
> Properties.Settings.Default seems to hate List classes.
> 
> [c56c7cf](https://github.com/TheCheatsrichter/Gw2_Launchbuddy/commit/c56c7cfb45fcbe803bd934c6a7638c4ea1224459)

Yup, works just fine now. Thanks for the fix!
