### ISSUE TITLE
0.8 Whitescreens Gw2 

### ISSUE THREAD

**Issue by Silveress** [TheCheatsrichter/Gw2_Launchbuddy#2]
As title, whenever I launch Gw2 it white screens. 
I use Autologin so that may have an issue with it. 
No multiboxing.

**Comment by TheCheatsrichter** [comment]
A white screen happens if:

- Invalid arguments are used
- Login data isnt correct
- Or arguments are used twice! (make sure not to select a gw2.exe shortcut)

**Comment by Silveress** [comment]
I hadnt typed in the password correctly.

Small note on that, if you are going to have passwords unviewable and uneditable it would be best if you made the password input box a bit bigger. my password is long enough that half was obscured when I put it in.
