### ISSUE TITLE
Ambient Occlusion ?

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [TheCheatsrichter/Gw2_Launchbuddy#203]
Noticed the option for Ambient Occlusion was missing from graphic configuration

Is this not possible to be added?

**Comment by TheCheatsrichter** [comment]
Launchbuddy actually reads the gfx config file from the Gw2 appdata folder (the .xml file in there) and creates GUI based on that. If this setting is not included in the .xml it likely is stored somerwhere else. I don't know why arenanet stores some specific graphic settings at a different location,, but LB is limited to the onces available in that xml file.
