### ISSUE TITLE
Second Account doesn't start properly + addon problems

### ISSUE THREAD

**Issue by Zaidya** [TheCheatsrichter/Gw2_Launchbuddy#206]
I only have 2 account's. If I try to start both the second one won't start the game. The Launcher starts, login works but the Game Client doesn't open. I just get an error (Installation wasn't able to finish, please contact support). But if I start the second accound sololy, it opens without any problem. After that I start the first accound and it opens.
The problem here is, only the client, that opens first has my addons included (arc dps, radial, dunno if the directX12 addon loads for both clients..). 
I already did the repair loginfile, recreate loginfile and also did a whole new account setting.

**Comment by SaiyanOfDarkness** [comment]
> The problem here is, only the client, that opens first has my addons included (arc dps, radial, dunno if the directX12 addon loads for both clients..).

Are you placing the files inside the bin64 or are you using LaunchBuddy and going to the Account Settings > Injected Software section and manually applying them to each account?

**Comment by Zaidya** [comment]
oh I was just using the addonmanager for my addons... do you have an manual how I implement the addons in the injected software for dummies? ._.

________________________________
Von: SaiyanOfDarkness <notifications@github.com>
Gesendet: Sonntag, 14. Februar 2021 04:58
An: TheCheatsrichter/Gw2_Launchbuddy <Gw2_Launchbuddy@noreply.github.com>
Cc: Zaidya <Evanescence-Krissy@hotmail.de>; Author <author@noreply.github.com>
Betreff: Re: [TheCheatsrichter/Gw2_Launchbuddy] Second Account doesn't start properly + addon problems (#206)


The problem here is, only the client, that opens first has my addons included (arc dps, radial, dunno if the directX12 addon loads for both clients..).

Are you placing the files inside the bin64 or are you using LaunchBuddy and going to the Account Settings > Injected Software section and manually applying them to each account?

**Comment by Zaidya** [comment]
Hello I figured out what my second account made crash. It is the d912pxy addon I can install with the addon manager. My first account works fine, the second one crashes. Find detail information here: https://github.com/megai2/d912pxy/issues/346#issue-824005330
My other question about using addons for all accounts is obsolete, I figured that out myself.
