### ISSUE TITLE
Update failed - Virus detected

### ISSUE THREAD

**Issue by NetF1re** [TheCheatsrichter/Gw2_Launchbuddy#207]
I started the update to v2.3.0 and Windows Defender detected it with Trojan:Script/Wacatac.C!ml
So Update failed and old version were deleted :-/

https://www.virustotal.com/gui/file/3bc48bc3cbe8a4216b087dc9217c243eb5d428eccfd76af1a2c13421712ee94e/detection

I was just wondering - I see you have a Virustotal powershellscript in your build process - doesn't that trigger anything?

**Comment by TheCheatsrichter** [comment]
I allready 2.3 submitted it to microsoft for a review. They did approve 2.2.1 , however lets hope that they let 2.3 also pass.

**Comment by TybaIt** [comment]
Affirmed. Clicking on the latest release *.exe causes Bitdefender to raise a false positive with ``Gen:Variant.Razy.678241`` and blocks the site/download.

**Comment by Jiansarys** [comment]
Got detections on the previous release, and now with 2.3 I'm still getting a bunch of hits. https://www.virustotal.com/gui/file/3bc48bc3cbe8a4216b087dc9217c243eb5d428eccfd76af1a2c13421712ee94e/detection

**Comment by Ainillia** [comment]
Hello,

I did work for Avira for a time, i tried to help for this and version 2.3 should have now much much less false positives (bitdefender, avira, MS, KiS, etc) can't talk for McAfee as they work less with others Avs, and for lesser known AV's i don't really know. The detections have already lowered massively, and they should continue to drop for a bit in the next few hours because of AV signature sharing.

Have a nice day ! And thanks for the launcher !

**Comment by TheCheatsrichter** [comment]
> Hello,
> 
> I did work for Avira for a time, i tried to help @TheCheatsrichter for this and version 2.3 should have now much much less false positives (bitdefender, avira, MS, KiS, etc), i just don't know for lesser known AV's but some may become OK due to same engine/signatures. The detections have already lowered massively, and they should continue to drop for a bit in the next few hours because of AV signature sharing.
> 
> Have a nice day ! And thanks for the launcher !

Wow thanks a lot! It is really quite hard to go against these false positives with a such a small budget. I can only try and hope, but with this you did single handedly take many ours of emails and communication off me. Thanks again!

**Comment by TheCheatsrichter** [comment]
Closing issue as it references an old version:
Mainissue:
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/363
