### ISSUE TITLE
Multiboxing - No Gamelaunch after loginwindow

### ISSUE THREAD

**Issue by lamvuong2019** [TheCheatsrichter/Gw2_Launchbuddy#210]
When I select multiple accounts a random number of times it will fail to launch the game. It is listed in the game instances though.

If I launch one at a time, I can login all the accounts (multiple instances)

Not sure if this is a bug or the game launches too quickly that is causing this. Is there a delay timer that I can change?

**Comment by TheCheatsrichter** [comment]
Did the multiboxing work for you in the past?
What LB version are you currently running?

Launchbuddy allready has a delay implemented calculated by:
Math.Pow(i, 2) * 25 + 50

where i is the number of tries to close the mutex (handle that prevents multiboxing).

**Comment by lamvuong2019** [comment]
Multi box is working. I just get random loading issues where the login shows but then no game load.

**Comment by maanlichtje** [comment]
I have this same problem, it happens for me when i have the radial menu addon installed. Once i delete that and let gw2 generate a new .dll again without this addon i can launch multiple accounts again without problems.
