### ISSUE TITLE
1st launch/ configuring launchbuddy invokes massive gw2-client- patch?

### ISSUE THREAD

**Issue by Fra66le** [TheCheatsrichter/Gw2_Launchbuddy#211]
i just downloaded the latest release ont my 2ndary pc. Upon configuring the launch file the gw2-client starts to download some 27k files for about 3-4GB ( judged by extrapolating progress bar after ~800MB) I do not remember this behaviour from when i installed LB on my other PC recently...
What might i be doing wrong?
The GW2 client path is correc.t, however if i try to "set" it in the client, by pointing to the actual executable (gw2-64..exe) the path is listed double in the LB- client. ( as in "C:\gw2\C:\gw2\gw2-64.exe")
if i start the gw2 client normally there's no patch occuring

As i the internet (google) apparently couldn't provide me with any other place to ask, i put it here, although that probably is not a software, rather a "userware" issue.
Thank you for your commitment!

**Comment by SamMackrill** [comment]
I see the same behaviour
