### ISSUE TITLE
Request - Can you please add -windowedfullscreen to the arguments section

### ISSUE THREAD

**Issue by FoxEy3s** [TheCheatsrichter/Gw2_Launchbuddy#212]
When opening GW2 through LB, it doesn't 'remember' the windowed fullscreen setting for some reason. I noticed the there is an argument for that setting. So I was wondering if you can add -windowedfullscreen to the arguments section?

**Comment by TheCheatsrichter** [comment]
This option was included in the past. I can't quiet remember atm why it had to go, but if I remember right there was some technical limitation. I will keep this updated when I reevaluate the option

**Comment by TheCheatsrichter** [comment]
I just checked the gw2 and it doesn't seem to support -windowedfullscreen. Do you have any source of where this information was from?

**Comment by FoxEy3s** [comment]
Well I feel dumb...apparently I must have been looking at the GW1 wiki on accident. I'm sorry I wasted your time and thanks for checking into it!
