### ISSUE TITLE
Account loginfile link broken

### ISSUE THREAD

**Issue by murtatal** [TheCheatsrichter/Gw2_Launchbuddy#213]
since an gw update i can't start the launchbuddy. First it says " Launchbuddy is updating an outdated Loginfile", then "Launchbuddy is waitung for GW2 to save the updated Loginfile" and after that the error message "Invalid Login file 2 please recreate this file in the account Manager".
But how can i recreate this file when i can't open the launchbuddy? 

System.Exception: An error occured when Updating the Login file. An error occured while swaping the Login file.Provided Local.dat file does not exist or Linkfile is already created.
   bei Gw2_Launchbuddy.Modifiers.LocalDatManager.UpdateLocalDat(LocalDatFile file)
   bei Gw2_Launchbuddy.ObjectManagers.AccountManager.UpdateAccountFiles()
   bei Gw2_Launchbuddy.ObjectManagers.EnviromentManager.AfterUI_Inits()
   bei Gw2_Launchbuddy.MainWindow.Init()\n   bei System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   bei System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   bei System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   bei System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   bei System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   bei System.Windows.Application.DoStartup()
   bei System.Windows.Application.<.ctor>b__1_0(Object unused)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   bei System.Windows.Threading.DispatcherOperation.InvokeImpl()
   bei MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Windows.Threading.DispatcherOperation.Invoke()
   bei System.Windows.Threading.Dispatcher.ProcessQueue()
   bei System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   bei MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   bei System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   bei System.Windows.Application.RunDispatcher(Object ignore)
   bei System.Windows.Application.RunInternal(Window window)
   bei Gw2_Launchbuddy.EntryPoint.RunParsed()
   bei Gw2_Launchbuddy.EntryPoint.Main(String[] args)

any help? thx

**Comment by TheCheatsrichter** [comment]
Seems like the accountlist somehow got corrupted.
How many accounts do you normally use?
If they only are a handfull it would be easy to just delete %appdata%\Gw2 Launchbuddy\Accs.xml. This will erase the configured accounts, but you will have to reenter all the settings...

If this isn't an option for you please let me know.

**Comment by murtatal** [comment]
thx for your help :) it worked. i only had 3 accounts, so it wasn't a big effort to recreate the settings
