### ISSUE TITLE
Launchbuddy Icon Import Crash

### ISSUE THREAD

**Issue by grze151** [TheCheatsrichter/Gw2_Launchbuddy#214]
For the past few weeks, this been happening to me whenever I try to use gw2 launch buddy, I love the program but have no clue how to fix this issue. I tried deleting %appdata% files but it doesn't help :(

Exception Type 
System.OverflowException

Message
The image data generated an overflow during processing.

Source 
PresentationCore

Stack Trace
System.ArithmeticException: Overflow or underflow in the arithmetic operation.\n   at System.Windows.Media.Imaging.ColorConvertedBitmap.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at Gw2_Launchbuddy.ObjectManagers.IconManager.Init()
   at Gw2_Launchbuddy.ObjectManagers.EnviromentManager.Init()
   at Gw2_Launchbuddy.EntryPoint.RunParsed()
   at Gw2_Launchbuddy.EntryPoint.Main(String[] args)

**Comment by TheCheatsrichter** [comment]
Seems like something got broken by imported icons. Go to %appdata%/Gw2 Launchbuddy and delete the icon folder

**Comment by TheCheatsrichter** [comment]
Might be similar to https://github.com/dotnet/wpf/issues/3884 currently investigating

**Comment by WolfSabian** [comment]
This appears to have been resolved.

Working fine for me on 2.4.2
