### ISSUE TITLE
UI Blank Startup

### ISSUE THREAD

**Issue by Rheiloth** [TheCheatsrichter/Gw2_Launchbuddy#215]
Hello, first of all thank you for your work.
It was working great until recently.
The addon starts normally and updates the game and all but after this it does not actually display the UI, when I mouse over the icon on the windows bar it's completely blank.
I don't have any clue as to why since I didn't play for a few days and all of a sudden it's kinda broke.
Tried a few basics steps, windows manager/restarting/pc restart/delete & re download/ start as admin / etc..

Any ideas ?
Thanks for your time

**Comment by TheCheatsrichter** [comment]
I need a bit more information here.
Launchbuddy itself is not shown when you start it or some sort of addon?

**Comment by Rheiloth** [comment]
Launchbuddy itself is not shown. When there is a gw2 update, it does update the game and itself but then I don't get the actual interface.
As seen on the screen

![update](https://user-images.githubusercontent.com/33836042/112549018-6e12e700-8dbd-11eb-906b-0ca65027931c.PNG)
![noshow](https://user-images.githubusercontent.com/33836042/112549063-7e2ac680-8dbd-11eb-9acb-30de9e831566.PNG)

**Comment by Rheiloth** [comment]
Well I was digging a bit deeper and I found the files in appdata, I deleted those and now it works. must have been some hiccups in the data or config files. Gotta setup my accounts again tho
Thanks anyway !
I'll wait a bit if you have an idea before closing the issue

**Comment by Rheiloth** [comment]
Hey, I just wanted to let you know since I figured out what happened and it doesn't have much to do with your program.
It's just that the launchbuddy window was on my third screen usually but on another setup I have only 2, so the UI was on a ghost screen, just had to move it with maj+windows+arrow

Have a good one
