### ISSUE TITLE
Cannot build due to missing .csproj

### ISSUE THREAD

**Issue by Lego6245** [TheCheatsrichter/Gw2_Launchbuddy#218]
You cannot build Gw2_Launchbuddy from source without the LBTacoPlugin.csproj project, a plugin which references a location outside of the working directory of this repository.

Please either move the LBTacoPlugin.csproj into this repository, provide a method to download the source (the Gw2LBPluginTemplates repository appears stale) or remove it as a direct dependency for build.

**Comment by TheNasbit** [comment]
You don't have to build the entire solution, you can also just build the Gw2 Launchbuddy project. So there is no need for the LBTacoPlugin project to build launchbuddy.

**Comment by Lego6245** [comment]
If it's not a dependency (i.e, not required to build), then it should probably not be included in the csproj as a dependency.
