### ISSUE TITLE
The URL cannot be empty. Parameter name:url

### ISSUE THREAD

**Issue by nickbraun7** [TheCheatsrichter/Gw2_Launchbuddy#223]
Having an issue where accounts aren't able to be added, with the crash "The URL cannot be empty." Additionally, the GW2 path seems to have an issue where the path is repeated.

![image](https://user-images.githubusercontent.com/20498900/114743835-0e07c480-9d1b-11eb-8cf1-a0166c2edb55.png)

![image](https://user-images.githubusercontent.com/20498900/114743513-c1bc8480-9d1a-11eb-9e71-75e5b8c2ec47.png)

**Comment by TheCheatsrichter** [comment]
Should be fixed with:
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/commit/a5363c0d5f45eafded90c2186639e479f6aa23a8
