### ISSUE TITLE
Non Responsive Crash

### ISSUE THREAD

**Issue by seanbarr1988** [TheCheatsrichter/Gw2_Launchbuddy#229]
I use gw2 launch buddy with about 15 accounts. every time I try to log into them 1 by 1 the app crashes every 3rd or 4th login.
in the task manager the app is non responsive and "suspended". I believe this is happening due to windows 10 trying to suspend the app in the background causing it to crash.

**Comment by TheCheatsrichter** [comment]
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/releases/tag/2.3.8 should be fixed with this. Pls report back if it still exists.
