### ISSUE TITLE
Had to rebuild my loginfiles for all of my accounts, today

### ISSUE THREAD

**Issue by Koviko** [TheCheatsrichter/Gw2_Launchbuddy#230]
After today's patch, I had to rebuild my loginfiles in order to log in to more than one accounts.

This is mostly an FYI for other people who come here looking for solutions.

It took multiple tries for some of the accounts.

**Comment by yusoffb01** [comment]
thanks that helped. I thought there was an internet issue

**Comment by PalantirTinuviel** [comment]
I now deleted all accounts. After creating the first account, it worked properly. But i recognized, that after loggin out, the accounts logged in automatically to the char-screen.
After creating a second account, LB overwrites the data of the first account. Deleting application data or LB-Folder didn't change a thing.

**Comment by Gragx** [comment]
Same for me after the May 11th update

**Comment by Koviko** [comment]
Now, whenever Launchbuddy tries to automatically update loginfiles and it looks like it fails, I just manually re-set them and am able to continue as usual.

A failure seems to look like:

1. LaunchBuddy's small "updating loginfile" window pops up
1. GW2's launcher opens
1. The password is empty and the the login never happens
1. If I attempt to enter a password, set GW2 to remember the email and password, and log in, LaunchBuddy never recognizes it as a successful login

**Comment by mwrich4** [comment]
I've had to do this for almost every patch for a long long time.  Quietly hoping for a resolution someday.  

I have my main account at the top of the list. I always update the login.dat file for that one last so when I launch gw2 from the desktop the credentials will be for 'main' account.

**Comment by TheCheatsrichter** [comment]
Likely a duplicate. Please reopen if not. https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/237#issuecomment-850362540
