### ISSUE TITLE
Multiple Account Login Issue

### ISSUE THREAD

**Issue by Bwachtel** [TheCheatsrichter/Gw2_Launchbuddy#240]
I tried using Launchbuddy a while back, maybe a month ago? and i had issues where when creating multiple accounts, when trying to log into all of them at once, it would all be just a duplicate of the same account. I gave up and didnt touch it again. I decided to look again today since i recently turned 2 of my alts into full accounts and i noticed that there was an update that appeared to fix my issue. But when trying it this go around, i can get my main account and 1 alt account to load, but then any account after that is just a duplicate of the alt account. Any ideas on how to fix this?

**Comment by Bwachtel** [comment]
Is anyone able to help with this issue? Launchbuddy is pretty unusable if it doesnt allow me to log into multiple accounts at once.

**Comment by Impulse193** [comment]
I am actually having the same issue and i have not found a resolution as yet

**Comment by Bwachtel** [comment]
Yep, i still have the issue. Was hoping to find help here but it doesnt look like i will find it. I guess i will have to just manually log into each one each day... a PITA but what can you do.

**Comment by Bwachtel** [comment]
Checking to see if anyone is able to help with this issue??

**Comment by Impulse193** [comment]
these are the errors that i get.
I tried a few things but couldnt find a fix 

![23457828-7D29-4771-90FA-131D6603191A](https://user-images.githubusercontent.com/85320750/121006963-1d255480-c757-11eb-9871-ee807a4296d8.jpeg)
![EEEB7AD2-B1D0-40A2-AF82-42C10FAD2BF8](https://user-images.githubusercontent.com/85320750/121006970-20b8db80-c757-11eb-909a-c2641370e29b.jpeg)

**Comment by Bwachtel** [comment]
I dont get any errors, it just logs me into the same account multiple times even though i set the login correctly (to my knowledge) for each individual account.

**Comment by TheCheatsrichter** [comment]
Should be fixed with 2.3.8 https://github.com/TheCheatsrichter/Gw2_Launchbuddy/releases/tag/2.3.8
Please report back if the error still exists for you

**Comment by Bwachtel** [comment]
Just tested,
- updated client to 2.3.8 via the update button in the app.
- Re did "set loginfile" for account #2 and #3.
- Left Main login file alone.
- Tried logging into all 3:
        - Main logged in once
        - Alt #3 logged in twice
        - Alt #2 did not log in.

I have discord and would be willing to do a voice call and share screen if that would help.

**Comment by Bwachtel** [comment]
any updates? Anything else you would like me to test?

**Comment by Bwachtel** [comment]
I havent heard of any updates on this, but i just checked to see if there was an update to launchbuddy and there was. But this update did not fix the issue i am noticing.

**Comment by Bwachtel** [comment]
I see that someone put links in one of my posts? i assume they are explaining the solutions to the issue? 

I decided to try it again and deleted all of my profiles and recreated them all and it now works. Not sure what the issue was, but it works now, so im happy.
