### ISSUE TITLE
Gw2_Launchbuddy 2.3.5 - trojan detected Trojan:Script/Wacatac.B!ml

### ISSUE THREAD

**Issue by pektus** [TheCheatsrichter/Gw2_Launchbuddy#241]
just updated to 2.3.5 from 2.3.4 when prompted and Windows Defender tagged it as an infected program. reverting back to 2.3.4 for now.
![image](https://user-images.githubusercontent.com/9129050/120095902-1e54f100-c15b-11eb-8086-e57ff1b45232.png)

**Comment by Almdoodler** [comment]
Having the same issue when trying to update from 2.3.8 to 2.3.9. although for me it's not reporting the launchbuddy.exe as the "culprit" but rather the updater, as can be seen in this screenshot:
![image](https://user-images.githubusercontent.com/8082125/121333136-d1220d80-c918-11eb-9dfd-a3004f05db09.png)
(Sorry for it being in german, it's basically the same as the other screen posted by @pektus except for the file part which links to the updater of launchbuddy)

**Comment by TheCheatsrichter** [comment]
Closing issue as it references an old version:
Mainissue:
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/363
