### ISSUE TITLE
V2.3.5 issues

### ISSUE THREAD

**Issue by aganod** [TheCheatsrichter/Gw2_Launchbuddy#242]
When I launch V2.3.5, I get the pop up "Guild Wars 2 info file not found! Please choose the directory manually!" It shows up twice. After clicking on OK for both these pop ups, I get the following pop up: "LB could not find any default graphic settings file. Launch gw2 at least once to fix this issue." I also get this message twice. As suggested to launch gw2, I am launching the game.

Now back to LB, when going to account settings, and going to Login Credentials and trying to Set Loginfile I keep crashing. Any ideas if this is could be a problem on my end?

**Comment by TheCheatsrichter** [comment]
Launching Gw2 without LB at least once and close it gracefully. Afterwards these erros should dissapear
