### ISSUE TITLE
Creating/Recreating Loginfile overwrites all accounts' loginfile

### ISSUE THREAD

**Issue by jdes375** [TheCheatsrichter/Gw2_Launchbuddy#243]
I can recreate individual loginfiles for each of my accounts, but once I have done so it applies to each account. I can recreate for each account and it uses the correct info for each account but just overwrites the others.

**Comment by sn0opy** [comment]
Probably a duplicate of #235 which has just been fixed.

**Comment by hansyulian** [comment]
i got the same problem, gonna try to check #235
