### ISSUE TITLE
Launch GW2 with user's permissison instead of elevated/admin permissions

### ISSUE THREAD

**Issue by sn0opy** [TheCheatsrichter/Gw2_Launchbuddy#246]
Got a feature request/change in regards of launching the GW2.

I assume Launchbuddy requires admin permissions to move loginfiles around. Unfortunately it also starts the game with elevated permissions causing other programs to bug out a bit. 

I realized this the first time when I wanted to use Discord's push to talk which doesn't work when GW2 is in focus while being launched by Launchbuddy. Discord even notifies the user that it requires admin permissions as well to make push to talk work again.

**Comment by Lego6245** [comment]
If you are comfortable building from source, my fork which I try to keep maintained / synced with the main branch does this by using Window's built in dev mode to enable that. You will need to enable Window's dev mode, but once you do you can launch Lauchbuddy with user permissions and everything will just work.

**Comment by Junktroep** [comment]
I downloaded you source lego compiled it with visual studio.
Enabled dev mode. Re-enabled UAC but it still runs elevated

**Comment by Lego6245** [comment]
Not sure what else to say. I double checked my repository, and if you checked out my branch and clean built from source, and are running the built output in the /bin/debug folder, it should not prompt you for UAC if you are not running it manually as administrator.

**Comment by Junktroep** [comment]
Did a redownload en extract to other map.
Did rebuild and now its working without elevation.
Maybe I mixed yours and cheats up.
Thanks man... Cheers!

**Comment by asheimo** [comment]
Is this still valid, the other branch is 306 commits behind and the main branch produces an error when trying to build 
`A numeric comparison was attempted on "$(MsBuildMajorVersion)" that evaluates to "" instead of a number, in condition "($(MsBuildMajorVersion) < 16)".	`

**Comment by Lego6245** [comment]
I've since moved on to using a different tool to manage my GW2 logins, so I haven't maintained my fork. In theory, if you were to just take my fork and merge in master (assuming master builds), you should still be able to get my changes, the changes I made to make my copy work in this way are simple and self contained.
