### ISSUE TITLE
Invalid Login file 4 please recreate this file in the account Manager

### ISSUE THREAD

**Issue by Marke3000** [TheCheatsrichter/Gw2_Launchbuddy#247]
Hi guys,

When i launch Gw2.LaunchBuddy.exe i get a popup saying "the launchbuddy is updating a login file , this window will close automatically" etc. Then the gw2 launcher pops up for a second and after a few seconds i get "Invalid Login file 4 please recreate this file in the account Manager" and when i close the bar or click 'OK' it goes into an infinite loop until i use taskmanager to close the app.

Tried deleting , downloading and re-launching Gw2.LaunchBuddy.exe but i keep getting the same error. It worked fine yesterday. Could anyone please help me with this. Is there a way i can re-create the login file without the app openig?

**Comment by Koborakai** [comment]
I'm having the same issue with the "Invalid Login file" error message and I tried the same solutions. I can't even get to the main screen of Launchbuddy, which I was able to before. I also noticed that my antivirus was automatically set to block Launchbuddy. I set it to trust Launchbuddy but I'm still having the issue. 

Maybe this is a bit different for mine, but the GW2 launcher does eventually stay open for me after infinite looping a couple times, with the infinite loop still able to go on in the background without closing and re-opening the launcher. Now on the GW2 launcher before I log in with my credentials, nothing happens during the loop. After I do log in and click "login" and then "ok" on the error message (I don't start the game), it attempts to update the Loginfile in the same loop, but I see that it tries to automatically do something where it clicks the "play" button in the launcher two times in quick succession, which fails to do anything and then the error message appears again immediately after.

Nothing changes with the loop if I click "play" in the launcher myself to start the game. I'm a bit out of my depth here, but I hope somebody with some knowledge might be able to shed some light on what's going on here. I hope I described what I saw well enough. Can anybody help?
