### ISSUE TITLE
Only one instance launching

### ISSUE THREAD

**Issue by hukyly** [TheCheatsrichter/Gw2_Launchbuddy#248]
Hello,

whenever i try to run 3 accounts at once only 1 of them is actually launched, other two stay in Task Manager as shown in picture.
![image](https://user-images.githubusercontent.com/25354634/121349320-a9877100-c929-11eb-9f54-00cecae82d58.png)

After waiting few minutes these 2 popups happen and then my PC runs out of RAM ( looks like 2 instances are leaking memory ).
![image](https://user-images.githubusercontent.com/25354634/121349182-8066e080-c929-11eb-8a99-33b7cf561d5c.png)

I tried everything i could think of, reinstalling LB, deleting APPDATA files, re-adding accounts, updating to latest version and nothing helped.

**Comment by Sunriz3D** [comment]
Hello don't know if you still have this problem i had the same.

I had to move the d3d9.dll from arcdps ( because it sideload d912pxy or something )  and put it in an another folder, then in LaunchBuddy in my main account settings I added the d3d9.dll ( the one I moved in another folder ) in Injected Software tab.

**Comment by hukyly** [comment]
Thank you for helping! Definitely issue that i'm running D912pxy with this, as soon as i do what you said it works! I don't know if this is something Launchbuddy dev can fix?

**Comment by Sunriz3D** [comment]
> Thank you for helping! Definitely issue that i'm running D912pxy with this, as soon as i do what you said it works! I don't know if this is something Launchbuddy dev can fix?

No problem glad it worked :)

I doubt the dev can do something about it since it is related to d912pxy. I only use arcdps/d912pxy on my main account now 👍

**Comment by hukyly** [comment]
But weird thing is it worked before on previous versions, when i get time maybe i'll try some of previous versions but i've been running LaunchBuddy with dx912pxy for a year already without issues. Maybe it's also dx912pxy update that bugged it out. Whenever i get time i'll check.
