### ISSUE TITLE
Antivirus false positives

### ISSUE THREAD

**Issue by kazerniel** [TheCheatsrichter/Gw2_Launchbuddy#252]
> Event: Malicious object detected
> User type: Active user
> Component: Virus Scan
> Result: Detected
> Result description: Detected
> Type: Trojan
> Name: UDS:Trojan-Spy.MSIL.Bobik.gen
> Precision: Exactly
> Threat level: High
> Object type: File
> Object name: Gw2.Launchbuddy.exe
> MD5: 25D9D5D595EA82CABA7D8E30BBEB433B
> Reason: Cloud Protection

previous versions didn't have this issue

**Comment by TheCheatsrichter** [comment]
https://www.virustotal.com/gui/file/d2a8a300aac8a0b25fee60ac3970149caa0670d33b37b7922b41b689e7ae3504/detection
currently did not mark it. :o
Is your Kaspersky up to date?

**Comment by Phantom0013** [comment]
![image](https://user-images.githubusercontent.com/77114925/126915942-4667c6c5-abf4-4617-9b7f-53126b955066.png)
same thing here and yes up to date

**Comment by hblaise** [comment]
The same happened to me too, Kaspersky removed the app, had no issues before the update.

**Comment by Cheeseypop** [comment]
Can confirm, also VirusTotal now has 6 flags.

**Comment by yannickcharron** [comment]
Version 2.4.0 is now deleted too by Kaspersky.

**Comment by kazerniel** [comment]
> 
> 
> Version 2.4.0 is now deleted too by Kaspersky.

Yesterday after I rolled back from LB 2.4.1, LB 2.4.0 worked for me fine, but today Kaspersky removed it >_>

**Comment by kazerniel** [comment]
> 
> 
> https://www.virustotal.com/gui/file/d2a8a300aac8a0b25fee60ac3970149caa0670d33b37b7922b41b689e7ae3504/detection
> currently did not mark it. :o
> Is your Kaspersky up to date?

Yeah, I'm using Kaspersky Free v21.3.10.391 (d). Database is also up to date.

**Comment by Atros04** [comment]
> https://www.virustotal.com/gui/file/d2a8a300aac8a0b25fee60ac3970149caa0670d33b37b7922b41b689e7ae3504/detection
> currently did not mark it. :o
> Is your Kaspersky up to date?

Also a Kaspersky user with the same issue. Total is now 7 flags as of comment.
Can also confirm older versions are now being flagged for the same trojan.

**Comment by clammers7** [comment]
I use BitDefender Plus, and it removed LB v2.4.1 when I tried to update yesterday. It also flags and removes the temp download file if I try to download it again.

**Comment by Eraithia** [comment]
Also running BitDefender, it keeps quarantening the files and deleting them. This is what happened when I tried to re-download the v2.4.1 exe:
![2021-07-26_21h16_15](https://user-images.githubusercontent.com/88003673/127053210-3d4de596-8cd8-47da-9086-d9f19be71443.png)
I have tried running GW2 separately and have no issues, so for some reason it really doesn't like this new update, to the point it is unusable.

**Comment by AKA-Syenite** [comment]
Running BitDefender, it flagged 2.4.1 as infected, as well as numerous other launchbuddy files and the ACTUAL GW2 .TMP FILES. This resulted somehow in gw2.dat (the main game file) being **wiped**. I'm not going to be using launchbuddy any more. If anyone else is getting this issue I advise either uninstalling launchbuddy or I guess turning off bitdefender (really don't recommend).

**Comment by Atros04** [comment]
> [...]I'm not going to be using launchbuddy any more. If anyone else is getting this issue I advise either uninstalling launchbuddy or I guess turning off bitdefender (really don't recommend).

You don't need to go to that much of an extreme. I am sure the author is working on a fix. LB has and always will be a great application to use, something just got weird in this last update.

**Comment by Apotekar** [comment]
> > https://www.virustotal.com/gui/file/d2a8a300aac8a0b25fee60ac3970149caa0670d33b37b7922b41b689e7ae3504/detection
> > currently did not mark it. :o
> > Is your Kaspersky up to date?
> 
> Yeah, I'm using Kaspersky Free v21.3.10.391 (d). Database is also up to date.
> 
> Btw this file also got deleted when I was trying to download LB from the site manually:
> 
> > Event: Object deleted
> > User type: Active user
> > Application name: firefox.exe
> > Application path: C:\Program Files\Mozilla Firefox
> > Component: File Anti-Virus
> > Result description: Deleted
> > Type: Trojan
> > Name: UDS:Trojan-Spy.MSIL.Bobik.gen
> > Precision: Exactly
> > Threat level: High
> > Object type: File
> > Object name: PW+PnYmM.exe.part
> > Object path: C:\Users\[username]\AppData\Local\Temp
> > MD5: 25D9D5D595EA82CABA7D8E30BBEB433B

Have the same issue it just deleted the file and cant use launchbuddy anymore :( 

EDIT: going back to version 2.3.9 worked so far lets se if it gets deleted aswell .....

**Comment by clammers7** [comment]
> > > https://www.virustotal.com/gui/file/d2a8a300aac8a0b25fee60ac3970149caa0670d33b37b7922b41b689e7ae3504/detection
> > > currently did not mark it. :o
> > > Is your Kaspersky up to date?
> > 
> > 
> > Yeah, I'm using Kaspersky Free v21.3.10.391 (d). Database is also up to date.
> > Btw this file also got deleted when I was trying to download LB from the site manually:
> > > Event: Object deleted
> > > User type: Active user
> > > Application name: firefox.exe
> > > Application path: C:\Program Files\Mozilla Firefox
> > > Component: File Anti-Virus
> > > Result description: Deleted
> > > Type: Trojan
> > > Name: UDS:Trojan-Spy.MSIL.Bobik.gen
> > > Precision: Exactly
> > > Threat level: High
> > > Object type: File
> > > Object name: PW+PnYmM.exe.part
> > > Object path: C:\Users[username]\AppData\Local\Temp
> > > MD5: 25D9D5D595EA82CABA7D8E30BBEB433B
> 
> Have the same issue it just deleted the file and cant use launchbuddy anymore :(
> 
> EDIT: going back to version 2.3.9 worked so far lets se if it gets deleted aswell .....

Based on the fact that VirusTotal said it was clean at first, and that old versions are being affected, my guess is that a new Trojan is out in the wild that happens to have a similar behavior to LB. If an antivirus company uses heuristics to identify that, it might block LB too.

**Comment by Caelus4058** [comment]
![image](https://user-images.githubusercontent.com/77759091/127199449-9905a64c-d608-4954-b599-1b32e7d38fa9.png)

It gets deleted from windows defender aswell

**Comment by TheCheatsrichter** [comment]
Once again had to submit this version to microsoft and kaspbersky for an additional review. Let's hope that the review gets finished pretty soon.

I am not an expert behind the inner workings of these antivirus detections however it seems that they have some sort of delay between the first scan and further analyses from their side? Anyway pretty hard to pinpoint what codechanged triggers these antivirus flags, as I can not just change a few lines an recheck without a delay of a few days...

**Comment by Atros04** [comment]
> Once again had to submit this version to microsoft and kaspersky for an additional review. Let's hope these reviews gets finished pretty soon.
> 
> I am not an expert behind the inner workings of these antivirus detections however it seems that they have some sort of delay between the first scan and further analysis from their side. Anyway pretty hard to pinpoint what codechange triggers these antivirus flags, as I can not just change a few lines an recheck without a delay of a few days...

How is the traction with Microsoft and the Antivirus providers coming along?

**Comment by TheCheatsrichter** [comment]
Closing issue as it references an old version:
Mainissue:
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/363
