### ISSUE TITLE
Deletes itself after the new update

### ISSUE THREAD

**Issue by cymrael** [TheCheatsrichter/Gw2_Launchbuddy#253]
What the title says, basically. I wanted to use it today and it was gone. Wasn't able to install the newest client as it would give me an error, so I got an older version. Seemed to work. Got the update notification, it updated and deleted itself again.

**Comment by M46N3** [comment]
That would be your antivirus deleting it. Most likely a false positive, but will be like that until it's cleared with the different security vendors.

https://www.virustotal.com/gui/file/d2a8a300aac8a0b25fee60ac3970149caa0670d33b37b7922b41b689e7ae3504/detection

@TheCheatsrichter already submited it for review, acording to issue #252

**Comment by cymrael** [comment]
> That would be your antivirus deleting it. Most likely a false positive, but will be like that until it's cleared with the different security vendors.
> 
> https://www.virustotal.com/gui/file/d2a8a300aac8a0b25fee60ac3970149caa0670d33b37b7922b41b689e7ae3504/detection
> 
> @TheCheatsrichter already submited it for review, acording to issue #252

Hm, okay. I guess I have to wait then. Though I've been getting a strange admin error as well, when trying to download any version, which I have not been getting before either.

![Screenshot 2021-07-31 221757](https://user-images.githubusercontent.com/88112422/127751521-abf546fb-71d4-4867-9366-29faaff1bbef.png)
I haven't made any changes to admin rights; does this have to do with my antivirus, too? It works fine with other files I'm downloading.
