### ISSUE TITLE
"Invalid Loginfile 1 please recreate this file in the account Manager"

### ISSUE THREAD

**Issue by Kzaix99** [TheCheatsrichter/Gw2_Launchbuddy#254]
Hello,i wanted to install the Program but there appears an message that says :

"Invalid Loginfile 1 please recreate this file in the account Manager"

but the Manager wont even open :(
any indeas what i have to do now? ^-^''

**Comment by Eraithia** [comment]
Thread #252 covers this issue. If you have an anti-virus it is likely that it is being seen as a trojan and removing the key files to be able to work.
