### ISSUE TITLE
one of my saved accounts does not automatically login

### ISSUE THREAD

**Issue by jacob-keller** [TheCheatsrichter/Gw2_Launchbuddy#26]
I have 3 accounts saved, and the 3rd account does not automatically login when I select it for launch

**Comment by KairuByte** [comment]
So if you select only that third account and click launch, it wont log in? Or do you mean when you try to launch all three accounts?

**Comment by jacob-keller** [comment]
No matter how I select that specific account it never does autologin.

On Jan 4, 2017 7:52 AM, "KairuByte" <notifications@github.com> wrote:

So if you select only that third account and click launch, it wont log in?
Or do you mean when you try to launch all three accounts?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/26#issuecomment-270405013>,
or mute the thread

**Comment by jacob-keller** [comment]
More detail:

I have 3 accounts, 2 of which are rather old, and one of which was created a month ago. Autologin works just fine for the first two older accounts, but the 3rd one does not perform auto login and instead pops up the regular game launcher, and I have to click ok. (note that the 3rd account credentials are my default saved credentials as well).

It does not matter if I open any combination of accounts, the new  account never does auto login, but the other 2 work just fine. Is it something to do with my saved credentials?

**Comment by jacob-keller** [comment]
I figured it out. The password had a quote character in it. Changing the password and autologin works as expected.

**Comment by jacob-keller** [comment]
It might be worth modifying the program so that it warns in this case.

**Comment by KairuByte** [comment]
Ah, I don't think we had considered that a possible problem, because we don't rely on quotations at all in the launching. It's rather odd actually, it must be something internal to C# or .NET that is causing this. Thank you for finding the problem!
