### ISSUE TITLE
Not saving DX11 Beta setting

### ISSUE THREAD

**Issue by TheWhiteWolves** [TheCheatsrichter/Gw2_Launchbuddy#262]
I know just came out so I don't expect you to have already updated for it but thought I'd throw something in to let you know that LB currently isn't handling the new graphics settings that enables the DX11 beta

**Comment by TheWhiteWolves** [comment]
Looks like its stored somewhere in the Local.dat file, just had to copy mine across from a normal login and overwrite the LB created one to get it to keep the setting

**Comment by Lego6245** [comment]
I've opened a PR #263 that should help by allowing you to set the -dx11 command line argument, which should force it to use dx11.

**Comment by dark-thor** [comment]
@TheCheatsrichter can you please create new release version this change?
