### ISSUE TITLE
Resetting graphic and sound settings

### ISSUE THREAD

**Issue by Kotrla** [TheCheatsrichter/Gw2_Launchbuddy#266]
Hey, the program is resseting my graphic settings and sound settings. The sound goes back to full volume, and the graphic settings to fullscreen. This started occuring after i reinstalled my windows.

**Comment by TheCheatsrichter** [comment]
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/commit/2912b65ea6eae9ceb7ec3ea01f7163118a0f2bfe
