### ISSUE TITLE
Importing Graphics Configuration Not Saving

### ISSUE THREAD

**Issue by Alimar777** [TheCheatsrichter/Gw2_Launchbuddy#271]
I added some new accounts to the launcher and they all launch with maxed out graphics. I've attempted to change this by importing a graphics config to no avail. Every time I reboot the launcher it resets all settings to max.

**Comment by hansyulian** [comment]
i have a profile back in win 10, "Main High Profile" and "Main Low Profile". i use the low profile if i want to do the low graphic farming with afk like verdant brink. But today i just installed windows 11 and i no longer able to set per-profile base graphic configuration. are you also in windows 11?

**Comment by Kotrla** [comment]
im on windows 10, same issue

**Comment by Kokit0** [comment]
same issue. last version 2.4.2. Windows 10 of course
