### ISSUE TITLE
API limited exceeded

### ISSUE THREAD

**Issue by WolfSabian** [TheCheatsrichter/Gw2_Launchbuddy#272]
So this happened this evening.  No idea why or what it means.  Game runs fine, but launchbuddy itself will not load.  Crashes immediately with the error.  (the blacked out area is my ip address.)

![lbapi](https://user-images.githubusercontent.com/49987935/140448050-99f99c0f-fc79-450c-aed4-5b761e6bde93.png)

**Comment by WolfSabian** [comment]
So far send to be fine today.

**Comment by TheCheatsrichter** [comment]
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/295

Gonna close this issue and redirect to the newer issue
