### ISSUE TITLE
error messages after 11th account 

### ISSUE THREAD

**Issue by drsegsi** [TheCheatsrichter/Gw2_Launchbuddy#275]
hey guys , so after the 11th login, the game will just put out error messages such as "undefined error" or something with the firewall is off. After you wait for around 2h it seems to be refreshed again and one can start logging in as usual

Is there a way to prevent this from happening?

**Comment by billypumphrey** [comment]
I get something to the liking of "cannot contact the login server".  If I wait, then I can resume going through my accounts.  I think it is a Anet thing but IDK.

**Comment by TheCheatsrichter** [comment]
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/280

Duplicate. Merged with newer issue
