### ISSUE TITLE
QOL Suggestion: Save placement of accounts on monitor, to decrease setup time

### ISSUE THREAD

**Issue by meykel** [TheCheatsrichter/Gw2_Launchbuddy#277]
I can't seem to find this functionality anywhere in the application. It would be great if it were possible to save the account layout and window sizes displayed on the monitor. I open 5 alt accounts and each time I launch the group I have to space them out on the display. Window size is saved and the location for one of the alt accounts seems to be saved also so I may be missing something but regardless a UI change in the game instances window that saved the layout for the multibox group would be nice.  If this is added to launch buddy another UI change could be to have some sorting function in the accounts table of the launchbuddy client that sorts the alt account by multibox layout

![Gw2 Account layout](https://user-images.githubusercontent.com/8836512/143365831-4a4d077b-7d9d-48fa-b5f4-bee9792a683d.PNG)

**Comment by TheCheatsrichter** [comment]
Please try to use the window configuration feature :

Account Settings --> Select Account --> Advanced Settings --> Configure Windowsettings

**Comment by meykel** [comment]
> Please try to use the window configuration feature :
> 
> Account Settings --> Select Account --> Advanced Settings --> Configure Windowsettings

Wow thank you so much this worked perfectly!
