### ISSUE TITLE
Software Engineer offer of help

### ISSUE THREAD

**Issue by SamMackrill** [TheCheatsrichter/Gw2_Launchbuddy#278]
Hi @TheCheatsrichter , I am a software engineer who specialises in modernising code and retro-fitting unit tests.
I have been using LB for a while now and decided to have a look at the code as I had some issues launching more than 4 instances.

I have a version working in .Net 6 and I wonder if you would like me to collaborate as I think this codebase is in need of some uplifts and serious refactoring to break-up some of the longer classes.

Also Unit Tests would be a massive help I think :)

I have it building in VS2022 but it would also be useful to sort out getting this to build in VS Code, dunno perhaps you have this already?

I could create a PR if you want but I don't want to seem like I am butting in

You can contact me:
sammackrill AT gmail.com
GW2: Smacker.6329
Discord: Smacker#5268

--
Sam AKA Smacker

**Comment by TheCheatsrichter** [comment]
Thanks for the offer. Currently I am very busy with some private things. I will however contact you asap (likely on the holidays) when I have e free time slot.

**Comment by SamMackrill** [comment]
I have been developing my own approach targeting login rewards:  https://github.com/SamMackrill/gw2-alternator
I am mostly using your approach underneath let me know if we can collaborate

**Comment by TheCheatsrichter** [comment]
I will contact you as soon as I have some more free time. Currently really busy with basic needs :(

**Comment by SamMackrill** [comment]
No pressure, I am busy getting my Turtle

**Comment by lcdlyxrqy** [comment]
@SamMackrill Do you have a working .NET 6 version of launchbuddy? If so may I have a look at that?

**Comment by SamMackrill** [comment]
> @SamMackrill Do you have a working .NET 6 version of launchbuddy? If so may I have a look at that?

I did last year, I will try and fork it so you can see it.
