### ISSUE TITLE
Change Launchbuddy DataPath

### ISSUE THREAD

**Issue by billypumphrey** [TheCheatsrichter/Gw2_Launchbuddy#279]
There are times that I play on my desktop, times that I play on my laptop.  I am wondering if I can change the location of the settings?  I would try to change them to a place on onedrive (re-directed folder such as documents) so that my settings are the same on both computers.  

Can you?

**Comment by TheCheatsrichter** [comment]
This would be possible yes. However in the past several people feared that their login data either gets copied to unsave locations or is somehow compromised. Therefore LB limited the paths to local machine space only.

But there might be a workaround:
https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/
