### ISSUE TITLE
Launchbuddy with monitor snapping support/multiboxing/multimonitor rig.

### ISSUE THREAD

**Issue by CedarD** [TheCheatsrichter/Gw2_Launchbuddy#28]
More of a suggestion for those of us with multiple monitors. Multiboxing setups open all the windows on the default monitor. However, I would like each instance to open up in a monitor of my choice. So part of the account options would allow us to select options: unset and monitor x, use new monitor for each new instance...

If that is not doable, perhaps an option to have unique process names and windows titles so I can use a monitor management software such as Displayfusion to move the windows to a monitor of my choice.

**Comment by TheCheatsrichter** [comment]
This shouldn't be that hard to implement. My/Our available time to work on this project has decreased drastically. Currently there are more important to fix and update. But I got this on my "Future features list" now.

**Comment by KairuByte** [comment]
I am actually planning on looking into the option of tying all the Guild Wars clients into the LB taskbar item for a cleaner look. In a way similar to Internet Explorer tabs back in the Windows 7 days. Or alternatively a "Switcher" window where you can see each logged in account and the respective window.

**Comment by CedarD** [comment]
Awesome! Yeah, just wanted to make a suggestion. I can workaround it and am patient. I understand that other things take priority, both real life and on severity of action items to take care of with this project. Thanks for adding it to your future features list! :)
