### ISSUE TITLE
DDOS protection - your solution is not working?

### ISSUE THREAD

**Issue by wir3k** [TheCheatsrichter/Gw2_Launchbuddy#280]
> Added a compensation for heavy login usage. Arenanet has some sort of DDOS protection on their loginservers. Therefore if you login 3 or more accounts in quick succession a artificially timeout is added to your normal time to login. Launchbuddy now waits this additional time to correctly press the login button.

Hmmm seems that delay is not correctly setup, could you please check and extend waiting time between next account is trying to log in. I cant get even 2 accs working now.

**Comment by Snaid1** [comment]
I started getting error messages on the 11th account and got to the point where I couldn't log in at all (launching a single account 20 minutes later) was blocked with the error [undefined] that would have been account 27
