### ISSUE TITLE
Backup Account data

### ISSUE THREAD

**Issue by hansyulian** [TheCheatsrichter/Gw2_Launchbuddy#281]
So i have tons of alt accounts for daily login (please dont ask me how many is that "tons"), then yesterday my windows failed update and crashed and i have to reformat it. Then i lost every single account in launch buddy and have to relogging them in one by one. Is there a fast way to backup every single account in my computer? i tried the `%APPDATA%/Roaming/Gw2 Launchbuddy` folder and back it up but every single login file lost its token and have to be relogged in.

**Comment by TheCheatsrichter** [comment]
Launchbuddy accounts are saved as you are allready stated correctly in `%APPDATA%/Roaming/Gw2 Launchbuddy ` in this folder following files/folders affect account information:

`%APPDATA%/Roaming/Gw2 Launchbuddy/Accs.xml`
`%APPDATA%/Roaming/Gw2 Launchbuddy/Loginfiles`

Last time i checked a simple copy of the files worked. I do however not know if anything changed on the gw2 gameclients side.
