### ISSUE TITLE
2 attempts login after request mail authentication

### ISSUE THREAD

**Issue by patrickmaciel** [TheCheatsrichter/Gw2_Launchbuddy#282]
Hi guys.
After I tried to login, GW2 ask for E-MAIL Authentication, but the Launchbuddy cancel the form, back to login and tried again.
So, every attempt to login occurrs 2 times and ANet send me 2 e-mails, because of that somes times API blocked me for some minutes.

It's possible to launchbuddy only try to login one time, and if is find the e-mail code form, it just wait for an inpu?

Sorry for my terrible english.

**Comment by patrickmaciel** [comment]
![image](https://user-images.githubusercontent.com/671670/144858461-a036cca3-f729-4f6b-b833-4c1851d82e8a.png)

here's the evidence.
when Launchbuddy get in this page of launcher, sometimes the cancel button is hit.

I notice that happens more times when I open 2 or more accounts at sametime.

**Comment by TheCheatsrichter** [comment]
Option to toggle automated loginwindow inputs are now considered for the next release.
Thanks for the feedback!

**Comment by TheCheatsrichter** [comment]
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/commit/d388355aca9cedd3e1b46f5e71a2eb2cea0dbebe
will be pushed with next release
