### ISSUE TITLE
German - Guild Wars 2 Settings zerstört

### ISSUE THREAD

**Issue by master1782** [TheCheatsrichter/Gw2_Launchbuddy#284]
Ich benutze mehre Guild Wars 2 Accounts und man hatte mir empfohlen dieses Programm zu nutzen da es angeblich schneller gehen soll mit dem umloggen. Ich habe dieses Programm benutzt und seit dem sind alle Grafik und Einstelleung von Guild Wars 2 zerstört.
Wenn ich in den Kampf gehe (schon bei einem Gegner) brechen die FPS ein. Vorher hatte ich immer 60 FPS und keine nenneswerten Einprüche nachdem ich das Programm benuzt hatte habe ich nur noch 25 - 30 FPS und wenn ich mich im Kampf befinde habe ich nur noch 2 - 5 FPS auch nachdem ich das Programm wieder deinstalliert hatte.
Ich habe sogar schon die local.dat im %appdata%\Guild Wars 2 Ordner gelöscht und alles neu gemacht aber es hat sich nichts geändert.
Dasselbe ist auch passiert auch mit dem Ping vorher hatte ich immer um die 40 - 60 ms und jatzt habe ich  150 -1000 ms

Wo soll ich noch nachschauen um das Programm wieder komplett vom Comupter zu bekommen das alles wieder so ist wie vorher.

**Comment by TheCheatsrichter** [comment]
Launchbuddy überschreibt im Worstcase Szenario nur die GFX Settings im  %appdata%\Guild Wars 2 Ordner.
Hauptsettings der GFX werden im .xml file dort gespeichert. Einige settings im local.dat file.
Falls du diesen wirklich gelöscht hast und deine Probleme tatsächlich nicht verschwanden / schlimmer wurden kann dies nicht mehr mit LB zusammenhängen da keine sonstigen Daten von Gw2 modifiziert werden.
Des weiteren würde eine Latenzzuname sich nicht mit den möglichen Laucnhbuddy Settings decken. LB hat keinerlei Möglichkeiten aktiv Latenz zu steigern.

Es empfiehlt sich ein paar Schritte zurück zu machen und eventuell zu rekonstruieren welche Treiber / Updated in letzter Zeit geändert wurden.
