### ISSUE TITLE
Adding accounts by using clone function issue

### ISSUE THREAD

**Issue by DevLapar** [TheCheatsrichter/Gw2_Launchbuddy#285]
I have added several accounts to launchbuddy using the clone function for faster creation by having all the settings similar (cloned) and then setting login files for each alt seperately through the "Login credentials". For each account I of course added its own appropriate login credentials after the login client opens, I enter the credentials and then it closes (as it should). But upon starting multiple alt clients all of them login to the same account that it has been cloned from. 

So for example:

1. I create alt 1, set all settings + login credentials
2. I clone alt 2 from alt 1 -> change its login credentials
3. I clone alt 3 from alt 2 -> change its login credentials
4. repeat so forth

Then upon starting alt1,2,3 simultaneously they all use the credentials from alt 1. Which eventually results in a lock-out from logging in alt 1 with an {{undefined}} login-client error.

**Comment by TheCheatsrichter** [comment]
Duplicate:
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/235#issuecomment-988328571
Known issue. On the ToDo list for 2.4.3
