### ISSUE TITLE
Configurable "reset.dat" that is used to reset the state of the locale.dat (mainly graphics) when app closes or on user action.

### ISSUE THREAD

**Issue by agaertner** [TheCheatsrichter/Gw2_Launchbuddy#288]
When you open several accounts and then want to quit GW2-UOAOM the graphics settings are set up to whatever account was last opened. If I want to continue with a single instance with my main account I close this app. Unfortunately, all alternative accounts are set to lowest graphics possible so that they open as fast as possible. It is cumbersome worrying about login order.

Describe the solution you'd like
Being able to set a "Reset *.dat" in the apps main settings which can be used to simply reset graphic settngs eg. by either the app copying the dat to the locale.dat when it closes or when you press a button on its main view somewhere.

Kind Regards

**Comment by TheCheatsrichter** [comment]
Most of the graphic settings are stored in the .xml file in the gw2 folder. Launchbuddy actually should swap the current .xml file to a backup location switch out the .xml for the current acc, launch that acc and than reset to the backup. Currently testing why this is happening

**Comment by agaertner** [comment]
There is also the bug that everytime I launch the app for the first time and add all my logins the "Accs.xml" gets all messed up and references the same login.dat under Loginfiles and gives multiple accs the same id. Eg. I create one, then create another profile and the second one will reference the login .dat from the first profile and also shares the same id although a second dat has been created. This happens with every profile after the first until I go into the Accs.xml and fix the references and ids manually once.

**Comment by TheCheatsrichter** [comment]
Should be fixed with
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/commit/ea527da47614bad952eaa716f0c6be11c405746f

Will be pushed with next release
