### ISSUE TITLE
Application suddenly stopped working

### ISSUE THREAD

**Issue by Rumerris** [TheCheatsrichter/Gw2_Launchbuddy#289]
Since today (22DEC21) the GW2LB 2.4.2.0. stopped working.
Immediately on launch, before the profile window even loads, I get an error screen with the message
"De objectverwijzing is niet op een exemplaar van een object ingesteld."
"object reference is not based on an example of an object"

I really don't know what that means.
After closing the message, either by cancel or submit, the application crashes without further information.

**Comment by TheCheatsrichter** [comment]
Seems like some config file got corrupted.
Try to open C:\Users\Adrian\AppData\Roaming\Gw2 Launchbuddy and delete the LBConfig.xml file.

**Comment by Rumerris** [comment]
hey man
at first glance, that seems to work (lets hope it keeps working)

cheers, appreciated!

**Comment by julialtmeyer** [comment]
I am having the same issue but deleteting the mentioned LBConfig.xml does not help.
