### ISSUE TITLE
Custom Windows Theme settings interfere with font color

### ISSUE THREAD

**Issue by nakami** [TheCheatsrichter/Gw2_Launchbuddy#29]
hey, as use a dark mode windows theme, my fonts in Launchbuddy get messed up and as a result making it almost impossible to read the descriptions on the general tab.
may you let me choose the font color myself?
thanks!
![image](https://cloud.githubusercontent.com/assets/6167914/22081680/cd1bc9a4-ddc4-11e6-9d9b-50ab8c9209c3.png)

**Comment by KairuByte** [comment]
This is definitely unintended. Though I think the proper solution is to force a text color rather then allow the user to select it. Users choosing colors on the default config screen is never a good idea.

**Comment by Halvaard** [comment]
Or setup a default light theme and a dark theme
