### ISSUE TITLE
Instant crash whenever launchbuddy is launched

### ISSUE THREAD

**Issue by Ammar1313** [TheCheatsrichter/Gw2_Launchbuddy#290]
Whenever I launch it the program shows a black window and crashes without any kind of error messages.

**Comment by ChiefThree** [comment]
I clicked on Launch Buddy this morning and it disappeared completely did nothing else so I attempted to reload and the same thing happened, any suggestions ?

**Comment by TheCheatsrichter** [comment]
Corrupted LB Config files will nwo be overwritten when import failed.
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/commit/9b22b7a4c7039d73d4f6f463f5b953d393f28bf9

This fix will be pushed with the next release

**Comment by TheCheatsrichter** [comment]
#289
