### ISSUE TITLE
add custom command line arguments support

### ISSUE THREAD

**Issue by lcdlyxrqy** [TheCheatsrichter/Gw2_Launchbuddy#291]
Is it possible to add custom command line arguments support?
In CN clients we need to duplicate gw2.dat files to be able to run multiple clients and that would require the usage of "-dat" argument.
And I'm sure there are many use cases where custom command line arguments would be useful.

**Comment by TheCheatsrichter** [comment]
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/commit/83454fb1472700c99bc6ba1677af0e172c41105f

new feature added.
Coming with next release

**Comment by lcdlyxrqy** [comment]
The new release supports it nicely. Thanks! Gonna close this issue.
