### ISSUE TITLE
API rate limit

### ISSUE THREAD

**Issue by TristisOris** [TheCheatsrichter/Gw2_Launchbuddy#295]
got a error today.

`API rate limit exceeded for *ip*. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)`

i'm using LB like once a day. what kind of limit it means?

**Comment by TristisOris** [comment]
fixed after few hours. anet side problems?

**Comment by TheCheatsrichter** [comment]
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/commit/fcc582cb0d95f5a326fb77cbf24aa0886b3060cc

should be fixed with the next release
