### ISSUE TITLE
No longer able to open more than one instance of GW2

### ISSUE THREAD

**Issue by mhudson5** [TheCheatsrichter/Gw2_Launchbuddy#296]
Since the update on 1/25 (which just "improved server stability"), when trying to open more than one instance of GW2 I receive the client retry error message reading:

"Client XXX got closed or crashed before a clean Start. Do you want to retry to start this Client?"

Opening them one at a time works fine, but obviously I'd like to just pop them all open as I have been doing. GW2LB seemed to update all the login files correctly after the patch was deployed. 

Was considering reinstalling - would there be local files for me to copy so that I don't lose my login info for all my alt accounts? It wouldn't be awful to go through all the accounts/pw again, but would love to not have to.

Thanks for your time and the awesome add on!

**Comment by Nimmidev** [comment]
I have to same problem since the update.

**Comment by Tharylia** [comment]
I have the same problem. Sometimes I have to start all accounts one by one because they "crashed" and sometimes all of them start like they are supposed to do. Can't really understand why that is as nothing changed.
