### ISSUE TITLE
ArcDps - Random multibox crashes

### ISSUE THREAD

**Issue by oats-and-apple** [TheCheatsrichter/Gw2_Launchbuddy#297]
- Quite recently my accounts started crashing randomly with ArcDPS, I get a pop-up:

"Intercepted unhandled exception. Remove any addons and overlays before reporting this to anet" and arc file pops up. I am using killproof and boon table extensions.

- Sometimes when I run multiple accounts, some of them crash with a pop-up saying: 

"Install cannot be completed. Please contact Support." 

It all works ok if I run accounts 1 by 1. The problem begins if I run 3+ accounts at the same time. Then one or two accounts crashes. Does anyone have any solution? :)

**Comment by TheCheatsrichter** [comment]
Both of these error messages do not originate from Lanchbuddy itself.
A random game client crash suggests that something with arcdps is wrong. Could be possible that arcdps has some sort of trouble finding the right memory adresses to read from.
Is everything up to date?

**Comment by oats-and-apple** [comment]
Thank you very much for the reply.

Everything is up to date. I will uninstall Arc tomorrow and test it. I thought that wouldn't be a problem because everything was running flawlessly for months. I will type the result tomorrow :)

Thank you for help!
