### ISSUE TITLE
Cannot launch more than one account at a time.

### ISSUE THREAD

**Issue by AnnieAcrux** [TheCheatsrichter/Gw2_Launchbuddy#298]
I used to be able to launch a few accounts at a time, which is very convenient and saves time. Since a few days ago though, whenever I try to do that it'll only launch the first acc I selected, while for every other I get the message "Client X got closed or crashed before a clean Start. Do you want to retry to start this Client?".
Selecting yes only results in the same message. 
Whelp!

**Comment by awesmdiver** [comment]
I now, unexpectedly, am starting to see the same behavior.  When it happens, I can reboot my system and LaunchBuddy will work fine again and if I keep LaunchBuddy up and running I can use it properly.  However, once I close the app and restart it, the issue returns, and a reboot fixes it.

Sounds like a file lock issue.
