### ISSUE TITLE
0.8 Error in shortcut creation

### ISSUE THREAD

**Issue by Silveress** [TheCheatsrichter/Gw2_Launchbuddy#3]
Error reproduced below:
__________________
Error when creating shortcut. Invalid path?

The system cannot find the path specified. (Exception from HRESULT: 0x80070003)
__________________
Then the install folder pops up.
I placed gw2.Launcherbuddy into the install folder and the same happens.

**Comment by TheCheatsrichter** [comment]
Thanks for the report! Have you tried to use a different path or did you use the path which was automatically selected for you? (Set Directory)
