### ISSUE TITLE
Guild Wars 2 API is not reachable. LB defaults to updating game client.

### ISSUE THREAD

**Issue by PaterFrog** [TheCheatsrichter/Gw2_Launchbuddy#302]
* 3.0.0
* renamed to d3d9.dll since I had issues launching this addon / the game with the addon manager.
* game client version: 124490

Is this an actual issue, or can LB indeed just not reach the API? I can log into the game manually just fine. No updates to the client available atm.

I updated to 3.0. today morning. Since then I've _also_ gotten this error:
Der Prozedureinsprungpunkt "Direct3DCreate9" wurde in der DLL "Guild Wars 2\bin64\CoherentUI64.dll" nicht gefunden.

**Comment by EtzBetz** [comment]
The API got disabled ANet yesterday until some time after the addon release to not spoiler anything.
