### ISSUE TITLE
The window size of the program doesn't work well with windows scaling.

### ISSUE THREAD

**Issue by MagnificentChari** [TheCheatsrichter/Gw2_Launchbuddy#304]
I use 150% scale in windows display settings because I use a laptop which is relatively small but has fullHD display resolution, so without scaling everything looks extremely small. 

However, launchbuddy doesn't work very well with this setting. It was already a bit too big in the older version and it took up all the vertical space of my screen, but it was still usable with all UI elements accessible. Today I updated to 3.0 and the program's window is now apparently even bigger so I can't use the "Launch" button because it goes under my taskbar, and there's no way to resize the window either because I imagine it has a locked minimum size. Could this issue be addressed somehow, if possible? Like, allowing to more freely adjust the size of the window.

**Comment by CraigParton** [comment]
I have this same exact issue. I cannot click the button to start the game. There is plenty of unused vertical space, I just can't resize the window.
