### ISSUE TITLE
LB 3.0 Alpha icon no longer shows on account select screen

### ISSUE THREAD

**Issue by Snaid1** [TheCheatsrichter/Gw2_Launchbuddy#305]
when selecting accounts to launch in the new alpha it no longer shows the account icons next to the names. I use icons to quickly tell which accounts I'm selecting so this slows me down a bit.

OS: Windows 10
LB version: 3.0.0 Alpha

**Comment by TheCheatsrichter** [comment]
Fixed with 1eb1df67af90f61d7434c1d96f9e449e274ab9ce
will be pushed with the next hotfix

**Comment by Snaid1** [comment]
confirmed working in version 3.0.1 Alpha. I'm fine with closing my issue.
