### ISSUE TITLE
Launchbuddy crashes when attempting to launch BlishHUD

### ISSUE THREAD

**Issue by Snaid1** [TheCheatsrichter/Gw2_Launchbuddy#309]
When attempting to launch BlishHUD from Launchbuddy, LB crashes instead.

Steps to reproduce:
- Have BlishHUD path correctly populated
- launch an account
- wait for it to login and get in game
- click the BlishHUD button for that account
- Launchbuddy Crashes! (send crash report)

Details:
- OS: Windows 10
- LB: 3.0.1 Alpha
- BlishHUD: v0.11.6 (works fine when manually launched so I'm inclined to think it isn't this).

**Comment by hildende** [comment]
The same happens with taco as well.

OS: Windows 10
LB: 3.0.1 Alpha

**Comment by TheCheatsrichter** [comment]
Fixed with 3.0.2
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/releases/tag/3.0.2
