### ISSUE TITLE
-maploadinfo option missing

### ISSUE THREAD

**Issue by TheWhiteWolves** [TheCheatsrichter/Gw2_Launchbuddy#31]
After the latest update with the LW3 ep4 patch the -maploadinfo option has disappeared from lauchbuddy. (see below)

![image](https://cloud.githubusercontent.com/assets/1471503/22751080/0e03f9ca-ee2b-11e6-8369-5433cb5bc98a.png)

**Comment by Kaukov** [comment]
Hmm, it seems it's only on your end. Have you tried updating LaunchBuddy?

![see](http://i.imgur.com/NNPyOQP.png)

**Comment by TheWhiteWolves** [comment]
where can i find v1.4, theres only v1.3.1 in the releases

**Comment by Kaukov** [comment]
I download the source and compile it myself. I now see it's not on the releases page ;/ Do you want me to share my compiled version with you ?

**Comment by TheWhiteWolves** [comment]
please if you would, don't think I visual studio installed on this machine

**Comment by Kaukov** [comment]
https://drive.google.com/file/d/0B-sboWi0zT-hNDVCQlVyeEo0ZTg/view?usp=sharing

Here you go :) It's a x64 build but as I saw from your screenshot, you have a 64-bit OS, so it should be ok :)

**Comment by TheWhiteWolves** [comment]
Thanks alot, thats brought the option back, its strange that it just suddenly disappeared after todays gw2 patch, don't think anything changed on my lauchbuddy 😕

**Comment by Kaukov** [comment]
It might be something with the launcher, I don't know. But I'm glad that solved it :) Have fun with the new patch! ^^

**Comment by TheWhiteWolves** [comment]
thanks, you too 😄

**Comment by TheCheatsrichter** [comment]
Be aware that Version 1.4 has many bugs as all new features are in alpha/prototype stage! There is a good reason why I haven't released this version yet!

**Comment by TheWhiteWolves** [comment]
Ye, I expect it prob will lol, if it wasn't for the -maploadinfo option randomly disappearing then I'd prob stay on v1.3.1
