### ISSUE TITLE
Launching GW2 via the Launchbuddy disables addons

### ISSUE THREAD

**Issue by PaterFrog** [TheCheatsrichter/Gw2_Launchbuddy#311]
I installed GW2Radial vie this [Addon Manager](https://github.com/gw2-addon-loader/GW2-Addon-Manager).

If I launch GW2 directly, the addon works as intended.
If I launch via Launchbuddy, it's as if I'd never installed the addon.

I'm unclear on which of the functions of Launchbuddy I should be using for this, and how?

There seems to be an addon manager built in, but it doesn't list any, for example.

**Comment by svavaiesu** [comment]
Same issue for me as well with GW2Radial via Addon Manager
