### ISSUE TITLE
Some non-dark background still existing

### ISSUE THREAD

**Issue by ScrambledBrain** [TheCheatsrichter/Gw2_Launchbuddy#316]
Hi,

there is still non-dark background left at account picker window.

![GW2LB303](https://user-images.githubusercontent.com/76404178/156833553-bcc89c95-9b9b-4667-a7e3-0f10be3baf58.png)

If you select the drop-down of an account, you nearly can't see anything, because it is grey font on light-grey background.

Would be nice, to fix this.

Greetings =)

**Comment by TheCheatsrichter** [comment]
Should be fixed with the next upcoming release

**Comment by ScrambledBrain** [comment]
Thanks, it is fixed =)
