### ISSUE TITLE
Working timings for account mass launch.

### ISSUE THREAD

**Issue by GabrielB-Norway** [TheCheatsrichter/Gw2_Launchbuddy#317]
There are issues when launching multiple accounts at the same time. And you seem to have trouble figuring out what is "too fast" to get rate limited.

Here are my working timings for account launches, if I try to go faster than this I get login errors. 

* Account number 1-12, 1 account can be launched every 10 seconds without issues.
* Account number 13-20, 1 account can be launched every 20 seconds without issues.
* Account number 21-30, 1 account can be launched every 40 seconds without issues.
* Account number 31-35, 1 account can be launched every 60 seconds without issues.
* Account number 36-39, 1 account can be launched every 120 seconds without issues. 

And from what I hear from other people who have a lot of accounts, once you go past 40 it gets even slower than this again and you need upwards of 5 minutes wait time between each account until you're completely halted around account number 45. 

And I'm not trying to be rude here or too demanding, I know this is your free project and I really appreciate the work you're doing here. I've simply noticed that you seem to have trouble figuring out what is too fast so here it is. This is as fast as I can possibly go when manually launching accounts, any faster and I get rate limited at once.

**Comment by TheCheatsrichter** [comment]
First up thanks for the feedback which is always wellcome!

Printed out some delay times which LB currently uses:

Account Number | Delay Time [ms]
1 | 1880
2 | 2120
3 | 2520
4 | 3080
5 | 3800
6 | 4680
7 | 5720
8 | 6920
9 | 8280
10 | 9800
11 | 11480
12 | 13320
13 | 15320
14 | 17480
15 | 19800
16 | 22280
17 | 24920
18 | 27720
19 | 30680
20 | 33800
21 | 37080
22 | 40520
23 | 44120
24 | 47880
25 | 51800

I hoped that these delays which are quiet big already would be enough, however it seems like i have to give it another try .^^
As you already perfectly pointed out this doesn't seem to reflect the delay the gw2 loginserver uses. 

Currently thinking about ways to minimize waittime ... worst case would be a fixed time based on launch attemps (currently uses active accounts).

**Comment by GabrielB-Norway** [comment]
The delays seem to be step-wise. Account number 1-12 seems to be exactly
the same, then 13-20 seem to be exactly the same.

You can actually see the difference on the log in screen, because the time
it takes from when you press "Log in" to when the account is ready to
"Play" changes.

So the way I do my log in's is that i mass launch the first 12 accounts.
And after that I do everything manually.

And the way I do it manually is that I launch the account with Launchbuddy,
Launchbuddy Presses Log In, I wait until the account says "Play", and when
it says play I press to launch the next account. That method usually works
up until the 35th account.

So if it would be possible to:

1. Launch account 1.
2. Launch account 2 when launcher for Account 1 has completed.
3. Launch account 3 when launcher for Account 2 has completed.
3. Launch account 4 when launcher for Account 3 has completed.
4. Launch ... and so on.

That would actually work perfectly up until the 35th account because as
long as you never start a launcher before the previous one has completely
finished it always works. (Up until the 35th!)

**Comment by GabrielB-Norway** [comment]
![image](https://user-images.githubusercontent.com/84335032/157488908-f199e2e5-3784-4dbd-96d5-1a2e98f72537.png)

That's from attempting to launch them as quickly as possible, manually, the 35th account in that screenshot is slightly wrong because I pressed it again by accident. So 5:38 is probably a more correct timing for that one. 

With those timings I got no login errors before the 36th account. But the 36th one required at least a couple of minutes wait.

**Comment by TheCheatsrichter** [comment]
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/commit/003f4bd7e415bf7d3b7c1ab1a80f017487a44508

This now works as following:

LB determines how many of all accounts have been launched in the past 30 mins ( limit atm is 30 mins might need to increase this if problem occur ). This number is used to determine how long the delay should be. This is refered to recent_logins.

Delays with a number of recent logins < 12 will use the old method.
Every other login past 12 will use the delays which [GabrielB-Norway](https://github.com/GabrielB-Norway) has posted here.

This solution has however one problem: if a user launches the same account over and over again ( I currently don't see a usecase for that), logincount won't match the number LB determines for the delays. Gonna keep an eye on that.


Will be pushed with the next release

**Comment by GabrielB-Norway** [comment]
Tested with 39 accounts, took about 25 minutes to launch all with no errors and you could actually see that the log in servers were visibly happy with the change because the time it took from pressing Log-In until the account was in Ready state was relatively short. 

That said the timers don't seem to start immediately which throws the timing off by a bit. 

So I think some optimizations could be done for accounts number 21-30 (40 -> 32 i think would work well) and 31-35 (60 -> 48) as well as 36-40 (120->90) and that would reduce the time to maybe 21-22 minutes which would be very close to the actual optimal speed. 

But that would be nitpicking really, because it works 100% perfectly now, I can press mass launch for 39 accounts like this and not have a single issue and that's awesome. 

Thanks a lot! :)

**Comment by maconho** [comment]
Hey guys! First of all I want to congratulate the excellent work done with this troubleshoot and solution for the time cap on account logins. I really appreciate the effort with this amazing tool that become better each update.

I wanna ask if it's possible to add an option to disable this new delay on the options (I tried to find some option for this, but can't find). It's nice to keep the delay between the accounts as default for Launchbuddy, but it's possible to avoid this time cap problem using connection proxy softwares. So it would be nice an option where we don't need to wait 20 or 40 seconds between each account.

In my personal case, I have 35 accounts and log-in they in 10/10/10/5 shares, with a different proxy connection for each share and don't need to wait this delay because GW2 server understand it as 4 internet connections logging the game. Without the delay present in the current build I was abble to log-in all the accounts, enter the game, collect the daily reward and close all in less than 15 minutes. With the current build the time necessary rises to 40+ minutes. So it would be nice if an option to disable the delay be implemented on a future update.

Keep the excelente work and thanks a lot for all done until now.
Best regards.

**Comment by GabrielB-Norway** [comment]
> In my personal case, I have 35 accounts and log-in they in 10/10/10/5 shares, with a different proxy connection for each share and don't need to wait this delay because GW2 server understand it as 4 internet connections logging the game. Without the delay present in the current build I was abble to log-in all the accounts, enter the game, collect the daily reward and close all in less than 15 minutes. With the current build the time necessary rises to 40+ minutes. So it would be nice if an option to disable the delay be implemented on a future update.


I don't want to claim this isn't an issue because I could understand it would be annoying. But with the current delays it takes me 19 minutes to get to 35 accounts without any VPN. I don't understand why yours suddenly goes to 40 minutes while mine is 19 minutes and done. (19 minutes for 35 and 25 minutes for 39 for me)

**Comment by ScrambledBrain** [comment]
Whatever the reason is for him, it is everytime a good idea to give the people an option to choose a setting or not.
So, these delaying setting should also be an option in GW2LB ;D

**Comment by GabrielB-Norway** [comment]
> Whatever the reason is for him, it is everytime a good idea to give the people an option to choose a setting or not. So, these delaying setting should also be an option in GW2LB ;D

I agree, personally what I would love to see is customizable settings.  Because I think the optimal settings will be different for everyone depending on whether you have a fast or slow PC for instance. As well as depending on whether you use VPN. And who knows what delays are needed when you got 40-50 accounts?

**Comment by GabrielB-Norway** [comment]
I see, I launch all accounts at the same time and then close them down once
I'm done with them. I also log in using "Windowed mode", lowest resolution
and lowest possible graphics settings for all my accounts (you can set
separate for each account).

So that way I never have more than 4 open at a time, but I basically always
have 1 account I'm playing, 1 in character screen, 1 being launched. So I
only ever have 3-4 accounts open at a time but I'm always launching new and
closing the ones I'm done with.

**Comment by Snaid1** [comment]
is it possible we could get a way to self configure the wait times? that way more people could experiment with setting up the optimal wait times for their setup.

**Comment by canyud** [comment]
please add option to turn off this feature

**Comment by canyud** [comment]
> > please add option to turn off this feature
> 
> Try this solution:
> 
> > Than I noticed that I can just hit cancel on the delay window in Launchbuddy and don't need to wait the delay between accounts. Doing this way I could log 35 accounts arround 17 minutes. This solve the problem for me, but still be great to have an option on configurations to skip the delay.

i still hate the pop up tho, btw do you have a solution or tricks to bypass login limit ? idk why my gw2 have this thing lol
it always says " The game client is unable to gain access to the log-in server at this time. This is most commonly caused by a firewall or router settings, security applications, or connecting through a campus network. For additional support, please visit [http://support.guildwars2.com](https://support.guildwars2.com/) " according to wiki its because too many login attempts and the limit is IP based

**Comment by GabrielB-Norway** [comment]
Yeah, I don't get why you need the pop up. If you want to bypass it you can
also just press Log In. And the delays were already there, the only
difference is that the timings are set so that they actually work now.

**Comment by Alimar777** [comment]
Is there a way to disable this feature? I was looking around in settings to disable the delay but no luck.

Additionally it seems you can bypass this DDOS protection if you have a VPN or the ability to change IP's. Obviously this means 2FA issues if you haven't set it to remember. 

If there's a way to rotate through different available IP's or login servers we might be able to reduce time between launches?

**Comment by TimothyLewisUTD** [comment]
Can we please get a custom setting for this, and rather soon? I am literally begging you.

I am not even sure you can figure out a 1 size fits all solution. With the current settings, I have now had my accounts locked 3 times. Each time requires me to contact support to unlock them, and it is just driving me insane. This last time they required that I reset my 2FA on ALL of my accounts. And I wanted to kill myself.

I don't care if I manually set them to 3 minutes between each. I will do it on a laptop or walk away for a an hour or so. But the way I am having to solve it now is just terrible. I run a manual timer in the background and just manually choose each account every 2-3 minutes.

I have 40 accounts.

**Comment by kililua** [comment]
Can we have an option to turn off this thing and the pop up please?? its kinda annoying since i always got undefined error every 10-15 accounts

**Comment by canyud** [comment]
> I have 35 accounts and log-in they in 10/10/10/5 shares, with a different proxy connection for each share and don't need to wait this delay because GW2 server understand it as 4 internet connections logging the game. Without the delay present in the current build I was abble to log-in all the accounts, enter the game, collect the daily reward and close all in less than 15 minutes

Hi! Is that means you are bypassing the DDOS protection? If so, can i have any tutorial for it?

**Comment by GabrielB-Norway** [comment]
Bypassing DDOS requires having VPN and changing IP address, new IP = new
DDOS limit. If I was to do this I would do batches of 12 accounts. So set
IP to Sweden, log in 12 accounts, set IP to to France, Log in 12 accounts,
set IP to UK, log in 12 accounts.

Every time you switch IP the time resets to your normal 1-12 time. The only
challenge is that a new IP might require SMS verification every single time
you change it. So you want to do it the same way every day, so number 1-12
from Sweden, 13-24 from France, 25-36 from UK.

**Comment by Aussiemon** [comment]
39th account hits a login server unavailable error. The timing might need some adjustment for large numbers of accounts.

I've also noticed that restarting the computer or launchbuddy crashing resets the delay timer, which means all your accounts have to be manually delayed. It'd be helpful to have some way to set a baseline delay for the session.

**Comment by Aussiemon** [comment]
Wait a second, the 42nd and onward accounts dropped from 120 seconds delay to 60 seconds delay. There might be a calculation bug here.

**Comment by murthagg** [comment]
Is it normal that even with this wait time there is still an increasing delay after login gets pressed. Where the circle next to the login button keeps spinning?

**Comment by GabrielB-Norway** [comment]
Being able to set up personal wait times would be the optimal solution.
Because the way it works right now wait times start after client is
launched, I'm confident the wait times are quite close to optimal for me
(who has a very fast PC), but if you're running GW2 on a HDD instead of SSD
or if you have a slower system they would be way off.

The same goes if someone uses VPN for their launches, if someone is using
VPN then the optimal time might be to repeat the 1-12 times several times
over.

**Comment by ManniMan** [comment]
Hi,
I have 40 accounts and log in a 24 and 16 split (or 20/20). The second split I do after 6h of the last login of the first split.
The DDoS Protection of GW2 resets after 6h. If I try to log in with the second split after 5,5h I still get the delay in the login screen for the second account (the first goes in without delay) of the second split. 
After 6h I can login with the normal standard delays second split (so the delays have been reset.
I mainly do the splits because I don´t want to wait for 40 or 60 seconds at the end for each account and it is not bothering me to do split the daily logins.
