### ISSUE TITLE
Launching without ArcDPS?

### ISSUE THREAD

**Issue by Drogon1234** [TheCheatsrichter/Gw2_Launchbuddy#323]
Hi,

I use ArcDPS when I launch the game without Launchbuddy, but when I launch via LB it also starts Arc even though I HAVE NOT set up LB to use Arc. I think it does it only on the first account I launch via LB, but I am not 100% sure.

Can someone tell me how to launch via LB without also starting Arc?

The reason I am asking is because when LB launches Arc, my multibox experience is terrible and at least 1 account will freeze in the background. When I delete Arc and use LB, I can run 4 accounts without ever running into issues, but when I have Arc on I can run max 3 accounts and at least 1 will always freeze in the background.

My boyfriend has the same issue.

Any help is appreciated.

**Comment by dylloop** [comment]
Im having the opposite issue. I want arc to launch with LB but it only seems to sometimes launch. and if I put it in injected software the game fails to launch at all.

**Comment by labaland** [comment]
Same issue here.. if i launch more than 2 accs the rest freeze and goes white.
