### ISSUE TITLE
Autoclicker macro not working when using launchbuddy

### ISSUE THREAD

**Issue by zman112** [TheCheatsrichter/Gw2_Launchbuddy#324]
Mouse software is Logitech G Hub.
Macro: click down, 50ms delay, click up, 50ms delay... repeat on button hold down

This has been working find for years.... but stopped working recently.

So now:
It works when I just run gw2.exe by itself
It does NOT work when I start gw2 via Launchbuddy

Other things I've tried to see if there's a pattern:
Macros with other keys work fine, example:
1, 50ms delay, 1, 50ms delay... repeat on button hold down (this spams auto attack while I hold down button)

Other keys work, it seems like the clicking action is the only thing not working.

I have tried testing the autoclick macro on a browser, it does work.

Any clues?

Thank you

**Comment by suialthor** [comment]
Same problem with my Logitech macro as well as any macro I try while using Stream Deck.  They both work without Launchbuddy but not with it.
