### ISSUE TITLE
the game instances overlay don't work in game.

### ISSUE THREAD

**Issue by nouche0** [TheCheatsrichter/Gw2_Launchbuddy#327]

**Comment by nouche0** [comment]
Hi ,
The overlay "game instances" is working on windows but not in game.

**Comment by TheCheatsrichter** [comment]
Is the game set to windowmode?

**Comment by nouche0** [comment]
oh that is why , nope i was in full mode. thanks !
________________________________
De : TheCheatsrichter ***@***.***>
Envoyé : vendredi 1 avril 2022 14:08
À : TheCheatsrichter/Gw2_Launchbuddy ***@***.***>
Cc : nouche0 ***@***.***>; Author ***@***.***>
Objet : Re: [TheCheatsrichter/Gw2_Launchbuddy] the game instances overlay don't work in game. (Issue #327)


Is the game set to windowmode?
