### ISSUE TITLE
Errorcode: 8 on multiple accounts launch

### ISSUE THREAD

**Issue by AnnieAcrux** [TheCheatsrichter/Gw2_Launchbuddy#328]
Since I updated launchbuddy to the lastes ver. I keep getting error code:8 and cannot launch more than an account at a time. If I select more than one, the first and second (max) will launch and everything else says the client crashed (error code:8) 
welp!

**Comment by ludwigma** [comment]
same here, sometimes 2 acc sometimes 3 acc sometimes 1 acc

**Comment by Erikdc666** [comment]
I came here to report the same issue, but for me it was the 12th account today...
But no matter which one it is, a retry always fails, and all current selected account afterwards fail as well

Even when all have failed, I can't launch any more, I closed all except one and then I was able to launch more again, so it feels like it is one specific running account that is blocking the rest from launching, I would guess the one right before, but I'd have to test that out next time I get the issue

![image](https://user-images.githubusercontent.com/52191397/162024513-7f4a52c2-3824-494b-9d20-0b6c59794f31.png)

**Comment by awesmdiver** [comment]
I now, out of the blue, am starting to see the same behavior.  When it happens, I can reboot my system and LaunchBuddy will work fine again and as long as I keep LaunchBuddy up and running and I can use it properly.  However, once I close the app and restart it, the issue returns, and a reboot fixes it.

Sounds like a file lock issue maybe.

**Comment by TheCheatsrichter** [comment]
Seems like the LocaldatManager can not switch back to the default loginfile. Gonna investigate if GW2 somehow extends the filelock on multiple logins.

**Comment by awesmdiver** [comment]
@TheCheatsrichter  thanks for looking into this.  Happy to help test if needed.

**Comment by Erikdc666** [comment]
Weird enough, the issue hasn't reoccurred for me anymore for almost 2 weeks now of almost daily launching my accounts.
once or twice I even launched 24 at the same time without issue (except my pc almost dying in the process)

I'm not saying you shouldn't investigate it anymore, but just that it isn't always consistent or easy to reproduce apparently...

**Comment by Erikdc666** [comment]
> @Erikdc666 can you launch a bunch of clients, close them all, close LaunchBuddy, restart it and launch multiple clients with no issues?

I just launched 8, logged them in, got my daily reward, closed them all, restarted launchbuddy and launched the same 8 without problem.
After that I launched 2 more batches of 8 without restarting again, still no issues...

I could try with more than 8 if you want, but that's gonna drive up the login delay timer ;)

**Comment by awesmdiver** [comment]
> > @Erikdc666 can you launch a bunch of clients, close them all, close LaunchBuddy, restart it and launch multiple clients with no issues?
> 
> I just launched 8, logged them in, got my daily reward, closed them all, restarted launchbuddy and launched the same 8 without problem. After that I launched 2 more batches of 8 without restarting again, still no issues...
> 
> I could try with more than 8 if you want, but that's gonna drive up the login delay timer ;)

Glad to know it's working for you.  I didn't have the problem right away after installing last update, but currently still have it.  Only resolves for me if I reboot my system if I close LaunchBuddy and reopen it.

**Comment by AnnieAcrux** [comment]
> Seems like the LocaldatManager can not switch back to the default loginfile. Gonna investigate if GW2 somehow extends the filelock on multiple logins.

thank you for looking into this I really appreciate it:)

**Comment by AnnieAcrux** [comment]
as for myself, I still have the same issue unfortunately. rebooting my pc doesn't work for me ;_; still can't launch more than one account, no matter the order I try/which one it is

**Comment by Chiesa5o** [comment]
Any progress on this?

**Comment by Valakivi** [comment]
> Any progress on this? I can't launch more than one account quite consistently now.

please help! :D

**Comment by Kevin-Thai** [comment]
This is still an issue for me on 3.0.6. At this point, it never launches more than 1 account.

**Comment by TheCheatsrichter** [comment]
2fad5247d19fcfd194437a7db321f75d65e08872
3d26c9f6c620bbdbe9a25f94d5212f5e3108378f

Some fixes coming with version 3.1.
Description:
Fixed a crash when an account without loginfile was launched. These accounts had a bug blocking all accounts after them from launching. => errorcode 8
