### ISSUE TITLE
Question: Skip nasty 2FA SMS reminder

### ISSUE THREAD

**Issue by ScrambledBrain** [TheCheatsrichter/Gw2_Launchbuddy#331]
Hi,
would it be possible to skip the nasty 2FA SMS reminder after login?
This would be really helpful.

This would maybe need some effort because of the different languages, if you try to skip this with some OCR or something like that, but maybe there is a more efficient way to skip this.

Any ideas are appreciated.

I don't know, if this is needed to implement in GW2LB or if there are any other possibilities.

**Comment by CurtisJohnston** [comment]
Agreed that Launch Buddy needs to skip it automatically.

That being said, GW2 allows you to use the same phone number for SMS of every alt account. So it's not difficult to add your phone number to every single alt. I did it in about 1 minute per account.

**Comment by murthagg** [comment]
Is it normal that even with this wait time there is still an increasing delay after login gets pressed. Where the circle next to the login button keeps spinning?
