### ISSUE TITLE
No auto-play for NA servers form EU

### ISSUE THREAD

**Issue by vanko11595** [TheCheatsrichter/Gw2_Launchbuddy#336]
I cant auto start the game if I use NA server from EU. The program stuck after login at PLAY button and have to manually press play to start the game.
I dont have this problem if i log into EU servers.

**Comment by kdog1964** [comment]
Confirming that this problem exists for EU servers logging in from NA and, also, not for NA servers logging in from NA.

**Comment by kdog1964** [comment]
Ok, made this work ok. Not sure why but autoplay was unchecked on only the EU servers for me. Redid the logfile for each, made sure to check autoplay and now all is good. Still can't explain why autoplay got unchecked only for these servers. I have 20 accounts and it only happened on EU servers. Once again, I'm in NA.
