### ISSUE TITLE
Inconsistency in Advanced Settings - Configure Windowsettings

### ISSUE THREAD

**Issue by accelleratii** [TheCheatsrichter/Gw2_Launchbuddy#338]
My PC is capable of running several accounts at one time. I chose to launch 9 at once and created a 3x3 grid of windows at 2560x1440 desktop resolution. 

Arranged the windows for all accounts using Configure Windowsettings in Advanced Settings: every 10th account window overlaps the 1st one, etc... 

Problem is that while predefined locations of windows are consistent, the size of some windows (randomly) scales up to 2069x1208.

![Screenshot 2022-05-12 220625](https://user-images.githubusercontent.com/15660299/168143103-23eb75df-5134-497d-bc92-4de6b7cbc131.png)

Is this inconstancy a know issue? Are there any other options to sort the windows, and let the settings remember the last position?

**Comment by accelleratii** [comment]
FansyZones don't seem to work with gw2 windows

**Comment by 1Nor1** [comment]
Yes same issue with me havent found a workaround but its not to hard to arrange all the windows...
