### ISSUE TITLE
download location of updates

### ISSUE THREAD

**Issue by TheWhiteWolves** [TheCheatsrichter/Gw2_Launchbuddy#34]
Any chance you can change the download location for updates to the working directory instead of the GW2 install directory.

Personally I store Launch Buddy is a completely different place to guild wars and have to move the file every time it updates.

**Comment by TheCheatsrichter** [comment]
To be honest the version updater/switcher was rushed as I wanted to release 1.4 before I have far less time again. But its on my todolist!

**Comment by KairuByte** [comment]
I have altered the LB update process to backup the current LB (appends .bak) and replace it with the updated version. This should remove the problem of downloading into the wrong place, but depending on the security of the folder where LB is placed there may be some problems with this process. If this happens I'll have to force the update process to request elevated permissions.

This should be in the next LB release.

**Comment by KairuByte** [comment]
This exists in the refactor branch, and needs testing. If you are not familiar with how to build the application, it will likely be included in the next alpha/beta release.

**Comment by KairuByte** [comment]
Closing as complete in 1.7
