### ISSUE TITLE
GW2 error if started with LB...

### ISSUE THREAD

**Issue by ASRSI** [TheCheatsrichter/Gw2_Launchbuddy#341]
In the past everything worked just fine. But now...

If I start a single account (not multi!), I get the GW2 message: "Guild Wars 2 needs to be patched befor using -shareArchive, -noPatch, or -multi.

Any idea what to do?

Thank you.

**Comment by Fribb** [comment]
I just ran into this problem as well with the Wintersday Patch just being released and a simple restart of Launchbuddy fixed the issue for me.
