### ISSUE TITLE
Login Server - Delay Timer - Firewall 

### ISSUE THREAD

**Issue by optkz** [TheCheatsrichter/Gw2_Launchbuddy#346]
Hey, first of all thanks for your Work, i really enjoy the advantages of your Launcher.

Now to the Problem:
After several Logins on my Alt Accounts, around the 30ish Account i get this Message:

"The game client is unable to gain access to the log-in server at this time. This is most commonly caused by firewall or router settings, security applications, or connecting through a campus network. For additional support, please visit http://support.guildwars2.com/.
Build: 130287
Error Code: 42:0:9001:4457"

So the DDos Delay Timer isnt set up properly because im getting this Issue everday . Whats worse is that when it was once triggered i need to wait around 5-10 Minutes for every next Account i want to login.

Switching the Login Server via the Network Settings or the Port which is used wont make any difference at all. Or am i doing it wrong?

Is there any Workaround / fix for it?

**Comment by CerberusKCO** [comment]
in my case, after login my first 25 alts, i reset my router so that i have a different IP address and afterward the DDos delay is removed as i'm on a new IP;
couldn't find a better solution cause to reset the router daily is a pain, in case you have a better idea would be great to share

**Comment by optkz** [comment]
Im using a free VPN (Proton VPN) now to bypass the Firewall Issue, Proton VPN allows you to choose a Free Server which seem to have a static IP, so you just have to do the 2 Factor Authentication once, just make sure youre on the same Free Server when launching the next day.
