### ISSUE TITLE
Gameclient Login - Loginbutton could not be pressed

### ISSUE THREAD

**Issue by Guillejin** [TheCheatsrichter/Gw2_Launchbuddy#347]
When I try to start 2 accounts I start 1 and the other I get this error shown in the image.

![9mc8HlZ](https://user-images.githubusercontent.com/102975157/173974403-a5bfa607-da78-4596-b229-8b635dee6d96.png)

**Comment by TheCheatsrichter** [comment]
` if (Account.Settings.Loginfile != null)
                            {
                                if(LBConfiguration.Config.pushgameclientbuttons) PressLoginButton();
                                LocalDatManager.ToDefault(account.Settings.Loginfile);
                            }
                            Status = ClientStatus.Login;`

LB seems to have some trouble finding the LOGIN button of the gameclient. Might be linked to the gw2 loginwindow updates in the past weeks.

**Comment by TheCheatsrichter** [comment]
Pushed the 3.0.5 release. Please report if the issue has been resolved
