### ISSUE TITLE
graphic settings problem with LB profile and non LB profile

### ISSUE THREAD

**Issue by Vipanez** [TheCheatsrichter/Gw2_Launchbuddy#348]
after logging in my accounts that all have low graphic settings for more performance, my main aacount starts with low graphic settings too. I dont have created a profil in LB with my main account. how can I prevent my main account not starting with the settings like my LB accounts?

sry for the english, its not my native language
thx for any help

**Comment by TheCheatsrichter** [comment]
Seems to be a bug which does not switch back the latest GFX settings file on the last used account.
I'll test this. :)
