### ISSUE TITLE
LB skip the login for some account (1/5 of all my account aprox) 

### ISSUE THREAD

**Issue by Ryu-Pendragon** [TheCheatsrichter/Gw2_Launchbuddy#349]
hello there i log in 50 account every day but i dont know why Lb open all the luncher but he skip some login action and just go on the other account and this is completly random but hapen at a ratio of like 15% 20 % of the time.. i have to wach it all the time and manaly presss the connect buton when that happen or completly delay the connection of this account to the end to not trigger the DDOS protection

im on windows 11

**Comment by TheCheatsrichter** [comment]
Probably the same issue as here. Timing errors as LB waits for a .dll file that no longer gets loaded by the Gw2 Gameclient.
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/356

Keeping this issue open as it might needs an additional fix.

**Comment by TheCheatsrichter** [comment]
Pushed the 3.0.5 release. Please report if the issue has been resolved
