### ISSUE TITLE
Auto-Update Login Files - Error

### ISSUE THREAD

**Issue by optkz** [TheCheatsrichter/Gw2_Launchbuddy#350]
So after the recent Updates to GW2 i launched Launchbuddy after i downloaded the recent patch on my Main Acc. Launchbuddy started to update all the Login-Files automatically, however, as soon as i try to login on the Accounts Launchbuddy tries to download something through the gw2 Launcher again and gets stuck in an Error Message which is telling me "Download failed, please check your Internet Connection and try again". I can fix this by manually updating all login files one by one again. Do i need to Backup my Login files for the Autoupdate to work properly? Is there a way to force Launchbuddy to update all Loginfiles instead of doing it manually one by one?

Its the third time that i have to update all the login files manually one by one again.

**Comment by Olian04** [comment]
I have the same issue. I'm using version 3.0.4

**Comment by Tisuchan** [comment]
Same issue here on 3.0.5 - With every gw2 update I have to re enter all the infos for all Accounts otherwise I get a network connection error.
