### ISSUE TITLE
Account launched with LB has (considerably) longer loading times than when launched normally

### ISSUE THREAD

**Issue by GBLikan** [TheCheatsrichter/Gw2_Launchbuddy#352]
Hey ! Thanks a lot for LB, which I have been enjoying for quite a while now !

Lately on my laptop (4800HS 1660Ti Max Q) I've been noticing a weird behavior : launching a given account with LB will result in significantly longer loading times (up to four times longer) than launching the same account normally, despite both login methods having the very same parameters.

I've done a fresh GW2 install, and a fresh LB install. In LB I registered the account directly from the initial local.dat parameters, no arguments, no addons or injection of any kind.

And yet, I've timed loading into New Kaineng at ~13s while logged in the "normal" way, and at ~40s with LB.

Has anyone experienced the same thing perchance ?

**Comment by Valakivi** [comment]
all is fine here

**Comment by GBLikan** [comment]
Found the culprit ! For some reason, the "Active Protection" feature of Acronis True Image software (in its 2020 version at least) interferes with the mutex handling of LB, resulting in the observed reduced performance. Once disabled, problem goes away.
