### ISSUE TITLE
Selecting accounts invisible when window is active

### ISSUE THREAD

**Issue by Dasher125** [TheCheatsrichter/Gw2_Launchbuddy#355]
Actively selecting the launchbuddy window makes the account selection boxes invisible. Clicking off to desktop makes them visible.

Window active:
![image](https://user-images.githubusercontent.com/37772722/182347205-e04275d8-8ec6-4cc9-a5e2-32caaf2b9bd2.png)

Window inactive:
![image](https://user-images.githubusercontent.com/37772722/182347068-cf5da0d7-0710-4e4d-ab7f-b0e7e2dc742f.png)

**Comment by TheCheatsrichter** [comment]
ToDo: Changing listview ItemHighlight color.
Should be fixed with the next release
