### ISSUE TITLE
Auto Login Not Working Properly

### ISSUE THREAD

**Issue by Alimar777** [TheCheatsrichter/Gw2_Launchbuddy#356]
First thanks for all your hard work!

I lack proper knowledge of how the game client works but it seems something with a recent update causes launch buddy to hang when trying to launch the game. It easily takes upwards of a minute to fully load into character select even after "cancel" is clicked on the wait timer.

I backed up to v3.0.3 and I still had the issue.

If anyone else is experiencing this I'd love to hear any solutions.

**Comment by 4enforced** [comment]
Same here.

**Comment by sveeke** [comment]
Same here. Since this morning, logging in takes ages. Looks like gw2launchbuddy can't properly interact with the buttons of the most recent version of the launcher maybe?

**Comment by DarkSquad** [comment]
Same here hope they push some update with fix soon

**Comment by Alimar777** [comment]
> Same here. Since this morning, logging in takes ages. Looks like gw2launchbuddy can't properly interact with the buttons of the most recent version of the launcher maybe?

I've noticed LaunchBuddy gets a "Not Responding" tag on the window when you hit cancel or the timer goes out and then it's about 1 min before process resumes and the sign in attempt happens. So there's something in the interim causing issues.

**Comment by Aussiemon** [comment]
If you're having the same problem I was having, it's because [this module](https://github.com/TheCheatsrichter/Gw2_Launchbuddy/blob/master/Gw2%20Launchbuddy/Modifiers/Loginfiller.cs#L24) isn't found in the GW2 process anymore. That means that the login filler waits for the entire timeout instead of loading immediately.

I'm not sure this applies to everyone, but changing the value to "NSI.dll" fixed the issue for me.

**Comment by blashmer** [comment]
> If you're having the same problem I was having, it's because [this module](https://github.com/TheCheatsrichter/Gw2_Launchbuddy/blob/master/Gw2%20Launchbuddy/Modifiers/Loginfiller.cs#L24) isn't found in the GW2 process anymore. That means that the login filler waits for the entire timeout instead of loading immediately.
> 
> I'm not sure this applies to everyone, but changing the value to "NSI.dll" fixed the issue for me. This fix doesn't work for updating the local.dat files though.

gj on finding this!
Are you able to send us a compiled version with this change, please ?

**Comment by Aussiemon** [comment]
> > If you're having the same problem I was having, it's because [this module](https://github.com/TheCheatsrichter/Gw2_Launchbuddy/blob/master/Gw2%20Launchbuddy/Modifiers/Loginfiller.cs#L24) isn't found in the GW2 process anymore. That means that the login filler waits for the entire timeout instead of loading immediately.
> > I'm not sure this applies to everyone, but changing the value to "NSI.dll" fixed the issue for me. This fix doesn't work for updating the local.dat files though.
> 
> gj on finding this! Are you able to send us a compiled version with this change, please ?

This isn't really the right place to share unofficial binaries, and I'm not sure my fix is better than just commenting out the line or would work for other people. It's probably best to wait for @TheCheatsrichter's official fix.

**Comment by DarkSquad** [comment]
when can we expect any hot fix patch to this ?

**Comment by Snaid1** [comment]
having this same issue. updates went from 20minutes to over an hour after the Aug 2 update...

**Comment by Zaerienne** [comment]
Would be lovely if this was fixed. But has Launchbuddy been abandoned? Kinda seems like it, no updates since end of March.

**Comment by WolfSabian** [comment]
Hoping for a fix soon.  For me it's the issue of it being crazy slow. [mentioned here](https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/357)

It takes forever to log into my accounts.  Literally went from about 10-15 mins to well over 30mins if things are fast.

**Comment by Alimar777** [comment]
> 

How did you edit the file target? I'm unfamiliar with editing the program.

**Comment by TheCheatsrichter** [comment]
I'm now back from vacation. :) Gonna have a look at this issue asap!

**Comment by Alimar777** [comment]
> I'm now back from vacation. :) Gonna have a look at this issue asap!

Thanks for the response and hope your vacation went well!

**Comment by TheCheatsrichter** [comment]
Pushed the 3.0.5 release. Please report if the issue has been resolved

**Comment by blashmer** [comment]
It works really well. 
With @Aussiemon fixes it's even better.
Good job !

I just wish we could have a button to reset timers as i'm using multiples IP to login in all my accounts.
I have to push the time on my PC to get the 0 to 30 accounts timers again.

**Comment by sveeke** [comment]
Login in works for me again. Thanks for the patch! Have not tried plugins yet (to confirm the report of @blashmer ).

**Comment by Farsc** [comment]
I'm still having the same issue on 3.0.5 email is not being filled in or the password is wrong, I have created all 5 accounts new and still, nothing fails 90% of the time.
