### ISSUE TITLE
V3.0.5 - Antivirus false Positives

### ISSUE THREAD

**Issue by TimSando** [TheCheatsrichter/Gw2_Launchbuddy#361]
The most recent version is being picked up as containing a Trojan virus by Windows Defender (Trojan:Win32/Wacatac.B!ml). 
![image](https://user-images.githubusercontent.com/58012811/185250680-6258c415-1f8e-466b-8d0b-8a9165b1b72a.png)

**Comment by accelleratii** [comment]
Got quarantined with Trojan:Win32/Wacatac.B!ml

**Comment by KOVIKO** [comment]
The [diff](https://github.com/TheCheatsrichter/Gw2_Launchbuddy/compare/3.0.4...3.0.5) shows changes in which DLLs are being used... could one of them be the issue?

**Comment by AnnieAcrux** [comment]
same, got 2 alerts saying this contains a virus :/

**Comment by Silitha** [comment]
My update also contained the same virus. Glad Defender caught it right away.

**Comment by Mythykle-Mythryndyr-Fs** [comment]
yeah same here. :(

![Screenshot 2022-08-18 132700](https://user-images.githubusercontent.com/48535309/185287046-45f40bbd-2870-472c-a40a-f97166b441c1.png)

**Comment by AdjutantAvocado** [comment]
[Here's](https://www.virustotal.com/gui/file/65c81764d6d8bb0d211a47ca191e1e5f0508d17809b31191fa62f44da8458ee5/detection) is the VirusTotal results for this file.

**Comment by Dalennau** [comment]
Tried to update the program from the popup upon launching it, and it looks like it just disappeared from my desktop. I have an older version that I can open, but it won't load the list of updates to do it manually. I'm assuming this is due to the apparent virus Windows is identifying.

**Comment by Alimar777** [comment]
Same issue here.

**Comment by Morozzko** [comment]
https://www.virustotal.com/gui/file/65c81764d6d8bb0d211a47ca191e1e5f0508d17809b31191fa62f44da8458ee5

**Comment by TheCheatsrichter** [comment]
Seems to be the same problem as in all previous Versions. These antivirus flags are sadly false positives which only can be resolved by a manual .exe review from microsoft. Therefore I had to submit the file to them, which sadly takes a while....

So either please be patient or wait a little until the review is approved by microsoft.

**Comment by optkz** [comment]
Got the same Issue, was smoking a Cigarette during my Logins, came back and Launchbuddy was just gone, i thought im crazy lol. Hopefully i dont have to set all the Account Logs again..

**Comment by TheCheatsrichter** [comment]
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/363
For further information.
Keeping this issue open to collect feedback if the issue got resolved for version 3.0.5

**Comment by TheCheatsrichter** [comment]
UPDATE:
Launchbuddy V3.0.5 now as been approved and reviewed by microsoft. The virus flag has been lifted and downloading / using LB should not work without issues. Please report back if any other AV scanners still have issues.
Virustotal results now also got updated:
https://www.virustotal.com/gui/file/65c81764d6d8bb0d211a47ca191e1e5f0508d17809b31191fa62f44da8458ee5?nocache=1
