### ISSUE TITLE
Windowed Mode Defaults to Full-screen Resolution

### ISSUE THREAD

**Issue by AEsylum** [TheCheatsrichter/Gw2_Launchbuddy#362]
Resolution for Windowed mode is automatically scaled up to the full screen causing the Title Bar at the top of the client when in windowed mode to be hidden, making it impossible to move the client window or resize it unless i drag another app to the sides of the screen and then click to select the GW2 client again to force it to resize to occupy the other half of the screen. This started from version 3.0.4 and isn't resolved in 3.0.5

**Comment by TheNasbit** [comment]
Workaround (still not optimal): Win+LeftArrow or Win+RightArrow
The shortcut will quickly snap a window to the screen borders.

**Comment by AEsylum** [comment]
> 

This works! Thank you so much!
