### ISSUE TITLE
Megathread - Antivirus False Positives

### ISSUE THREAD

**Issue by TheCheatsrichter** [TheCheatsrichter/Gw2_Launchbuddy#363]
Merging all existing Antivirus false positives issues into this one to get a better discussion going.
To provide feedback regarding the newest version please use the issue with the correct versiontag.
This issue is reserved for general problem discussion on how to tackle the false positives.
Newest Version 3.0.5 issue:  https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/361

Description:
Each time Launchbuddy releases a new version false positives in some antivirus softwares get triggered. Main issue here is Windows Defender as it deletes the executeable instantly, which confuses and angers users.
Issue currently has been manually resolved each time by submitting the executebale to microsoft for an additional review. This however introduces a delay (1 week).

Possible Solutions:
1) Analysing which Launchbuddy components trigger the false Positives + Code rework:
Really hard to pull of as Antivirus programs seem to delay some flags to prevent programmers adapting code to go under the radar.
Therefore a codeoverhaul or even a deactivation of some features ( likely DLL injection and client altering features) would have to be made. However results would still be based on wild guesses on which parts trigger them.

2) Signing the application with a certificate:
Signing Launchbuddy with an certificate or even an EV certificate would boost the reputation score of Launchbuddy in Windows Defender and might even get rid of the SmartScreen on startup. Main problem here is the cost of these certificates as a base certificate starts at around 150$/year and an EV certificate at 250$/year. In the current state donations and financial community support is not enough to cover these costs.

 Normal Certificate : Reputation will have to be build up asap people use signed software. --> ~ 2000 downloads to become a "trusted" publisher
EV Certificate: Instant Reputation. Certificate  costs more and is only handed out to businesses.

3) Submitting each Launchbuddy release to AVs for further analysis:
The current way of solving the issues as it is free. However with some big drawbacks:
- Code review takes some time, in the meantime users get confused and even concerned about Launchbuddy not beeing save. Reputation damage in the community is big and not to be underestimated.
- Each new releases needs to be submitted to all the AVs, big chunk of paper work, every single time....
- The releases only get flagged as viruses when multiple users try to use it. --> I can not submit the new versions beforehand and wait for approval as the executeable is not yet flagged as a virus.
-  Reputation buildup for Windows Defender of an unsigned application is reallyyyyy slow. Takes about 4 weeks to be consired "known software" and not get flagged as "potentialy unwanted software"

If you guys have any additional solutions or ideas please let me know!

**Comment by accelleratii** [comment]
Is Wacatac.B!ml identified falsely? Or is this a randomly assigned malware by "some antivirus softwares" that trigger a false positive, in other words, would that "blame" a different malware next time?

**Comment by TheCheatsrichter** [comment]
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Virus:Win32/Wacatac.B!ml&ThreatID=2147774417

States : "This [virus](http://www.microsoft.com/security/portal/mmpc/shared/glossary.aspx#virus) spreads by attaching its code to other files on your PC or network. Some of the infected programs might no longer run correctly."

Which sound very familiar to the dll injection feature of Launchbuddy. So a "false positive" in this regard isn't quite right. Launchbuddy DOES infect other processes (in our case the gw2 game client) by injecting user selected .dll fils to the process. This is needed to support 3rd party softwares in multiboxing mode as the default "load the directx.dll and inject stuff there" only works on single gameinstance usage.

**Comment by eodgod406** [comment]
> https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Virus:Win32/Wacatac.B!ml&ThreatID=2147774417
> 
> States : "This [virus](http://www.microsoft.com/security/portal/mmpc/shared/glossary.aspx#virus) spreads by attaching its code to other files on your PC or network. Some of the infected programs might no longer run correctly."
> 
> Which sound very familiar to the dll injection feature of Launchbuddy. So a "false positive" in this regard isn't quite right. Launchbuddy DOES infect other processes (in our case the gw2 game client) by injecting user selected .dll files to the process. This is needed to support 3rd party softwares in multiboxing mode as the default "load the directx.dll and inject stuff there" only works on single gameinstance usage. So on the one hand the virus scan isn't wrong about it, on the other hand this is a key feature to support 3rd party software like arcdps etc.
