### ISSUE TITLE
Can't open multiple accounts simultaneously (Errorcode: 8)

### ISSUE THREAD

**Issue by KOVIKO** [TheCheatsrichter/Gw2_Launchbuddy#367]
More often than not, I cannot open multiple accounts. The only thing that seems to work is closing GW2 and trying over and over again until it works....

Whenever an account does not open, I get a dialog citing "Errorcode: 8"

![image](https://user-images.githubusercontent.com/835767/186042933-2f99a6cc-784e-4a69-93cd-89d9538e42e3.png)

This issue started for me shortly before the release of 3.0.5 and continues to be an issue after upgrading.

**Comment by Nut3lla1** [comment]
Same here
