### ISSUE TITLE
have to redo every set login after gw2 patch

### ISSUE THREAD

**Issue by Ryu-Pendragon** [TheCheatsrichter/Gw2_Launchbuddy#368]
happen to me multiple time after gw2 patch all my set login got broken and cant even repair them so i have to redo all my 50 set login info :(

**Comment by Me4fun** [comment]
bruh same

**Comment by MiryksV** [comment]
Since the last update of 23th August 2022. The work-around by (re)setting loginfile again all account works well

**Comment by akeck** [comment]
I got a dialog telling me that nothing has changed since the update, and if I want to continue.
When it finally finished, every second account was corrupt and I had to repair the login file.

**Comment by akeck** [comment]
I got a dialog telling me that nothing has changed since the update, and if I want to continue.
When it finally finished, every second account was corrupt and I had to repair the login file.
