### ISSUE TITLE
V3.0.5 No alt accounts will launch, Blish disappeared from addons

### ISSUE THREAD

**Issue by She-Ra8315** [TheCheatsrichter/Gw2_Launchbuddy#369]
Yesterday, LB was slow, but working. The main issue til today, was that the windows opened in odd sizes, not how I set them.

As of today's patch, I can only log in to main account, all alt accounts just open up duplicate of main account. Error messages pop up telling me to recreate login file for each I try to launch, including main account, even tho it opens main. Blish no longer in addons, added it back, but not showing like it used to. I can't remember if I had TacO added, don't know if it needs to be, & don't know where to find it in Windows Explorer.

**Comment by She-Ra8315** [comment]
I've also tried a few times to repair (unsuccessfully) and to recreate the login (also unsuccessful). These attempts merely launch my main account. Is there a solution, short of removing each alt account & starting from scratch?

**Comment by sveeke** [comment]
Same for me. As of today, only my main account (which is the first one added to LB) will login. All other accounts just load my main account. There are some notices about `Invalid Login file <number> please recreate this file in the account Manager.`, but this doesn't seem to work very well.

**Comment by She-Ra8315** [comment]
After I got all the login files reset, everything worked better than ever....then another gw2 build, resulting in a new LB crash. I guess I have to reset all the logins every time we get a new gw2 build/patch
