### ISSUE TITLE
Way to remember position and size of each windowed sessions

### ISSUE THREAD

**Issue by slipenbois** [TheCheatsrichter/Gw2_Launchbuddy#37]
-Hello i run 5 accounts at the same time so could be nice if i was not forced to resize and move them between my 2 screens each time i restart them.

-Could we have individuals parameters for each session ? (nomusic for one and not for the other etc) i think it will be implemented with the shortcut functionality but just in case.

Regards.

**Comment by TheCheatsrichter** [comment]
>Hello i run 5 accounts at the same time so could be nice if i was not forced to resize and move them between my 2 screens each time i restart them.

Coming with future additional game instance management.

> Could we have individuals parameters for each session ? (nomusic for one and not for the other etc) i think it will be implemented with the shortcut functionality but just in case.

Will come later as the first thing that has to be done is to bind the choosen arguments to a account.
