### ISSUE TITLE
The loginfile for "accountname" did not change when updating from 132525 to 133322. Proceed anyway?

### ISSUE THREAD

**Issue by accelleratii** [TheCheatsrichter/Gw2_Launchbuddy#370]
It happens for each account, on app launch - before selecting and launching any account. Followed (if clicking YES on the prompt) by the game launching in windowed fullscreen (not the settings I saved it with). Clicking NO at this prompt seems to be updating a login file, but login window has to be closed manually each time for every account.

After manually going over all accounts, app did manage to launch itself, but now most of the files are "invalid:" and ask for recreation via the "account Manager."

**Comment by accelleratii** [comment]
Clicking NO at thsis prompt seems to be updating a login file, but login window has to be closed manually each time for every account.

**Comment by Ryu-Pendragon** [comment]
Same i know the feel ... i have 51 account and it take age every time to recreate everything :(

**Comment by accelleratii** [comment]
I disliked how the other one handled some things and tried it for the second time just before 3.0.5 release, a bit of mess with .dat file creation, which is probably documented somewhere but I have not figured it out yet.

**Comment by suialthor** [comment]
I spent most of the evening on Tuesday resetting logins and then having to wait forever to log into the accounts.  Doing this once is annoying but having to do after every update is too time consuming.

**Comment by Ryu-Pendragon** [comment]
just happen rigth now again ... another few hour lost ...

**Comment by Alimar777** [comment]
Happened again for the small patch. Only way to fix it is to manually log in which, of course, is the whole point we're trying to avoid with Launchbuddy. 

Thanks for all your hard work and I hope for a fix soon!

**Comment by Drogon1234** [comment]
> Same i know the feel ... i have 51 account and it take age every time to recreate everything :( im close to burn out just with all prob with gw2 launcher :(
> 
> someone know if the other app gw2launcher is better for this ?

The other one doesn't seem to have any of these issues. I'm going to use that one for now until LB gets more frequent updates.

**Comment by sveeke** [comment]
Never tried the other one, but good to know it doesn't seem to have the same issues. Will try it today as well. I always liked using Gw2Launchbuddy but it simply gives me too much pain/costs too much time right now (and over the past two weeks).

**Comment by accelleratii** [comment]
Trying to figure the other one out, seems I have to press YES on the first launch, set all the settings in-game, use COPY dat when cloning, and select YES to store passwords in the game launcher. It is overcomplicated for no reason.

**Comment by Drogon1234** [comment]
> Trying to figure the other one out, seems I have to press YES on the first launch, set all the settings in-game, use COPY dat when cloning, and select YES to store passwords in the game launcher. It is overcomplicated for no reason.

I never set up the other one properly because I preferred LB, but waiting for updates every patch is getting annoying. I'm gonna try to find a guide on how to set up the other one properly. It asks stuff like local date or share local dat and I have no idea what the differences are.

**Comment by sveeke** [comment]
Haha I was just trying it as well and also got confused by the questions. Also I get the `Unable To Open Archive File` error, so I guess that killing the mutex doesn't work for some reason (but I believe I used the right setting for that). If I get it to work I'll report back here.

**Comment by accelleratii** [comment]
They do have their own repo here, and a well-documented wiki. What I am guessing, "share" is used when you wish to reduce space requirements for all the extra .dat files, and use the in-app password/account save option. But we better move our discussion there, as their user base might have more answers on the topic.

**Comment by Drogon1234** [comment]
These issues would already be a lot less annoying if setting the login file didn't require you to log in to the game. When I have to fix all my accounts it takes an hour because setting the login counts as a login so after a few the DDOS protection kicks in and you have to wait before you can do the next one

**Comment by AEsylum** [comment]
Since 3.0.5, every GW2 update I have to use the Repair Login function for every account saved on LaunchBuddy. Please fix this soon, thanks.

**Comment by ubereffect** [comment]
SOLUTION: Temporary fix, download the older [Launchbuddy Version 2.4.2](https://github.com/TheCheatsrichter/Gw2_Launchbuddy/releases/tag/2.4.2) and use it to update your gw2.dat files. Once updated, go back to using the latest version.

Credit goes to [akek](https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/368#issuecomment-1229076706)

**Comment by Ryu-Pendragon** [comment]
it 100% work you sur  :O ??

**Comment by phynxlyncis** [comment]
Tested and yes updating with 2.4.2 works ^^ Thanks

**Comment by accelleratii** [comment]
> 

Has anyone tested if 3.0.4 works fine?

**Comment by ubereffect** [comment]
> > 
> 
> Has anyone tested if 3.0.4 works fine?

I haven't tested any of the 3.0.X versions, just the most recent 2.X.X one. Having said that, I've only needed to run the old version to update my gw2.dat files. Once updated, I go right back to using 3.0.5 without issue.

To clarify, I have both version in separate folders on my PC. No need to keep replacing/overwriting your Gw2.Launchbuddy.exe file. I suppose if you rename one, you should be able to keep them both in the same folder, and have them work just the same. I've also created shortcuts for each, to make it easier for me. Hope this helps.

**Comment by ubereffect** [comment]
> SOLUTION: Temporary fix, download the older [Launchbuddy Version 2.4.2](https://github.com/TheCheatsrichter/Gw2_Launchbuddy/releases/tag/2.4.2) and use it to update your gw2.dat files. Once updated, go back to using the latest version.
> 
> Credit goes to [akek](https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/368#issuecomment-1229076706)

UPDATE: When I posted the above, running 2.4.2 would automatically update all of my gw2.dat file, without giving error messages, or requiring me to manually repair them. Well that changed for me, with today's update.

This time around, 2.4.2 kept giving me errors, and wouldn't update my gw2.dat files. But after I worked through the error messages (for all of my accounts) the Launchbuddy program window finally loaded up, and without crashing. Which is better than my experience with 3.0.5 which always crashed when my gw2.dat files needed fixing.

SOLUTION (Part 2): If simply running [Launchbuddy Version 2.4.2](https://github.com/TheCheatsrichter/Gw2_Launchbuddy/releases/tag/2.4.2) doesn't automatically update your gw2.dat files. Proceed to click on 'Account Settings', select an account who's gw2.dat file needs updating, click on 'Login Credentials' followed by the 'Repair Loginfile' button. Do this for each of your accounts. No need to re-enter login info, just a few clicks and a short wait per account.

Clarification: Once your gw2.dat files have been updated, you can go back to using the latest 3.0.5 version. At least until the next game update. I keep both versions in separate folders on my PC.

**Comment by TheWhiteWolves** [comment]
> > 
> 
> Has anyone tested if 3.0.4 works fine?

Yes v3.0.4 is work fine, I've just downgraded until @TheCheatsrichter can provided a new fixed version, I'd rather deal with the obnoxious popup window than recreate all 20+ accounts after each patch
