### ISSUE TITLE
Game starting in full screen and unlimited fps even though I have it set to windowed fullscreen and 30FPS

### ISSUE THREAD

**Issue by Drogon1234** [TheCheatsrichter/Gw2_Launchbuddy#371]
Since last patch I had to redo all my accounts. I fixed the login files, settings are same as before with everything on lowest, windowed fullscreen and fps limited to 30. However, the game instances are launched in fullscreen mode with unlimited fps.

**Comment by Ryu-Pendragon** [comment]
very inconsistent setting on my game to sometime windowd like i want but most of time nope and that annoying unlimited fps to  ...

**Comment by accelleratii** [comment]
As discussed in https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/370 most of us have downgraded to the previous version. Bugs in alpha are very taxing for people with many accounts. I'd recommend you do the same unless you want to recreate your .dat files from scratch: you need to start the game normally, and configure all the settings first (windows size/position, etc) then start LB and create your .dat files, they will all inherit the settings from the previous configuration.

**Comment by Drogon1234** [comment]
How does that work if I've already 'fixed' all since last patch? Do I downgrade and then use repair login file on all and then go back to the alpha versions?

**Comment by accelleratii** [comment]
> 

If they work now just leave it alone, if once a new game patch breaks them, run the old version of the app.
