### ISSUE TITLE
Launchbuddy no longer launching accounts with a login delay

### ISSUE THREAD

**Issue by hECANATOR** [TheCheatsrichter/Gw2_Launchbuddy#372]
So with the new patch I first had the issue that I had to redo all my accounts settings.
No big deal, that was quickly done.
But now when I select all of them to log in, it doesn't automatically put in a log in delay.
Is anyone else experiencing this?

**Comment by Poocifer** [comment]
Same here. It is also messing with my volume and bricking my logins by refusing to update

**Comment by oats-and-apple** [comment]
Yeah, cannot launch multiple accounts at the same time for over a month now.
