### ISSUE TITLE
Can't create new account login

### ISSUE THREAD

**Issue by asteentje** [TheCheatsrichter/Gw2_Launchbuddy#373]
Can't create a new/current login because after pressing 'create login' it opens and closes gw2 launcher and nothing happens after that.
Running v3.0.5

**Comment by ubereffect** [comment]
I haven't tried or needed to create a new login on 3.0.5. Having said that, 3.0.5 has an issue with updating existing accounts whenever there's a new GW2 patch. Solution for that is to download the older [Launchbuddy Version 2.4.2](https://github.com/TheCheatsrichter/Gw2_Launchbuddy/releases/tag/2.4.2) and use it to update your gw2.dat files. Then once updated, you can go back to using the latest version. Not sure if the same solution would work for creating new logins, worth a try.
