### ISSUE TITLE
can't login my alts properly

### ISSUE THREAD

**Issue by CerberusKCO** [TheCheatsrichter/Gw2_Launchbuddy#374]
Hello;
its been more than 1 months i'm having this issue now; i have multiple alts account but when i try to login 3 or more alts at same time, i get white screen on multiple account and i can't login or get to the character select window; it's stuck on a white screen permanently and i have to close the window. I guess this issue has already been mentioned and i can't find a solution for it.
if you can help please.

**Comment by MiryksV** [comment]
Have same problem with 2 alt accounts

**Comment by MiryksV** [comment]
@CerberusKCO, I maybe find something. I saw that the white screen always occurred when your first window didn't load fully the character menu. You just need to manually quickly Launch window and wait for fully loading before launching again next windows
The workaround works great for me!

**Comment by TheCheatsrichter** [comment]
3d26c9f6c620bbdbe9a25f94d5212f5e3108378f
2fad5247d19fcfd194437a7db321f75d65e08872
eafc4e350e99390e56c42be9158abf193d366c72
These commits touched some essential parts of the GW2 gameclient management.
Will be pushed with next public release version 3.1.0.

**Comment by ubereffect** [comment]
While I've had the same issue, and still do. I was surprised to see it improve with the recent GW2 game update(s). I went from getting white screens 1/3 of the time, to 1/20th of the time. Looking forward to 3.1.0.
