### ISSUE TITLE
Is it possible to set window size?

### ISSUE THREAD

**Issue by WKMEG** [TheCheatsrichter/Gw2_Launchbuddy#378]
I found some old posts on this this and the solutions didn't work for me. I have to resize the tiny windows every time I use Launch Buddy.

**Comment by She-Ra8315** [comment]
I did it awhile ago in the advanced settings for each account. It's not perfect, but some of the windows start where I want them to. I'll be resetting them soon, see if they open to the size I set them

**Comment by TheCheatsrichter** [comment]
54b0de6df2979630c1cd878d033a55861a6f22b0
Moved Window settings to its own tab for better user visibility

**Comment by WKMEG** [comment]
Thanks. Is there a quicker way to get the same window settings for each account other than setting the window size/position manually for each one?

**Comment by accelleratii** [comment]
> Is there a quicker way to get the same window settings for each account other than setting the window size/position manually for each one?

What I did, was set up first .dat files with the gfx settings I needed via the game. Created all the other files via LB "clone" afterward, so they all match by default now, no need to mess with gfx settings in LB, which were inconsistent at the time.

**Comment by WKMEG** [comment]
> What I did, was set up first .dat files with the gfx settings I needed via the game. Created all the other files via LB "clone" afterward, so they all match by default now, no need to mess with gfx settings in LB, which were inconsistent at the time.

I've considered doing that. But I assume it would require me to re-enter the login info for each account.
