### ISSUE TITLE
ddos protection timings 

### ISSUE THREAD

**Issue by PaRTWasTaken** [TheCheatsrichter/Gw2_Launchbuddy#380]
Hey, so to start out I guess I'll say that it's not a issue, more of a feature request. I have over 40 accounts and in the older version the ddos timings would run out after around an hour? which meant that you had to do all your logins quickly and if you waited too long then launchbuddy would open accounts too quickly while the 6 or so hours hadn't passed. This is fixed now with the new timings and it's been pretty consistent.
However the problem I'm having is I use 2 ip addresses (home and work) to do all my logins, so I'd do 40 at home and then the rest at work, and by the time I got there the ddos timings would have reset and I could do the logins during my lunch break. Now I have to wait for 6 hours or launch 1 account every 2 minutes. 
Would it be possible to get a button that resets the ddos protection? turning it off and on again doesn't seem to work, and I have too many accounts to launch them with the ddos protection off completely. It turns into a micromanagement nightmare. 
Is there some file I can edit and do it manually? I tried looking into the files and it looked like each account has a timestamp and there's no single location where I could remove/replace a line and reset it myself.

**Comment by blashmer** [comment]
I just do a backup of my file before launching accounts so i can keep launching acc.
You can also change the hour of your PC.

You can do a .bat file to only have to run launch the command.

I do this 
xcopy "C:\Users\username\AppData\Roaming\Gw2 Launchbuddy\old" "C:\Users\Username\AppData\Roaming\Gw2 Launchbuddy" /y

You need to have put your files in "old" before launching your acc.
files I backup Accs.xml Addons.xml lbac.txt LBConfig.xml
It will work until there is a game update

**Comment by TheCheatsrichter** [comment]
I will implement an additional check if your public ip adress has changed. If the ip adress changed then the delays will be reset until either the timer runs out (60mins atm) or the ip changes again.

**Comment by blashmer** [comment]
that would actually be awesome. So ppl who can change IP can launch account very fast without having to play with files.

**Comment by PaRTWasTaken** [comment]
Yeah, I haven't gotten around to the playing with files bit, but you got it right. 1 pc, multiple ip addresses, it would be awesome if it was either a button that allows you to reset back to square 1 or some automatic IP change check which would be awesome. Now if it kept multiple lists for each IP... but that's asking for too much xD

**Comment by TheCheatsrichter** [comment]
Added with Version 3.0.12 (patreon exclsuive) https://github.com/TheCheatsrichter/Gw2_Launchbuddy/commit/c97d756c8e50b2dd1058651b254e4160998e8f31
Will be included in the upcoming 3.1.0 public release.
