### ISSUE TITLE
Possibility to close BlishHUD when closing the game?

### ISSUE THREAD

**Issue by wolfeng-db** [TheCheatsrichter/Gw2_Launchbuddy#382]
We have an option to auto start BlishHUD with the game, but I can't seem to find anything to auto close BlishHUD when I'm done playing.

**Comment by TheCheatsrichter** [comment]
Small oversight from the pull request back then. Fixed it. LB will now close the Taco/ BlishHUD instance whenever the gameclient of the account gets closed. Coming with public release 3.1.0

**Comment by Stis** [comment]
It can be done in BlishHUD itself, even if the option name isn't clear on this.
In Overlay settings, just uncheck "Minimize to tray when Guild Wars 2 Closes."
