### ISSUE TITLE
Is there a way to update multiple Launchbuddy clients automatically? [After GW2 Patch]

### ISSUE THREAD

**Issue by Stalvr0s** [TheCheatsrichter/Gw2_Launchbuddy#384]
Am currently using Launchbuddy 3.0.6 Alpha

So what happens is this; 
Say I have account A,B,C,D,E
Say that I only want to launch the clients 1 by 1 (not 5 at a time)

After each gw2 update patch, providing I did not restart the Launchbuddy 3.0.6 Alpha I find that I couldn't launch the client A as it's not updated. That's fine! So I restart Launchbuddy 3.0.6 Alpha and it says please do not close window as the program will update the client automatically. Once it's updated, I then proceed to launch client A and it works fine! 

Now - I was under the assumption that when it automatically update the client, it was for client A-E.
Because once I launch client B, the same thing happened and I have to close Launchbuddy 3.0.6 Alpha and wait for it to update again!

I was wondering if there's an option to update all the clients AT THE SAME TIME?
Instead of me just having to close / restart to update each and individual PER account basis?

**Comment by Stalvr0s** [comment]
PS: When I say it wouldn't work, I launched client B -> It starts to update the client followed by 'Connection Error'
I then have to close the client and re-launch launchbuddy before it updates client B in particular before it works!

**Comment by ubereffect** [comment]
Since 3.0.6 I've only needed to update my clients twice. Once Sept 13th, then again Sept 15th. Both times Launchbuddy updated all of my clients in sequence, and the Launchbuddy window popped up once it was done.

That being said, I likely had to close and restart Launchbuddy after it updated my first client, in order for it to finally go through the rest of my clients automatically on it's own. I don't fully recall how it went these last 2 times, but I've experienced this often enough. Both before, and I believe since, 3.0.6.

3.0.6 has been good enough for me so far. And 3.1.0 should improve on this, as it's to include many bug fixes.

**Comment by Stalvr0s** [comment]
I used to do that with the older version of launch buddy
for some reason - it didn't seem to work with this one~

> Since 3.0.6 I've only needed to update my clients twice. Once Sept 13th, then again Sept 15th. Both times Launchbuddy updated all of my clients in sequence, and the Launchbuddy window popped up once it was done.
> 
> That being said, I likely had to close and restart Launchbuddy after it updated my first client, in order for it to finally go through the rest of my clients automatically on it's own. I don't fully recall how it went these last 2 times, but I've experienced this often enough. Both before, and I believe since, 3.0.6.
> 
> 3.0.6 has been good enough for me so far. And 3.1.0 should improve on this, as it's to include many bug fixes.

**Comment by TheCheatsrichter** [comment]
Launchbuddy should actually do the following when a gw2 updates hit:
- On launch LB checks if your gw2 client is up to date
- If not, update it without swapping any loginfile and close it
- After that check all accounts which have a loginfile set. If the loginfile version < gw2 version flag it as outdated
- Go through each account one after another by, swapping the loginfile, launch gw2 and then close it.

So if you mean by at the same time that each acc should be updated one after another that SHOULD be the case. However there are currently some known bugs which will be addressed in 3.1.0.

If you mean by the same time that LB should launch like 5 clients at the same time to update 5 loginfiles this is simply not possible. The gw2 gameclient always looks at the same path. So even if LB could redirect the path (symlink) a small timing or crash could lead to one loginfile overwritting another.

**Comment by Stalvr0s** [comment]
> Launchbuddy should actually do the following when a gw2 updates hit:
> 
> * On launch LB checks if your gw2 client is up to date
> * If not, update it without swapping any loginfile and close it
> * After that check all accounts which have a loginfile set. If the loginfile version < gw2 version flag it as outdated
> * Go through each account one after another by, swapping the loginfile, launch gw2 and then close it.
> 
> So if you mean by at the same time that each acc should be updated one after another that SHOULD be the case. However there are currently some known bugs which will be addressed in 3.1.0.
> 
> If you mean by the same time that LB should launch like 5 clients at the same time to update 5 loginfiles this is simply not possible. The gw2 gameclient always looks at the same path. So even if LB could redirect the path (symlink) a small timing or crash could lead to one loginfile overwritting another.

Which is v strange why mine is doing it :(
I used 3.0.4 and it didn't have this issue~
It's only when I used 3.0.6 when it has this issue~
I was wondering if its the way I install it that's wrong or something else?
What i did was to just download the .exe file and place it in C:Program Files / Guild Wars 2
and launch it from there

**Comment by TheCheatsrichter** [comment]
Problem is that 3.0.6 does not like the client "sself updates". There are basically 3 different components that make out a gw2 update. If we calc all combinations we come out with 9 different "ways" a gw2 can update, of which 4 seem to cause some trouble at 3.0.6.

So it might not even be the LB version it could just be that the latest update was an update type LB can easily handle in its current state.

**Comment by Stalvr0s** [comment]
At the moment, i'm quite tempted to actually use the older version of LB :(
Though the last time I used 3.0.4 before updating to 3.0.5, there was an error with launching gw2 clients~

**Comment by TheCheatsrichter** [comment]
Closing this issue to merge multiple issues with the same problem
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/387
