### ISSUE TITLE
3.0.6 - Game update breaks Loginfiles

### ISSUE THREAD

**Issue by Flapjakk** [TheCheatsrichter/Gw2_Launchbuddy#387]
That's been most days for the past week.

10 accounts, a variety of different errors. 

Some accounts patch fine. Mostly not, though. 

When launching some accounts, you get a screen that says in red text: "Download failed! Please check your internet connection and try again. (5)" Trying again never works. 

Sometimes doing a manual "repair login file" from the account settings works. Sometimes it doesn't. It's a crapshoot. 

Occasionally this produces a system style window error that reads, "An error araised when the login file was restored to its original form. Loginfile might not be set correctly now." When this does occur, it's usually hidden. It's always completely unclear why this would be happening on some accounts but not others.

Sometimes when there's an error, the account username and password is remembered. Sometimes it's completely forgotten. Sometimes it swaps to a completely different account's credentials.

Sometimes there's a system message window that hides behind all windows, so you dont see it.

Sometimes there's an error that reads "The login file for [account] did not change when updating from 0 to [13-----]. Proceed anyway?" Sometimes the 0 is a different number. It's completely unclear whether "yes" or "no" is the correct response, but one of them consistently trashes the entire account.

Most of the time Launchbuddy and its popup windows appear un-minamizable over the screen. It lags constantly while it works, locking out interaction or even dragging the window around, usually at the times I most need to interact with it. This makes dealing with the already ridiculous repair times *even longer.*

I've experienced this behavior over the past year on three different computers.

But it's been happening every day for a week now. Dear god please make it stop.

**Comment by ubereffect** [comment]
A few personal observations running 3.0.6

If there's a game update while I'm in game with Launchbuddy open, it gives me an error and locks up if I simply exit the game and relaunch using Launchbuddy. If I close and relaunch Launchbuddy itself, it then recognizes there's a game update, and proceeds to update the game client, but only once. If I close and relaunch Launchbuddy itself once again, it then updates each individual game client I have setup.

Maybe a little more effort then it should be, but works well enough as is (at least for me).

One last observation. If I launch a bunch of game clients at the same time, and proceed to select character as they become available, I sometimes end up getting blank screens for some other clients that were still waiting to launch. Doesn't happen all the time, but happens often enough. If I wait until my game clients have all finished loading up, before clicking or doing anything, no more blank screens.

Guessing some, if not all of the above, has been addressed in 3.1.0 which Patreon supporters got early access to 3.5 weeks ago.

**Comment by Flapjakk** [comment]
Thanks for the feedback. It's difficult to specify (or even determine) the exact chain of errors, because there are different sequences of the same elements, plus so many different windows popping up  -- and some of them hidden -- that you cant tell which account launch or in what sequence they occurred. 

But what they all have in common is patches. Almost every time there's a patch, there's a huge problem. What is also consistent is that LB is inconsistent: sometimes cancelling LB and patching from a standard client launch works, most times it doesn't. Most times it's some accounts that have errors, sometimes it's all of them. Sometimes manually hitting the "repair login file" button fixes, things, sometimes it doesn't. 

In my situation, the errors don't arise from playing while the patch drops, though that's a good observation. I don't seem to experience those black game screens.

Another thing worth noting is that nothing can be fixed while a game client is running, so you have to wait for LB to finish all of its operations on however many accounts you launched.  That's a lot of waiting, error windows, and room for compounding errors. A workaround is to only launch one account at a time, at least for the first login of the day. But that doesn't completely fix the problem of course.
