### ISSUE TITLE
Looking for an alternative, older version to use 

### ISSUE THREAD

**Issue by AnnieAcrux** [TheCheatsrichter/Gw2_Launchbuddy#389]
Is there an older verion of LB that works right now? 
The latest version of LB is still not working for me, it won't update nor save my login files. I get error messages (like error 10) when I try to launch my accounts.
I haven't logged into my alts since the august update, so I am losing a lot of resources. Is there any other older version I could use until a new LB is out?
Thank you

**Comment by TheCheatsrichter** [comment]
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/releases
is a list of all versions.
Keep in midn that a newer version 3.1 just released yesterday
