### ISSUE TITLE
GW2 Launch Buddy process dies while loading.

### ISSUE THREAD

**Issue by CedarD** [TheCheatsrichter/Gw2_Launchbuddy#39]
Basically what the title says. 

In Event Viewer the following event is generated:
Faulting application name: Gw2.Launchbuddy.exe, version: 1.4.1.0, time stamp: 0x58aad2fe
Faulting module name: dxgi.dll, version: 3.0.6.165, time stamp: 0x586927a4
Exception code: 0xc0000409
Fault offset: 0x00000000001143eb
Faulting process id: 0x2688
Faulting application start time: 0x01d2b3c62338d2a3
Faulting application path: E:\Guild Wars 2\Gw2.Launchbuddy.exe
Faulting module path: E:\Guild Wars 2\dxgi.dll
Report Id: 4268fbc6-0879-4b4c-a6be-798017af3f0b
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Qlii256** [comment]
I'm having the same problem. I wanted to start using this application, but it never even opens (the GUI). I see the process is starting when double clicking, but then it disappears. Seems like me there is a problem, doesn't matter if I run as admin. or try comp. mode.

Could this issue being looked at?

**Comment by TheCheatsrichter** [comment]
Seems like reshade or another .dll injection library targets Launchbuddy. Try to move Launchbuddy in another folder than the Gw2 Gamefolder, or make a folder for Launchbuddy itself.

**Comment by Qlii256** [comment]
I have it on my desktop... I've never used this application before, do I need to install or configure something specific first?

**Comment by CedarD** [comment]
I did that and so far so good. The only issue I'm having currently is Launchbuddy forgetting the flags and the servers I've set up each time I start the program.

**Comment by Qlii256** [comment]
The app crashed and then I couldn't start it again. There seems to be something wrong?

**Comment by Qlii256** [comment]
Again numerous reboots and app is just not opening for me, I can see the process starting but it then disappears just like that. Do you want me to give some more detailed information like logs etc. ?

**Comment by KairuByte** [comment]
Are you by chance running the windows creators update?

**Comment by Qlii256** [comment]
Yes, I am. Is that giving me problems? Could it be the Rivatuner statistics server? I had problems running GW2 with that application.

**Comment by KairuByte** [comment]
This is going to be one of those things that LB isn't going to be able to handle. External applications hooking into LB processes are bound to cause problems, so I think in this case we can consider this not something that needs to be corrected in LB.
