### ISSUE TITLE
Patch Day, All Hell Breaks Loose in Launch Buddy

### ISSUE THREAD

**Issue by Flapjakk** [TheCheatsrichter/Gw2_Launchbuddy#390]
Same issue from #387. Patch day today, 7/10 accounts configured in LaunchBuddy broke. Took it slowly today to more clearly document the sequence of events.

1) Starting LaunchBuddy gave an error popup, warning that something was wrong with patching, so please patch the game regularly without LB. Did that.
2) Launching LB again produced several "Errorcode: 8" messages that got hidden behind other windows, of the "Account so-and-so didn't update from x to y, proceed or not?" variety. I said yes in every case.
3) When launching one of these broken accounts, the GW2 launcher produced the red-text error message "Download failed! Please check your internet connection and try again."
4) After this error message, LB freezes for a long time, preventing any interaction with it, then produces the "Errorcode: 10" message, "Client so-and-so got closed or crashed before a clean Start... Do you want to retry this Client?"
5) Saying "yes" never works, it just takes you back to step 3, the red "download failed" error on the game client.
6) Some of the broken accounts' last-accessed dates change to the current date, some don't. So it's not possible to tell which ones broke without manually recording them as you go or doing the failed-launch loop multiple times to check.
7) Fixing the broken accounts requires manually going into each account's "Account Settings" screen individually, clicking "Repair Loginfile," and going through that process.
8) Note that a slightly different sequence of events will break the accounts even further, preventing the "Repair Loginfile" button from working and requiring the account credentials to be redone from scratch. I believe this happens when you chose "no" on the 'account didnt update from x to y, proceed?" error, but I didn't test that today.
9) Sometimes, even when following these steps, an account will stay broken and not repair. This happened today for 1 out of 7 broken accounts. Successive repair attempts on this account eventually produced the error message, "An error araised when the loginfile was restored to its original form. Loginfile might not be set correctly now."
10) Broken accounts can only be fixed while no other instance of the game is running.
11) This repair process removes window size and placement settings.

LB version 3.0.5. Has happened this way on past versions and different computers, too.

Thanks for your attention to this matter.

![Errorcode 8 - retry](https://user-images.githubusercontent.com/84879230/200993493-d3c19ff7-9748-45cc-882c-bf0d7e941fff.png)
![red text - download failed](https://user-images.githubusercontent.com/84879230/200993510-29be47dc-12df-4886-b5a8-c9a32fde205c.png)
![Errorcode 10 - retry to start client](https://user-images.githubusercontent.com/84879230/200993584-95a21804-4495-4bda-a7fb-294ed76923a5.png)
![an error araised](https://user-images.githubusercontent.com/84879230/200993628-d6ac4ba2-58f0-416d-af1b-0a6f5b0a2599.png)

**Comment by luzclasil** [comment]
Yep, facing the same issue as well.
I've noticed clicking here (Repair Loginfile) fixes the issue but this is a very boring solution if you have 40+ accs like I do.
The auto Launchbuddy login update after gw2 update does not work (gives error 5 - download failed), it's feen behaving like this for a couple of days now.
The only way I was able to fix this was by manually clicking "Repair Loginfile" for all accs. I'm using LB latest version 3.0.6 Alpha
Thank you!
![image](https://user-images.githubusercontent.com/45974378/201254082-c8d467f8-1e01-4fd5-981b-7364a230a116.png)

**Comment by AZDarkknight** [comment]
Same also. It appears that the LB update is timed and does not wait for the download of the new version file before moving onto the next one thus not actually updating the GW2 version. Additional issue for me is when doing the repair login file when the software just randomly "forgets" the login account name, meaning it has to be left for a while and another repair attempted.

**Comment by Flapjakk** [comment]
>Additional issue for me is when doing the repair login file when the software just randomly "forgets" the login account name, meaning it has to be left for a while and another repair attempted.

Same here. Should have added that to my original post.

**Comment by Stalvr0s** [comment]
There is actually a way to update the client WITHOUT having to repair login file and having to input your username and password for each account one by one.
I've mentioned this in the other thread 
(and yes, this is an old issue that has been mentioned several times but WITHOUT ANY FIX!)
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/384

With this issue in hand, you usually pray that Anet doesn't launch as many updates as they do -_-.
Most times with major updates, they did it 3 days in a ROW! 
1st day to patch PvE
2nd day to patch PvP
3rd day to patch WvW
and you have to either 'repair login file' or do the method I suggested for...... 3 days in a row -_-

I really hope the creator of launchbuddy sees this issue and will fix them as soon as possible.
Either that or just let us use the OLD version of launchbuddy that doesn't have this issue!

**Comment by TheCheatsrichter** [comment]
Closing this issue to merge multiple issues with the same problem
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/387
