### ISSUE TITLE
Account Name field randomly left blank upon launch

### ISSUE THREAD

**Issue by Windfreeze1** [TheCheatsrichter/Gw2_Launchbuddy#391]
**Describe the bug**

When launching accounts, either alone or multi-launching, more often than not the Account Name field will be left blank requiring me to manually type in the acc name. Repairing the login file also does not work, as it will "repair" it by pulling up the launch window with the acc field empty in the same way launch attempts will. Having the optional backup information fields filled out also does not correct the issue.

**First happened in LB Version**
This has always been an intermittent issue for Launchbuddy. It seems like some releases mitigate it, while it becomes much worse in others.

While the workaround provided in https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/383 does seem to fix this issue, it is at the cost of making my game look like garbage on my 4k monitor, and addons such as Arcdps are scaled terribly and huge. As such, I don't consider it a viable workaround.

**Comment by vm0d** [comment]
found this issue to be a gw2 client issue, not lb issue.

gw2-64.exe > properties > compatibility > change high dpi settings > click override high dpi scaling behavior > select "System" from the dropdown menu

-however-

afterwards, lb will not interact with the gw2 login gui correctly.

effects include:
random inputs in the password field
opening new player guide multiple times in browser
lb progress bar not attaching to the gui in the correct location
