### ISSUE TITLE
Updates all login files every time i open LB

### ISSUE THREAD

**Issue by Drogon1234** [TheCheatsrichter/Gw2_Launchbuddy#392]
Per title, every time i restart launchbuddy (i.e when i have restarted my PC), it will start updating all of my login files.

Does anyone else have this? I thought this version had already been live for a while for patreons so I figured it was safe to download the new update.

**Comment by PremiumQuality** [comment]
Same issue here after updating to the latest version

**Comment by ManiakNL** [comment]
Same here (just upraded to V3.1)

**Comment by TheCheatsrichter** [comment]
![image](https://user-images.githubusercontent.com/15090699/202715557-038f5e69-cf92-4361-a808-08addb1ebb7e.png)
Is this settign disabled?

**Comment by ManiakNL** [comment]
It was enabled,

Just disabled it and the problem went away,
Does this means that the function was not working correctly on 3.0.6 and what we are seeing in 3.1 is the correct behavior?

**Comment by Drogon1234** [comment]
> 

Yep, this works. Thanks!

**Comment by TheCheatsrichter** [comment]
Reopen issue as issue gets posted multiple times
