### ISSUE TITLE
v3.1.0: Accounts don't get loaded and stuck with a white screen

### ISSUE THREAD

**Issue by ScrambledBrain** [TheCheatsrichter/Gw2_Launchbuddy#395]
**Describe the bug**
- Accounts don't get loaded and stuck with a white screen.
- Sometimes this load stucking also blocks copying file backups.
- Closing instance from with LB close button does not close the process. The stucking process could only be killed manually within task manager.

**To Reproduce**
- Steps to reproduce the behavior: using LB v3.1.0 to start multiple accounts.

**Expected behavior**
- All accounts should get loaded successfully.
- New features like mouse clicking feature for skipping 2FA button should be available optional as choosable check mark.
- Mouse clicking feature should be fail-safe for other UI languages. A fixed mouse position is maybe not working for other UI languages.

**First happened in LB Version**
- Issue first appeared in LB Version : 3.1.0

**Screenshots**
![Issue with loading (white screen)](https://user-images.githubusercontent.com/76404178/202773241-19881343-c844-4529-9e3f-2e64ca9939f3.png)

![GW2 processes](https://user-images.githubusercontent.com/76404178/202773278-1ef1b567-b34a-4587-81b7-014f2a99719d.png)

![Issue on file backup](https://user-images.githubusercontent.com/76404178/202773284-30a52edf-c291-4d89-9b93-333c8cb117ec.png)

**Comment by ManiakNL** [comment]
I already had this sometimes in V3.0.6. It did not crash but GW2 just never responded.
The only workarround was to note down which instance this occurred to and try again after all other accounts are loaded in.

**Comment by TheCheatsrichter** [comment]
Thanks for the report. I am currently trieng to reproduce this issue. Looks like somehow the gw2 client tries to access files LB is currently swapping.

**Comment by ScrambledBrain** [comment]
Seems to be timing related.
I was on a slow CPU but with SATA-SSD and the slow CPU seems to scramble the timings around for LB.
I'm now on a brand new CPU with PCIe-M.2-SSD and timings seem to be ok. I don't have such an issue anymore.
So maybe more checks inside LB are neccessary to make sure, that files were copied successfully before accounts go on loading or accounts have enough time for loading.

**Comment by TheCheatsrichter** [comment]
@ScrambledBrain  your pretty much on point of what i have seen on my end. On my machine the file lock gets closed right after the game launches (150ms delay ). If the save file process however takes a bit to long timing issues occur --> white screen. Next LB release shifts the timing to wait for the char selection screen not right after the play button is pressed. This way clients launch slower, but stability should be way better.

**Comment by ScrambledBrain** [comment]
> Next LB release shifts the timing trigger to wait for the char selection screen (currently waits for play button to be pressed). This way clients launch slower, but stability should be way better.

Yep, it makes more sense to wait, that GW2 is loaded before starting next account loading.
