### ISSUE TITLE
Add account to Gw2_Launchbuddy doesn't work

### ISSUE THREAD

**Issue by redalert99** [TheCheatsrichter/Gw2_Launchbuddy#398]
Hello,

it is not possible to add an account. when i want to create the setfile, i cannot enter any login details, because the login window disappears immediately. Can you take a look at this ?

Thanks a lot

Greetings Red

I use the latest github version.

**Comment by TheCheatsrichter** [comment]
Thanks for the report! Do you mind sharing your OS version and if you have any other third party softwares installed? (arcdps,blishhud,etc ...)

**Comment by redalert99** [comment]
I have latest Win 11 installed. No addons.

**Comment by GreenV1rus** [comment]
I am also having this issue and am also on the newest update of Win11. 

I tried using an old configuration copy from my old install's Roaming folder as well. When manually updating my login files, it opens the login window with the correct email(s) for each different account. The passwords, however either aren't being saved or something else, as when I try starting them up they say "invalid login". When manually entering the password, the account successfully logs in. 

This tells me that something isn't being saved in GW2 Launchbuddy loginfile, somehow.

**Comment by TheCheatsrichter** [comment]
I am gonna get my hands on a virtual win 11 machine soon. Fingers crossed that the issue is visible there
