### ISSUE TITLE
Difference in .exe size?

### ISSUE THREAD

**Issue by Kaukov** [TheCheatsrichter/Gw2_Launchbuddy#40]
Today I noticed that if I compile Gw2_Launchbuddy, the EXE's size is smaller than the one provided in the Releases page here on GitHub. Why is that?

**Comment by KairuByte** [comment]
I haven't been part of development lately, but it's possible the size will fluctuate for a few different reasons, including the version you compile with.

That being said, if you are concerned about security (which by all means you are allowed to be) grab a copy of JustDecompile from Telerik (or similar) and look through the source. There is no obfuscation involved in the building as far as I am aware, and you should be able to view the full source.

**Comment by Kaukov** [comment]
Okay, thanks!
