### ISSUE TITLE
v3.2.2 - Parameter is Incorrect on Launch of Accounts

### ISSUE THREAD

**Issue by TheWhiteWolves** [TheCheatsrichter/Gw2_Launchbuddy#402]
**Describe the bug**
Parameter is Incorrect Error thrown by Launchbuddy when opening accounts

**To Reproduce**

Install v3.2.2
Run any account
Get Error

**Expected behavior**
Account runs without Error

**First happend in LB Version**
Issue first appeared in LB Version : 3.2.2

**Screenshots**
![image](https://user-images.githubusercontent.com/1471503/205377750-535faf84-b353-40db-896c-b57fc21aceeb.png)

![image](https://user-images.githubusercontent.com/1471503/205377674-57a3e6b7-9be2-457a-80d3-e55e176f1ce3.png)

![image](https://user-images.githubusercontent.com/1471503/205377623-2ce3b58e-6d41-465b-b6de-5b30cc0445bf.png)

**Comment by TheCheatsrichter** [comment]
At which state does this error occur? Right after you click launch or at a later state like character select screen?

**Comment by TheWhiteWolves** [comment]
it happens when on launch immediately after launchbuddy clicks on Play in the launcher window

**Comment by TheCheatsrichter** [comment]
Fixed with https://github.com/TheCheatsrichter/Gw2_Launchbuddy/commit/d5085c982062229bcc069d85dfe4565addeca39b

Windows doesnt support zero pointer affinity even thoe the documentation states it does....

**Comment by TheCheatsrichter** [comment]
Should be fixed in release 3.2.3 please report back if your issue is solved

**Comment by TheWhiteWolves** [comment]
can confirm no more error on 3.2.3
