### ISSUE TITLE
V3.2.2 LB launches accounts twice

### ISSUE THREAD

**Issue by ManiakNL** [TheCheatsrichter/Gw2_Launchbuddy#404]
**Describe the bug**
When logging into an account and claiming the daily reward, after closing the account the same account is beeing launched again.

!! I did notice that the LB Information popup was stuck at 80% when shutting down the account
!! The LB information popup then dissapears and the same account is booted up again.

**To Reproduce**
1: Open LB
2:  Start a bunch of accounts
3: Login to an account
4: Login to character
5: Do what ever you need to do on that character
6: Check the LB information popup and see if it's stuck at 80%.
7: Close the account
8: Notice that the same account is loaded again.

**Expected behavior**
There is probably a problem for LB to determine when a account is 100% loaded
I would assume that there is a failsave introduced in V3.2.2 that automatically restarts the client when the state is not 100% and the game instance is not running (because i closed it after doing everything i wanted to do)

**First happend in LB Version**
Issue first appeared in LB Version : 3.2.2

**Comment by Fuzzydroid** [comment]
Same thing happening for me too.

**Comment by Wolfy339** [comment]
I may add to that that it also sometimes launches the second account/login launcher with random stuff written in it instead of the email!

**Comment by ZoXlike** [comment]
With V3.2.3 my whole GW2 is broken and i have to repair the client. No login is working even without LB. If a working release is up, i will disaple any updates to LB.

**Comment by ManiakNL** [comment]
Confirming that accounts are no longer started twice.
