### ISSUE TITLE
Does not start multiple instances of the launcher since 3.2.2

### ISSUE THREAD

**Issue by SuperPoggerNoob** [TheCheatsrichter/Gw2_Launchbuddy#406]
**Describe the bug**

When I use 3.1.0 I can open multiple instances of the launcher at once (as in the launchers properly load when I launch them at the same time). It does not work in 3.2.2 and 3.2.3. When I want to open 3 instances of the launcher at once (for sake of this we call it acc 1, acc 2 and acc 3) it will only open the uppermost one of the selected accounts. It will then wait until I logged into the char select of acc 1 until acc 2 even starts up and acc 3 does not do anything in the meantime either and while all that is happening Launchbuddy is unresponsive. When I close the launcher it tries to open the accounts once again and when I close that it gives me the error message if I want to retry it or cancel. I looked at the options and I at least did not have any changes between 3.1.0 and 3.2.2.

**To Reproduce**

Not sure since I only have it on my private rig.

**Expected behavior**

The launchers not waiting until I am in the character select to launch and upon closing not restarting once and on the second try asking me if I want to try again or to cancel.

**First happened in LB Version**

Issue first appeared in LB Version : 3.2.2

**Comment by luzclasil** [comment]
I'm starting to face the same issue. Sometimes I can multibox just fine, sometimes it simply won't open more than one instance of the game just like how OP reported. But no matter what, I can always open 1 acc at a time through LB, meaning there are no error w/ the login files. Very strange. It's happening a lot on 3.2.4 but I cannot remember it happening before 3.2.2.

**Comment by Wolfy339** [comment]
I have been having a similar issue since after 3.1.x. I would assume it may be related to the % bar. I am able to launch like 3 accs at once but the 4th won't happen till after I close the first and the 5th till I close another one, it happens randomly sometimes after 3 sometimes after 5 etc.. and it is still happening in the last version.
