### ISSUE TITLE
V3.2.4 LB does not detect that Login button was pressed with success, thus stuck at 40%

### ISSUE THREAD

**Issue by ManiakNL** [TheCheatsrichter/Gw2_Launchbuddy#408]
**Describe the bug**
Sometimes LB logins but fails to register that it actually succeeded
Seems like the 40% step is the pressing of the login button.

Does gives us the following behavior:

1) LB does not attempt to startup the next account because it probably thinks it was not able to press the login button, even though it succeeded

2) Sometimes LB claims that the game instance has crashed, it displays this message when i just shut down the instance of the game when I was done with it. 

!! This seems to happen more frequently with the first few accounts while the DOS protection delay is not in effect yet.

When shutting down the game instance LB will continue and start up the next game instance.
Truth to be told, this version is by far a lot better compared to the previous ones, for that.. Thank you.

**To Reproduce**
Start a bunch or instances and interact with them while not all instance have started yet.

**Expected behavior**
Expected the application to detect that the game was started up correctly and proceeds to load up the next instance.

**First happend in LB Version**
Issue first appeared in LB Version : 3.2.4

**Comment by Fuzzydroid** [comment]
This is also happening to me.

**Comment by TheCheatsrichter** [comment]
Added new Visual Trigger to prelogin startup. This should reduce false state switches between client states.
