### ISSUE TITLE
Resetting audio sliders

### ISSUE THREAD

**Issue by JordanSalihi** [TheCheatsrichter/Gw2_Launchbuddy#41]
It seems using a graphics config resets the audio sliders without an option to customize them.
Every time I launch an alt through LB my sliders are all messed up.

**Comment by DeltraEcho** [comment]
Launchbuddy doesn't store or change the audio settings, so they're probably stored in "%appdata%\Guild Wars 2\local.dat". Which Launchbuddy doesn't touch.

**Comment by JordanSalihi** [comment]
After some testing it seems I was mistaken.

Changes to audio sliders done through LaunchBuddy are only stored for the current instance. 
To do longer lasting changes I have to open up the client normally and edit the sliders there.
