### ISSUE TITLE
LB updating every loginfile everytime LB opens

### ISSUE THREAD

**Issue by morpheus305** [TheCheatsrichter/Gw2_Launchbuddy#410]
LB used to only update loginfiles whenever gw2 got an update. Now it updates every loginfile every time you open LB even if gw2 wasn't patched. For people with a lot of accounts this can be a time consuming process. My question what's the reasoning behind this change and is this going to be the way LB is going forward?

**Comment by TheCheatsrichter** [comment]
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/392
