### ISSUE TITLE
Launchbuddy 3.2.4 don't wait 2FA input

### ISSUE THREAD

**Issue by yhtojy** [TheCheatsrichter/Gw2_Launchbuddy#411]
**Describe the bug**
Launchbuddy 3.2.4 will close the game when game is waiting for 2FA input. 
It close the game and claim the game is crashed.

**To Reproduce**
Login at IP range will trigger 2FA.

**Expected behavior**
It should wait for 2FA not closing the game right away.

**First happend in LB Version**
Issue first appeared in LB Version : 3.2.3
This issue started at 3.2.3 and getting worse in 3.2.4

**Screenshots**
![image](https://user-images.githubusercontent.com/3877705/206630981-f6268b3c-98e1-4076-ace2-eeca7a875301.png)
Launchbuddy don't wait for input at this page

**Comment by TheCheatsrichter** [comment]
Thanks for the detailed report. Gonna fix this asap when I am at home. :)

**Comment by rangeraut** [comment]
also still have this issue on multiple accounts..

its very annoying especially on my 2 main alts, cause im also raiding etc.
