### ISSUE TITLE
Cannot set login files

### ISSUE THREAD

**Issue by GingerMeTimbers** [TheCheatsrichter/Gw2_Launchbuddy#414]
When I try to add an account and set a login file, the gw2 launch window where I enter my email and password pops up and immediately disappears. I have no time to actually enter my information to set the loginfile. This happens every time for every account.

When I try to click 'manually update login file', no launch window even appears. The buttons seemingly does nothing.

This started happening in, I believe, version 3.1, when the 'repair login file' button was removed. I haven't been able to even use launch buddy since, because I can't set any login file.

**Comment by accelleratii** [comment]
A postprocessing fix has effectively killed LB, and along with OP's problem, there is no Autologin or Autoplay anymore. When launching multiple accounts 1st one will sit on 80% waiting for you to manually sing-in and play.

**Comment by accelleratii** [comment]
Roll back to Gw2 Launchbuddy V3.1.0 Alpha looks like working

**Comment by GingerMeTimbers** [comment]
I actually already tried that. Setting the login file won’t actually
finalize. The little black circular window that comes up with instructions
never disappears, and if I hit cancel on it, it says, “oops. You didn’t set
the login file.”

**Comment by jazdarc** [comment]
I've been having this same issue for months, The most recent update I got the 80% freeze issue also reported. So I rolled back to 3.1.0 Alpha, and when I go to set my login files, the login pops up for 2 seconds and then disappears before I can type my login information. I haven't played the game in months because LB is broken. RIP?
