### ISSUE TITLE
Login no time to register

### ISSUE THREAD

**Issue by Kiana321** [TheCheatsrichter/Gw2_Launchbuddy#418]
**Describe the bug**
When we would register the loging we don't have time to register

**To Reproduce**
Set new loging, and try to register a new file

**Expected behavior**
Normaly we have time to register fmail and password

**First happend in LB Version**
Issue first appeared in LB Version : 3.1

**Comment by GingerMeTimbers** [comment]
Please fix this! It's literally been months, and the program is literally unusable because of this!
