### ISSUE TITLE
Launchbuddy no longer starts multiple instances!

### ISSUE THREAD

**Issue by Stalvr0s** [TheCheatsrichter/Gw2_Launchbuddy#419]
**Describe the bug**
I was using the latest build (3.2.4)
It's only until recently (about 1 month) that it refuses to launch multiple clients!
I can still launch 1 by 1 but still.....
Unsure what went wrong there~

Other then client updates, there hasn't been any changes made on my client's side~
Is there anything that can be done?

**To Reproduce**

**Expected behavior**

**First happend in LB Version**
Issue first appeared in LB Version : 3.2.4

**Screenshots**

**Comment by Stalvr0s** [comment]
I also tried launching it manually after 1 client is already open
it seems it refuses to do so~

There's no loading, no nothing
it just refuses to load more then 1 client at a time

**Comment by morpheus305** [comment]
For me I am basically having the same problem but it started with the very latest update to gw2. It will sometime only launch one client. If I try to launch 2 clients it sometimes works but sometimes it just launches one. It can never seem to launch more than 2 clients. I tried looking at the progress bar for the 2nd and 3rd clients and what I see on the screen is basically for a fraction of a second the progress bar appears at zero and goes away.

**Comment by Kiana321** [comment]
that clear, patreon start and service has been stop !

**Comment by morpheus305** [comment]
> that clear, patreon start and service has been stop !

What??? Is that even english?

**Comment by waldolflo** [comment]
Same here ! Can't launch multiple client :x
