### ISSUE TITLE
not working - STAY AWAY RN!

### ISSUE THREAD

**Issue by FixURSHT** [TheCheatsrichter/Gw2_Launchbuddy#428]
Nice Program with good Intention, but the constant troubles make it more a timewaste!

Now the Program just opens all the fking saved Files alone and doenst finish the Update, absolutely not useable anymore! 
Spent so much time setting this BS up and all, having daily issues and now its not working anymore at all.

Cant recommend this Program to anyone RN! Its a fking timewaste at best and it wont work like u expect!

**Comment by tazer1** [comment]
Low quality bait. FixURBRAIN
And the reason why it is not working isn't even LBdev's fault for anyone honestly concerned.

**Comment by Geovakaid** [comment]
If it was so hard for you to set it up to begin with then maybe you should just stay away from now on.  You seem like an asshole.
