### ISSUE TITLE
TheCheatsrichter?

### ISSUE THREAD

**Issue by morpheus305** [TheCheatsrichter/Gw2_Launchbuddy#430]
Launchbuddy hasn't received an update since dec 22nd and he has posted anything on here since then as well. Has TheCheatsrichter abandoned the project? I was worried the first time they tried to implement chromium and he didn't respond to any of the posts. Now here we are and still not a word from him.

**Comment by laroxyz** [comment]
His last update was 3 weeks ago, obviously LB is not his main life project, let's just give it time and it will surely solve the current patch problem.

**Comment by FinalRemix** [comment]
He posted on his patreon yesterday that the update has broken more than anticipated, so the LB update is more triage than update, per se.

**Comment by laroxyz** [comment]
yes I saw it, I'm glad he has time to dedicate himself to the software, personally I can take good advantage of it, I've also thought about paying for the patreon version but my native currency is very devalued, who knows in the future I'll pay.
however, just wait and I'm sure he will soon fix the LB free version.

**Comment by exepll** [comment]
so the patreon version works normally?

**Comment by IstvanFranko** [comment]
The version 3.0 Alpha is very slow, but still works for me.

**Comment by tazer1** [comment]
There are older versions that work quite OK, I am now using 2.4.1 as suggested in another thread. I only have to manually press cancel after dat file update (because it updates them fine) and then all logins and mutiboxing works OK, so that's what matters most. Lets just wait for a new stable and working version, better to give it some extra time  as needed for development

**Comment by Qwix005** [comment]
WORKAROUND.  https://github.com/TheCheatsrichter/Gw2_Launchbuddy/releases   I went here. I am using 3.0.3Alpha it takes longer to update the dat files but it is working now.  (I replaced the Launchbuddy exe with the older version. I can swap back or update when a fix is in.)

**Comment by zanagraf** [comment]
follow your exemple, but easily ^^ after cancel the update, i went to the launch buddy setup, view the other realease, and choose to set up back the 3.03 (not alpha) and it work ^^ thanks for your inspiration !

**Comment by Grimleiv** [comment]
You can use this wile waiting for repair. It's pretty much same, easy to setup.. Less errors. Just make one server, clone and edit.. new dat file. One login pr server to same the new dat file.

https://github.com/Healix/Gw2Launcher

**Comment by morpheus305** [comment]
> You can use this wile waiting for repair. It's pretty much same, easy to setup.. Less errors. Just make one server, clone and edit.. new dat file. One login pr server to same the new dat file.
> 
> https://github.com/Healix/Gw2Launcher

Does this have built-in ddos protection system like launchbuddy has?

**Comment by Grimleiv** [comment]
It has a lot of settings. For me i can open more Windows with this without getting errors. There is daily reminder, api support etc. It's a good supplement to launchbuddy if we don't get updates anymore.

**Comment by Grimleiv** [comment]
Still not working. Now it updates, but everytime i start it, it goes through the update.. Even tho ther is no update. Then when i start GW2 clients, Launchbuddy crash often. Guess some testing sttill needed. Sendig bug report.

**Comment by Scijoe** [comment]
Its working fine for me. I had to manually click Login on each account, but i think that might have to do with the last login without LB

**Comment by l4ndl0rd** [comment]
Semi-working for me - loginfile got updated no problem, but when it comes to logging in, it just sits there at the launcher and I have to manually click on "Login" and "Play".

**Comment by Grimleiv** [comment]
Have you tried restart? Every time i restart, all gw2 clients opens. Like when update are needed.

**Comment by laroxyz** [comment]
> Hotfix version 3.2.5 is now available. Please report back if your issues persist

you are my hero

**Comment by morpheus305** [comment]
Login button still needs to be manually clicked for every account. Not sure what's causing it but I have tried lots of ways to fix it and nothing seems to work.
