### ISSUE TITLE
"Loginfile Setup" doesnt let me put my login and passwd,  it closes too fast

### ISSUE THREAD

**Issue by MarvIcNet** [TheCheatsrichter/Gw2_Launchbuddy#433]
**Describe the bug**
I click on "Set Loginfile", Gw2 opens then 3 sec later, without clicking on anything, it closes.
The issue is that I dont have time to put my login and passwd.

**To Reproduce**
Update to 3.2.5.
Click on Account Settings then select a account then click on Set Loginfile

**Expected behavior**
I expect to have time to put login and passwd, then click on Login in order than Gw2buddy save my credentials.

**First happend in LB Version**
Issue first appeared in LB Version : 3.2.5

**Comment by stevey71** [comment]
I have the exact same issue as well.

**Comment by zanagraf** [comment]
Same here

**Comment by Vy-Ro** [comment]
workaround that did it for me, compile the login in the normal launcher, click login , close the launcher and press setlogin file in launchbuddy

**Comment by Vatrez69** [comment]
same here

**Comment by wikiidoo** [comment]
-Login screen still disappears after 3.2.5 hotfix.
-Client will not "auto-login" even after information is saved.

**Comment by mirkotriglav** [comment]
same for me... deleted the appdata folder, still does the same thing.

**Comment by Lisaria28** [comment]
+1

**Comment by Fischersen** [comment]
+1, since April now...
