### ISSUE TITLE
Login button not getting pressed after client is opened

### ISSUE THREAD

**Issue by morpheus305** [TheCheatsrichter/Gw2_Launchbuddy#434]
**Describe the bug**
Login button not getting pressed since last update

**To Reproduce**
Steps to reproduce the behavior: does it every time

**Expected behavior**
Login button should be pressed

**First happend in LB Version**
Issue first appeared in LB Version : latest 3.2.5 hotfix

**Comment by kariella** [comment]
does this happen on all your accounts? I have some accounts this happens on and others it doesnt and I found out that it was the settings used in adding the account...

**Comment by morpheus305** [comment]
Happens on all accounts and started with this latest patch

**Comment by Genimaster** [comment]
Can confirm, this is happening to me too on all accounts.

Issue before that was that there was no time to change the login info before it closed the window. Tried creating new account in it.

Not that I know how your SW is created, but I think you can combine issue 431 to 434 to the same issue in it.

**Comment by Lisaria28** [comment]
Same here.
Login does not work on any account. I tried different settings at setup as well. I have to start every account manually with the login button. As long as not all accounts I've chosen to start are logged in (by hand), they are not shown in the game client selection too.

**Comment by Starmaster1952** [comment]
I am having then same issue have press the log in button on each account. Multi launching only works by pressing log in on each account!

**Comment by morpheus305** [comment]
Hopefully TheCheatsrichter has some free time to take a look at this issue soon. I've tried multiple different settings and such to try to fix it but with no luck. It seems like it's affecting more than just a few people.

**Comment by shibbbbby** [comment]
Same issue here

**Comment by ManniMan** [comment]
There was a workaround with the argument -usecoherent. Since this argument was removed from GW2 game client with the July, 18th update, that workaround is gone now. Seems like the manual press on login button is the only way other than subscribing to the beta version via Patreon.

There is a duplicate issue open as well: https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/431

**Comment by morpheus305** [comment]
> There was a workaround with the argument -usecoherent. Since this argument was removed from GW2 game client with the July, 18th update, that workaround is gone now. Seems like the manual press on login button is the only way other than subscribing to the beta version via Patreon.
> 
> There is a duplicate issue open as well: #431

Is this actually fixed in the Patreon version?

**Comment by ManniMan** [comment]
> 

I'm not sure, but the Patreon site reads that way.
