### ISSUE TITLE
Where is Data Stored?

### ISSUE THREAD

**Issue by Zodiaksl** [TheCheatsrichter/Gw2_Launchbuddy#441]
Hello,

I just switched from my old laptop to a new gaming pc.

I was using Gw2 Launchbuddy 3.2.5Hotfix on the old laptop, which is located on my D:\ drive but it only has a .exe to it. So moving it from the old PC to the New PC didn't transfer any of the login data along it.

Where does Gw2 Launchbuddy save the account info to?

I was trying to add all of my accounts back manually but on the new computer, the login page goes away too fast and I can't enter the email and password for each account.

If I could find the stored data file on my laptop, I could copy that over.

Thank you

**Comment by Skaldhor** [comment]
Hi @Zodiaksl,

the data is stored in "[%Appdata%\Gw2 Launchbuddy](https://github.com/TheCheatsrichter/Gw2_Launchbuddy#:~:text=%25Appdata%25%5CGw2%20Launchbuddy)"

Regards
Skaldhor

**Comment by Zodiaksl** [comment]
Even after copying the old files to the new computer, I am still unable to login to alt accounts. It doesn't save passwords and clicking Edit Loginfile doesn't give enough time before it closes the login window.

I love gw2 launchbuddy but I don't know if it will ever work again :(

**Comment by TheCheatsrichter** [comment]
Hi there! Loginfiles in the past could be copied. So moving over the launchbuddy folder should ahve actually worked. However in the recent months many changes regarding loginfiledata and the login framework have been made. Might be that the logindata is now encrypted with your machines ID --> not transferable. Can you confirm this behavior?
