### ISSUE TITLE
Launchbuddy can run only one client - workarounds not working anymore?

### ISSUE THREAD

**Issue by TenAncymon** [TheCheatsrichter/Gw2_Launchbuddy#442]
**Describe the bug**
Launchbuddy can open only one client at the same time, when I'm trying to open multiple clients, it will open only the first one. 

**To Reproduce**
Just click on more than one account from list and click "launch Guild Wars 2"

**Expected behavior**
LB should run multiple clients.

**First happened in LB Version**
Issue first appeared in LB Version : 3.5.2 hotfix
______________________________________________________________

OK, I found workaround here before (rollback to older LB version and add -usecoherent tag to all accounts) but this is not working anymore (at least in my case). Also, it's not easy to add/update login files, because login window disappears very fast (I'm doing also workaround here, with opening gw2 by official launcher, and typing logins there, to set them for LB loginfile window) - but its another issue and workaround also not working anymore because LB crashes.

I'm tired TBH with all these things - "Patreon" version also working like this, or it's working as intended? 
I'm thinking about Patreon version, but if it has the same issues, I'm not going for it - any Patreons here can tell me something about this?

**Comment by Alimar777** [comment]
I ended up using the 2.4.2 version. It's slow and doesn't have some of the DDOS protection features, but it doesn't cause problems like the newest update. 

Sadly I don't have enough information to help you other than suggest to try older versions.

**Comment by TenAncymon** [comment]
Seems like this project is dead.
Switched to gw2launcher, everything works fine there.
I'm sorry - I was a huge LaunchBuddy enjoyer, but decided to leave 
see you

**Comment by ManiakNL** [comment]
He seems to be updating the project like a few times per month on Patreon
https://www.patreon.com/gw2launchbuddy

Basically putting the project behind a paywall at this point

**Comment by ManiakNL** [comment]
I just gave up on it and move on to [GW2Launcher](https://github.com/Healix/Gw2Launcher). Took a bit of effort to set it up, but now i am actually faster with my daily logins.

**Comment by equinox711** [comment]
> I just gave up on it and move on to [GW2Launcher](https://github.com/Healix/Gw2Launcher). Took a bit of effort to set it up, but now i am actually faster with my daily logins.

Sadly, I've just done the same. GW2Launcher is just much smmother and easier to use nowadays.
