### ISSUE TITLE
doesn't work, can't setup loginfile

### ISSUE THREAD

**Issue by glycoslave** [TheCheatsrichter/Gw2_Launchbuddy#443]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**First happend in LB Version**
Issue first appeared in LB Version : 0.0.0

**Screenshots**

**Comment by glycoslave** [comment]
can't setup LB from clean. 

repro:
- fresh install of latest LB, GW2 client updated to latest, no APPDATA directory for LB. 

- add new account, rename it, click set loginfile, game launch window appears but is auto-closed by LB 2 seconds later, can;t edit the account name or passwork.

expected:
- window stays open to allow account/passwork to be set.

**Comment by Fischersen** [comment]
Same Problem...

**Comment by glycoslave** [comment]
moreover, when i launch GW2, it always opens with my main GW2 account, even if i edit the account name/password to be the one i actually want, ie: account name/password are not persisted.

ie: blocker level bug.

**Comment by Valinor2439** [comment]
Bug temporary solution

step one -
Open gw2, put password and password and press to log in remember to mark save in both fields, open the game or not, it's your preference


step 2

open gw2launcher create an account and click on set loginfile for it to create the login that is saved in the gw2 launcher, ready the alt account is saved

step 3, repeat step 1 and 2 with another account and so on until you save all your accounts
