### ISSUE TITLE
Login file creation not working on 3.2.5

### ISSUE THREAD

**Issue by Xavicrist** [TheCheatsrichter/Gw2_Launchbuddy#444]
Can only set 1 login file.

Create new login file, GW2 windows popups and inmediatly closes, and it seems it gets configured with the first login profile already set up

You should be able to create different login accounts/login profiles

3.2.5

**Comment by Evgenin7** [comment]
Yes, it is...

**Comment by ManiakNL** [comment]
He seems to be updating the project like a few times per month on Patreon
https://www.patreon.com/gw2launchbuddy

Basically putting the project behind a paywall at this point

**Comment by Evgenin7** [comment]
If he can't answer to any of the 30 opened topics for problems with the public version, no one will pay for not working and unsupported spaghetti software. The public release is so broken it is unusable -  3 months the auto login is broken, multiboxing is broken as well. Already moved to the better alternative then the public version, I loved his program before he abandoned the public project. I will check his program again when he releases something to the public until then, alternatives are superior in every way - they work.

**Comment by ManiakNL** [comment]
yeah same here, his patreon count did go up by quite a bit though, I doubt seeing him updating the public version anytime soon.

Out of curiosity, what software are you using now?

**Comment by Valinor2439** [comment]
Bug temporary solution

step one -
Open gw2, put password and password and press to log in remember to mark save in both fields, open the game or not, it's your preference


step 2

open gw2launcher create an account and click on set loginfile for it to create the login that is saved in the gw2 launcher, ready the alt account is saved

step 3, repeat step 1 and 2 with another account and so on until you save all your accounts

**Comment by mirkotriglav** [comment]
Yes, unfortunately, it's dead. The DEV decided to develop updates behind paywall. Not that I can't understand his motives.

**Comment by mirkotriglav** [comment]
> If he can't answer to any of the 30 opened topics for problems with the public version, no one will pay for not working and unsupported spaghetti software. The public release is so broken it is unusable - 3 months the auto login is broken, multiboxing is broken as well. Already moved to the better alternative then the public version, I loved his program before he abandoned the public project. I will check his program again when he releases something to the public until then, alternatives are superior in every way - they work.

What alternatives?

**Comment by TheCheatsrichter** [comment]
Second loop of fixes is now live in V 3.2.6 please keep me updated on your status
