### ISSUE TITLE
v3.2.5. Injected Software Not Working

### ISSUE THREAD

**Issue by AEsylum** [TheCheatsrichter/Gw2_Launchbuddy#445]
Finally decided to try out the hotfix build despite the multiple bugs reported. Turns out able to update the game and launch multiple clients pretty smoothly. But then found that it's not loading the injected software correctly. My Reshade just refuses to load no matter what I try (including just launching 1 client). Reverted to v3.0.3, though it's very buggy and slow when the game has updates, at least everything else still works correctly.

Another disappointing release, becoming a trend lately after years of stability.

**Comment by TheCheatsrichter** [comment]
Second loop of fixes is now live in V 3.2.6 please keep me updated on your status

**Comment by AEsylum** [comment]
Hi,

Thanks for the notification but the 3.2.6 still doesn't work with the injected software.

Regards,
________________________________
