### ISSUE TITLE
Still can't set login files.

### ISSUE THREAD

**Issue by Mythykle-Mythryndyr-Fs** [TheCheatsrichter/Gw2_Launchbuddy#447]
Login files still can't be set cause they still close instantly before you get a chance. :(

**Comment by ibuljeta** [comment]
Same here.
Tedious, but available workaround is to start the client normally, add login info and login (maybe login is not required, but haven't tested), exit client/launcher, create a new profile, and hit "set loginfile". It will close automatically after a few seconds, but will work. Just an advice if you go this way, monitor profile creation as every once in a while, username field is not populated when "set loginfile" is pressed and then you need just to re-click to recreate it.

**Comment by Mythykle-Mythryndyr-Fs** [comment]
Yeah nah, this does not work as you said, It didn't work before the last update either.
Especially if you have more than 1 client and the one that is not working is not your main account.

**Comment by ManiakNL** [comment]
The author of the plugin does not seem to be interested in updating this application.
Perhaps you can try and see if GW2Launcher suits your needs.
