### ISSUE TITLE
Launchbuddy still not launching with update 3.2.6

### ISSUE THREAD

**Issue by Flapjakk** [TheCheatsrichter/Gw2_Launchbuddy#448]
Same behavior as before the update (see https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/436). Launchbuddy won't launch the game, it just sits on the game's launcher window.

```
**Describe the bug**
Launchbuddy doesn't launch the game. Have to manually press "login" and "play" on the game's launcher window.

**To Reproduce**
Start launchbuddy 3.2.5. Select one or many accounts, click "Launch Guild Wars 2" on the launchbuddy window.

**Expected behavior**
The game to launch without the user manually interacting with the gw2 launcher.

**First happend in LB Version**
Issue first appeared in LB Version : 3.2.5
```

**Comment by Alimar777** [comment]
Same issue here, It will only launch one client at a time and every time I have to manually log in. I've resorted to using 2.4.2 release since it seems to work.

**Comment by maconho** [comment]
Same here. All broken. Only 2.4.2 working now that -usecoherent stop working from the game side.

**Comment by ManiakNL** [comment]
The author of the plugin does not seem to be interested in updating this application.
Perhaps you can try and see if GW2Launcher suits your needs.

**Comment by Flapjakk** [comment]
> The author of the plugin does not seem to be interested in updating this application. Perhaps you can try and see if GW2Launcher suits your needs.

Well the version number updated a week ago, and github shows some kind of change yesterday. So he's poking around. 

But you're right: The thing's been broken for months now. Without any acknowledgement or communication, it does seem like the author is just uninterested.

**Comment by ManiakNL** [comment]
> > The author of the plugin does not seem to be interested in updating this application. Perhaps you can try and see if GW2Launcher suits your needs.
> 
> Well the version number updated a week ago, and github shows some kind of change yesterday. So he's poking around.
> 
> But you're right: The thing's been broken for months now. Without any acknowledgement or communication, it does seem like the author is just uninterested.

I checked the latest commits, and he just added some hashes over the last months.

I think he now fully foccusses now on the paid version of his software (patreon)

**Comment by Flapjakk** [comment]
Wonder how he expects to convert free users to buyers with a constantly broken and ignored product.
