### ISSUE TITLE
PProtection.cs and ScreenAnalyser.cs are missing in repo

### ISSUE THREAD

**Issue by ManniMan** [TheCheatsrichter/Gw2_Launchbuddy#449]
**Describe the bug**
I wanted to check, if I can contribute to the current login button issue, but two files in the repo are missing:
PProtection.cs and ScreenAnalyser.cs
I don´t know, if this was just not commited or if this is intentional.

Issue appeared in LB Version : 3.2.6

**Comment by ManiakNL** [comment]
The author of the plugin does not seem to be interested in updating this application.
Perhaps you can try and see if GW2Launcher suits your needs.
