### ISSUE TITLE
Code Refactor

### ISSUE THREAD

**Issue by KairuByte** [TheCheatsrichter/Gw2_Launchbuddy#45]
We have a large amount of logic tied directly into the main window of the application. We also have object classes scattered in different places, as well as static classes.

Object classes and logic related to that object should be moved into their own file. Most logic needs to be pulled out of MainWindow to facilitate shortcut functionality, as the code does not always function as expected if we simply create the mainwindow object and never fully initialize it.

**Comment by KairuByte** [comment]
Pulled external branch into new internal branch: https://github.com/TheCheatsrichter/Gw2_Launchbuddy/tree/refactor

Testing would be great, as I touched a large amount of the code. While things seem to work for me there's likely something I have not tried.

**Comment by TheCheatsrichter** [comment]
Merged since release 1.6
