### ISSUE TITLE
Suggestion: Setting to suspend client after start up

### ISSUE THREAD

**Issue by xNaii** [TheCheatsrichter/Gw2_Launchbuddy#450]
Would love to have an option to suspend client after start up automatically without need of hot-key for each client running
That way it keeps CPU usage low.

Currently have to suspend each client separately or launch 1 by 1

**Comment by ManiakNL** [comment]
The author of this plugin does not seem to update the free version anymore. Best to checkout GW2Launcher.

It has the option to limit the amount of running instances to reduce load.
It also has the option to only allow the next instance to start  when the main window is loaded.
