### ISSUE TITLE
Background musics

### ISSUE THREAD

**Issue by Brendead** [TheCheatsrichter/Gw2_Launchbuddy#453]
hi, launchbuddy allow us to change the background music when you are in the lobby. My problem is that i can't delete the musics that a put before and now they are playing even when i'm on the anet launcher and  i don't have the new musics of the extension

can you help me please 

ty

**Comment by Brendead** [comment]
i deleted all the launchbuddy files and now just the old selection caracter song is playing non stop

**Comment by Ryu-Pendragon** [comment]
Delete Launchbuddy and download gw2 launcher it way better and free... i think the patreon version of launchbuddy is the only one who work i guess cause you have to paid ... the free version is completly abandoned ....

**Comment by Brendead** [comment]
yes but how can i delete the music in the lobby. the one that i add with launchbuddy

**Comment by Brendead** [comment]
no more help ?
