### ISSUE TITLE
3.2.6 broken as of Jan 11, 2024

### ISSUE THREAD

**Issue by AEsylum** [TheCheatsrichter/Gw2_Launchbuddy#455]
Keep getting this error message. Using older versions doesn't help.

![image](https://github.com/TheCheatsrichter/Gw2_Launchbuddy/assets/82086629/2d1aa696-29ba-44e3-aa70-b1659361c8f2)

**Comment by gormleymark** [comment]
@AEsylum  Did you find a fix? Mine has been like this since yesterday

**Comment by AEsylum** [comment]
> @AEsylum Did you find a fix? Mine has been like this since yesterday

No. And the developer has gone completely unresponsive. I've abandoned this and switched to Healix's GW2Launcher. It has a much steeper learning curve with a less friendly UI but once you've learned exactly how to use it, it's a lot more powerful and definitely better supported than LaunchBuddy.

**Comment by Drogon1234** [comment]
Would definitely recommend Healix Launcher. It doesn't break after every single patch. The dev for this launcher now only seems to release new builds to his patreons...

**Comment by Toluk** [comment]
2.4.1 kinda still works on win10

**Comment by gormleymark** [comment]
I've since moved to GW2 launcher
