### ISSUE TITLE
Use non-listed assetserver & login feedback

### ISSUE THREAD

**Issue by SeparGW2** [TheCheatsrichter/Gw2_Launchbuddy#49]
GW2 LaunchBuddy (v1.42) is a very nifty tool. It has allowed me to run multiple copies without having to use various batch files to get online with more than one GW2 instance.  

I have found an area that would improve the user experience.  I would like LaunchBuddy to be able to store and use an manually entered assetservers.  

I currently cannot run GW2, due to continuous connection errors, unless I follow the advice of the following 2-year-old forum post:
https://forum-en.guildwars2.com/forum/support/support/Connection-error-s-detected-Retrying-100/first#post5016682 which contains a post from a dev (Chris Cleary) which says: ...

    If you are still having (connection) problems, try adding this to your GW2 Shortcut Target:

    -assetsrv 62.154.232.187:80

    Here is a list of alternatives to also try:
    194.25.94.170:80
    174.35.71.9:80
    151.249.90.199:80
    93.188.135.37:80
    62.154.232.194:80

The only assetserver currently visible to me in the LB Server selection tab is 174.35.56.164 (ping 0).  When I select in LB and specify an account then attempt to start the game...I do not connect and there is no error message from LB.  When I edit a GW2 shortcut with that assetsvr argument, I see connection errors.    

I then edited a GW2 shortcut to include -assetsrv 174.35.71.9:80 (picked randomly from the list) and now have no problems connecting, but cannot use LB for that assetserver since it is not available.  

For a future update please modify LB to include the above listed assetservers and allow additional ones to be added.  Also please let it provide feedback during login to alert us of any problems found during the login process.

**Comment by KairuByte** [comment]
I'll have a look when I can but I would have sworn you could manually enter an IP in LB after changing your servers. 

I can say it will be easy to add custom servers to the list, but I don't believe it is currently possible to save that selection in any way. I'm actually not sure that saving the selection would be the best idea either, since you may want to use it only temporarily.

**Comment by TheCheatsrichter** [comment]
Inlcuded in V1.5. Further saving/loading of servers will be in a future release.
