### ISSUE TITLE
launch buddy use with arcdps + ReShade

### ISSUE THREAD

**Issue by jacob-keller** [TheCheatsrichter/Gw2_Launchbuddy#53]
If a user wishes to use GW2 Launch Buddy while using arcdps, it seems that you have to put the arcdps d3d9.dll into the main folder (Program Files\Guild Wars 2) instead of in the bin64 directory.

I'm not certain why this occurs but i think it has to do with what directory the gw2-64.exe is launched in, as it now uses the main directory as a search path.

This is normally ok, users are just aware to put a copy of the arcdps (or any other added) into the main dir instead. This causes a few problems however.

First, it means the user has to have two copies of the d3d9.dll incase they launch the game client directly.

Second, more importantly, it prevents chain loading into ReShade. This is because ReShade does not load properly if d3d9.dll is in the main directory (also not completely certain yet why this occurs).

Essentially, arcdps will load a chainloader for d3d9.dll which then loads ReShade64.dll. However, ReShade64.dll will not load because it finds the d3d9.dll file in the top level and exits.

Since we need the d3d9.dll in the top level to use launch buddy, this prevents the user from being able to use arcpds with ReShade. Additionally, after the ReShade fails to load, arcdps itself doesn't finish loading and you end up getting neither addon working correctly.

I believe the fault is that launchbuddy changes the load path. Alternatively it may be ReShade code which fails to load when a d3d9.dll is in the top level directory, but I'm unsure how to fix either of these issues.

**Comment by jacob-keller** [comment]
[ReShade64.log.txt](https://github.com/TheCheatsrichter/Gw2_Launchbuddy/files/1294881/ReShade64.log.txt)

There's a copy of the ReShade64 log after loading with d3d9.dll in the top level,

[ReShade64.log.txt](https://github.com/TheCheatsrichter/Gw2_Launchbuddy/files/1294887/ReShade64.log.txt)

Followed by a copy of the log if I rename d3d9.dll in the top level to something else (obviously launched without launch buddy in this case).

**Comment by jacob-keller** [comment]
Based on a cursory reading of the ReShade64 code, it appears that when ReShade64.dll is loading, it finds the d3d9.dll in the path so when it finally goes to load the real d3d9.dll it accidentally tries to run the copy found at the top level of the gw2 folder, which in this case isn't a valid d3d9.dll and then it fails to finish loading. and falls apart.

I don't think we can really fix this in ReShade itself.

**Comment by KairuByte** [comment]
There are two distinct problems each with an individual cause, though they are only seen in tandem. 

The first is that when you run the client with auto login, you need to use the -nopatchui flag. For some reason this flag sets the load directory to the root of the game folder instead of the intended bin folder. There is no way to fix this without either a client update or dll injection (which I am confident will never happen through LB). 

The second problem is in Reshade itself. I have never found the root cause of the crash, but something about the way -nopatchui loads the game causes Reshade to bomb. While Reshade is open source, I am not familiar enough with its code base to attempt to debug. Though I believe I submitted an issue to the Reshade github page. 

At this point, there's really not much to be done except bug the parties capable of making the changes.

**Comment by jacob-keller** [comment]
Actually, I wonder..... So when you launch the game with patchui, it then after patching proceeds to launch the game in bin64 folder...

With "-nopatchui" I bet that the game just lauches in the folder it originally was in (the regular directory).


What about adding a "launch in" path so that it launches in bin64 directly instead, when running with nopatchui? I suspect that the nopatchui code just doesnt' change dir, and if you force it to start within the bin64 directory it would work fine?

Essentially, at

https://github.com/TheCheatsrichter/Gw2_Launchbuddy/blob/8285f0e435959f735f8ba3dfb3a81db43984f77f/Gw2%20Launchbuddy/ApplicationManager.cs#L119

What if you set the working directory to the bin64 path instead of working directory (but only when launching with nopatchui)?

**Comment by jacob-keller** [comment]
Maybe something like https://github.com/TheCheatsrichter/Gw2_Launchbuddy/pull/54

**Comment by jacob-keller** [comment]
Unfortunately @KairuByte is right, and changing the launch directory did not fix the issue (probably due to how the game launches itself). This means the only alternative fix besides changing the gw2 client is in fixing ReShade's crash.
