### ISSUE TITLE
setting up Reshader

### ISSUE THREAD

**Issue by leogono** [TheCheatsrichter/Gw2_Launchbuddy#58]
Does anybody know any guide on how to setup reshader with Launchbuddy? I can see the option but don't know which files to download.

**Comment by KairuByte** [comment]
Latest reshade versions are broken with LaunchBuddy. There is something that causes reshade to crash and unload immediately after it's initial load. See also #42.

**Comment by KairuByte** [comment]
Duplicate of #42

**Comment by leogono** [comment]
Thanks. I did not know you can add the .dll on the root folder. 👍 it's working now.
