### ISSUE TITLE
UI missing mouse hover tooltips

### ISSUE THREAD

**Issue by icy-** [TheCheatsrichter/Gw2_Launchbuddy#59]
[feature request]   Hi, I'm trying out LaunchBuddy for the first time, and I find some of the custom icons difficult to predict.  Can you please add tooltips on mouse hover?  Examples:

- main UI top right corner ("Cinema Mode" located at the "minimize window" location)
- GW2 Instances window icons.  Some of these clicks have a very forceful effect!
- probably unrelated, but in general no warning popups for extreme actions like killing windows (Are you sure you want to close Launch Buddy? etc.)  Will clicking X on main UI window close all instances too? 

thanks

**Comment by TheCheatsrichter** [comment]
Added popups to most of the laucnhbuddy buttons etc in 1.6. Still not perfect.
