### ISSUE TITLE
Obscure Email Address

### ISSUE THREAD

**Issue by vipero07** [TheCheatsrichter/Gw2_Launchbuddy#6]
Because of the availability of nicknames it would be best to have the email addresses obscured.

The way I would do it is have an edit button that when you click has a popup that allows you to change the email and password. This way the total number of characters of the password wouldn't be easy to determine, and the email wouldn't be plainly visible.

**Comment by KairuByte** [comment]
I would actually make the suggestion of removing them completely from the UI and only showing the Account Name (I am working on API integration) or the Nickname. This way the account information, including API key, can be hidden off in a settings pannel.

I would also argue that the password field does not need to be shown at all in the UI, apart from adding/editing the account credentials.

**Comment by vipero07** [comment]
Yes... That's exactly why I suggested putting them in a pop-up that only
shows when you click edit next to the nickname...

**Comment by KairuByte** [comment]
I apologize, I misread your post.

**Comment by TheCheatsrichter** [comment]
I allready fixed this on my newer build. Atm commiting to the project is really not the best moment as I develop the app on the run with my laptop -> no internet. But thanks for the support!

**Comment by KairuByte** [comment]
Reopening as this appears to have regressed. Will address during refactor cleanup.

**Comment by TheCheatsrichter** [comment]
Fixed with 1.6
