### ISSUE TITLE
Request: Option to disable -nopatchui

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [TheCheatsrichter/Gw2_Launchbuddy#60]
Right now -nopatchui is preventing programs such as ReShade 3.0+, GW2Hook, and even ArcDPS from running properly.  If given the ability to disable -nopatchui .. this might help to get other 3rd party programs working properly with GW2 that can't be used with LaunchBuddy currently.

**Comment by Artanis** [comment]
https://wiki.guildwars2.com/wiki/Command_line_arguments#-nopatchui

The `-email` and `-password` options require `-nopatchui` flag to be set to function.

**Comment by KairuByte** [comment]
Launching without auto login options should start without -nopatchui

**Comment by SaiyanOfDarkness** [comment]
Well the point of having it is so that it would autofill the gw2 launcher, but unfortunately.. the only way I can see that happening is if some how launchbuddy would know how to properly edit the local.dat file to put in the email and password before loading the game.

**Comment by KairuByte** [comment]
local.dat is encrypted pretty strongly. No one has been able to reverse engineer the encryption process, and the moment a tool like launchbuddy is released with a way to mimic the encryption it would likely result in the encryption being changed almost immediately. 

At least for the foreseeable future local.dat is out of the running. 

A much slower alternative would be to simulate keyboard interaction to type the account and password out, but that has other drawbacks such as a lack of security. 

That said, all tools I know of work properly with -nopatchui except Reshade, which worked in a previous version. Your best bet would be to talk to the creator and ask them to fix the problem.

**Comment by SaiyanOfDarkness** [comment]
That might be a little difficult as the creator has been MIA for 4 months.  They do however have a github, but no place to report issues..

https://04348.github.io/Gw2Hook/

**Comment by SaiyanOfDarkness** [comment]
`That said, all tools I know of work properly with -nopatchui `

Alright, I put ArcDPS in the bin64 folder like they instruct, loaded gw2 with launchbuddy.. arcdps isn't working?

**Comment by hasosoft** [comment]
see https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/42#issuecomment-320530426

**Comment by KairuByte** [comment]
Closing as non LB.
