### ISSUE TITLE
Launchbuddy issues with McaFee & Webroot

### ISSUE THREAD

**Issue by DougSands** [TheCheatsrichter/Gw2_Launchbuddy#62]
Hi -- Tried to download 1.5.1 and both of these apps, Webroot and Mcafee, flag GW2_Launchbuddy as a bad actor. I went to this site and while there is a link for 1.5.2, nothing downloads from it. I thought you folks should know.
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/releases/tag/1.5.2

**Comment by TimothyVandenbrande** [comment]
Duplicate of https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/56

**Comment by KairuByte** [comment]
Closing as dupe of #56 (As noted by @TimothyVandenbrande)
