### ISSUE TITLE
Value assignment instead of comparison typo

### ISSUE THREAD

**Issue by Kaukov** [TheCheatsrichter/Gw2_Launchbuddy#65]
This should be double equals instead of single.

https://github.com/TheCheatsrichter/Gw2_Launchbuddy/blob/924c90947a4abe4a9b166f1b3828f28858891630/Gw2%20Launchbuddy/ObjectManagers/ClientManager.cs#L291

**Comment by KairuByte** [comment]
Ah, good catch! I admit I almost never run without the debug flag.

**Comment by TheCheatsrichter** [comment]
Fixed in 1.6
