### ISSUE TITLE
SerializationException occurs when program opened

### ISSUE THREAD

**Issue by ErikHumphrey** [TheCheatsrichter/Gw2_Launchbuddy#67]
Launching the program (1.6.0) only makes a window appear saying:

>The ObjectManager found an invalid number of fixups. This usually indicates a problem in the Formatter

Once dismissed, the program closes.

**Comment by SaiyanOfDarkness** [comment]
This is due to the fact that versions below 1.6 cannot transfer account information over to the current version.  You have to input the logins and passwords manually.  You shouldn't see this error again at least?

**Comment by ErikHumphrey** [comment]
Hmm. Where's the existing data stored so I can delete it?

**Comment by TheCheatsrichter** [comment]
The existing data will be overwritten automatically once this error pops up. So you actually hven't to do anything. A simple relaunch will fix it. :)

**Comment by ErikHumphrey** [comment]
I tried relaunching it before creating the issue, but the error still popped up every time. I've since deleted everything on the system related to Launchbuddy and redownloaded it, but now the program just runs for a few seconds (nothing opens) and then closes silently.

**Comment by KairuByte** [comment]
Can you see what deleting "%APPDATA%\Guild Wars 2\Launchbuddy.bin" does?

**Comment by ErikHumphrey** [comment]
Sorry, forgot to submit my comment to this. Launchbuddy.bin was one of the first things I deleted. It is not generated on opening the program anymore. I'll see if manually compiling the program works.

**Comment by ErikHumphrey** [comment]
Manually compiling made LaunchBuddy start successfully, but it's worth noting that it can't be built without copying TestPlugin.dll to `Gw2_Launchbuddy\TestPlugin\bin\Debug\TestPlugin.dll`.

**Comment by KairuByte** [comment]
I fixed the compile problem in a commit today.
You can also try moving the compiled launchbuddy off on it's own, or just remove the plugin from the folder with it.

**Comment by TheCheatsrichter** [comment]
Binary Data is no longer used.
