### ISSUE TITLE
1.6.0 - Disable splash window

### ISSUE THREAD

**Issue by ccp6128** [TheCheatsrichter/Gw2_Launchbuddy#68]
Hi,

While launching the Autologin / Multiboxing feature, the "always on top" splash window that appears while Launchbuddy is starting the multiple copies of the games is more of a bother than a feature :

- If Launchbuddy fails to start even one instance, it'll stay forever, taking a good chunk of screen space for nothing.
- Even if it works, it still uses a ton of screen space while starting, which in my case (I'm starting the games full screen) prevents me to do anything until every instance of the game is started.

The splash window should be at least an optional feature, or not be set as "always on top"

**Comment by TheCheatsrichter** [comment]
Added a CheckBox in the LB Settings Tab (1.6.2)
