### ISSUE TITLE
1.6.x - cannot autologin when passwords have spaces 

### ISSUE THREAD

**Issue by wohali** [TheCheatsrichter/Gw2_Launchbuddy#69]
Confirmed with 2 different people and 2 different accounts - works fine with accounts that have no spaces in their passwords.

Accounts that have spaces in the password sit on a white screen (fullscreen windowed is how I run GW2) and never make it to character select. ALT-F4 shows evidence of the password, past the first word, in the debug log:

```
Cmdline: -maploadinfo -shareArchive -nopatchui -email myaddress@somewhere.com -password ******* REST OF PASSWORD HERE
```

**Comment by KairuByte** [comment]
This has been corrected in a recent commit. There is a workaround though, in case you want to continue to use spaces in your password but do not have the ability to compile latest. Simply input your password as normal, but surround it in double quotes "like so".
