### ISSUE TITLE
Suggestion: less chrome and compatibility with Gw2Hook

### ISSUE THREAD

**Issue by ToyinB** [TheCheatsrichter/Gw2_Launchbuddy#70]
Hello,

Excellent tool.

Could you please add an option to turn off the black skin for 'Game Instances' so I can just put the options to the side and not have it overlap my UI?

Compatibility with Gw2Hook would be appreciated. I understand this may be quite difficult though.

**Comment by KairuByte** [comment]
Gw2Hook is already compatible FYI, even before v1.7 which introduced an injection system.
