### ISSUE TITLE
Launchbuddy Alpha 1.6.1 treated as having Malware

### ISSUE THREAD

**Issue by ReportAnIssue** [TheCheatsrichter/Gw2_Launchbuddy#72]
My antivirus software (Vipre) has removed GW2Launchbuddy 1.6.1 exe from my system and won't allow the exe to be down loaded from the site. It is identifying it as Gen:Variant.Razy.348320.

**Comment by samuliHeikkinen** [comment]
My antivirus did the same (F-Secure). The 1.6.1 Hotfix version was running fine, but this morning when I opened the pc anti-virus just informed that it has found a trojan and removed it. Redownload does not solve the issue. Identified as same virus Gen:Variant.Razy.348320.

**Comment by t-v** [comment]
It is kind of being discussed in this issue too: https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/56
But I don't think it's currently a priority. I keep following the thread, but no real changes happen to the whole malware thread. So yeah, assume security is not a priority in their current roadmap.

**Comment by KairuByte** [comment]
I'm closing this out. #56 has the full details on why, but I'll point out here that anything with the word/phrase/partial of "Gen" is a generic, non specific, "might be but isn't for sure" detection. It's literally the virus scanner saying "We don't know what this is, but it has code parts that could be used for nefarious deeds". It's in no way a reflection of the security of LB itself. For that, I would suggest either yourselves (or someone you know that understands the code if you don't) look through the code, and make the determination.
