### ISSUE TITLE
2.1.5 - UI Size setting getting overwritten on every game launch

### ISSUE THREAD

**Issue by oranisagu** [TheCheatsrichter/Gw2_Launchbuddy#73]
### Problem:
~~The graphics options are applied on every start and since the interface size option is not configurable, it always gets reset to normal.~~

After looking at the XML I saw the interface size wasn't set in that XML. When not using LB I was able to normally change my games option and have them saved after shutdown. As soon as I used LB again, my ingame options don't seem to get saved (i.e. sound levels). So my initial interpretation was way off, but something with using LB seems to cause problems for the game and some options don't save reliably anymore.

I start both the game and LB with user privileges, so at this point I can't really say what the underlying issue is.

**Comment by watlok** [comment]
UI size is set in the loginfile. Steps to reproduce and confirm this finding:

1. Set UI size to larger in guild wars
2. Set Loginfile by logging in
3. Launch with launchbuddy to confirm it's larger
4. Close, launch with normal launcher
5. Set to normal
6. close, relaunch with normal launcher (it's normal still)
7. close, relaunch with launch buddy (it's larger)

Just figured this out because it was driving me insane.

**Comment by TheCheatsrichter** [comment]
This might be a sideeffect of using command line arguments. Sideeffects of using specific command line arguments aren't very well documented on the wiki and have to be tested on our own...

**Comment by WKMEG** [comment]
> If you want to quickly update all of your accounts:
> 
>     1. Open guild wars 2 normally with one account, set ui size, close it
> 
>     2. Go through each account in launchbuddy and hit "set loginfile"
> 
> 
> You'll need to enter credentials, but each one will have an updated UI size. Real GW2 only needs to be launched once even if you are updating many accounts. Certain other settings, like sound settings, can also be updated this way.

I tired this and the UI size and position did not change. Is there a newer update on how to do this?
