### ISSUE TITLE
tackling real splitscreen

### ISSUE THREAD

**Issue by maxMel1** [TheCheatsrichter/Gw2_Launchbuddy#74]
Are  -AlwaysFocus and  -ControllerOffset=1 possible (accepted) commands for batch file or Launchbuddy?

**Comment by KairuByte** [comment]
While this is possible in the future, (@TheCheatsrichter can weigh in and sway this as well of course) I don't see this happening any time soon... This would likely be something for a plugin, which are planned to have more capabilities in a future version.
