### ISSUE TITLE
[Alpha 1.6.1] ConfigurationPath is ignored/overwritten

### ISSUE THREAD

**Issue by Invisi** [TheCheatsrichter/Gw2_Launchbuddy#78]
In the current v1.6.1 the Account's ConfigurationPath is overwritten if the Account doesn't match the AccountManager's DefaultAccount (See [here](https://github.com/TheCheatsrichter/Gw2_Launchbuddy/blob/master/Gw2%20Launchbuddy/ObjectManagers/ClientManager.cs#L262)).
This got introduced in 569cb6c4e319b780fc194c80cf1ff0621c1cdfaa and despite its age doesn't seem to affect v1.5.3.
Without it LaunchBuddy seems to work fine however I haven't checked whether the command line arguments are impacted in any way.

Cheers,
~Invisi

**Comment by KairuByte** [comment]
I.... honestly have no idea why that is there. It looks like I potentially stubbed out a basic account creation when I was working on DefaultAccount for simplicity, and forgot to remove it when it was no longer needed.

Good catch. I've corrected this in the latest commit.
