### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by ReonBalisty** [TheCheatsrichter/Gw2_Launchbuddy#8]
Recently downloaded, ran the clear app data, and clear bin. 
Settings set while using launcher will not stick.
Have to set my display to windows full screen, larger text each log in, will do these settings outside of launcher later today, but while launcher is on, these setting sill not be permanently set.

**Comment by KairuByte** [comment]
Which settings are you speaking about? Do you mean graphical settings within Guild Wars (F11), or settings in the launcher?

**Comment by ReonBalisty** [comment]
F11 while launched through the launcher exe. It will not save the current settings wherever it should be saving them. Had to reset my display to windowed fullscreen and display to larger text and icons as well as music to 0.

**Comment by KairuByte** [comment]
This may just be the expected behavior of the client not holding the mutex... Or local.dat being read only. As far as I know these settings should not be effected by anything the launcher is doing. If they are stored in local.dat it may be because the file is in a read only state.

**Comment by ReonBalisty** [comment]
Settings will stick when not running launch buddy, so recommend resetting the F11 settings outside of the launch buddy environment and then closing and reopening with launch buddy, once have preferred settings have been set.

**Comment by KairuByte** [comment]
Indeed, this will be the ultimate solution for now. It _may_ be possible to allow those settings to be set by the launcher at some point, but if the game currently has problems saving them it may be best to not allow the game to change the settings even if I find it is possible, otherwise oddities may arise.

**Comment by TheCheatsrichter** [comment]
Version 1.4 of Launchbuddy features a GFX setting feature which lets you switch the graphic settings in launchbuddy itself. Further testing will see if this also fixed this bug.
