### ISSUE TITLE
Handle check doesn't work on Windows 10 Pro 64-bit (1803)

### ISSUE THREAD

**Issue by CanisHelix** [TheCheatsrichter/Gw2_Launchbuddy#80]
On Windows 10 64bit, 1803, LaunchBuddy fails to kill the handles at all. It actually appears that the Handle -> Name decode is failing.

When debugging this myself, I found that `name` at [https://github.com/TheCheatsrichter/Gw2_Launchbuddy/blob/master/Gw2%20Launchbuddy/HandleManager.cs#L283](https://github.com/TheCheatsrichter/Gw2_Launchbuddy/blob/master/Gw2%20Launchbuddy/HandleManager.cs#L283) was returning seemingly random data. The handleName was either truncated, or the combination of bytes read matched up with Chinese Kanji instead.

This is most likely why it's failing for me, but I'm not an expert on Win32 Handles to be able to resolve that problem.

For myself, I changed the code on my local version to utilize SysInsternals' handle.exe (handle64.exe specifically) to kill the mutex. This requires me to Run as Administrator, not ideal, but it's okay for my local one until this can be fixed.

**Comment by KairuByte** [comment]
This is quite odd to me actually. So the handle was returning, but was always random (never the same) or random and consistent?

Out of curiosity, is this the Chinese version of the client? I only ask because you mentioned Chinese Kanji.

**Comment by ShiroiKuma** [comment]
I actually used the English NA version of the client. From what I could tell, the handle was always returning, but could never be decoded and so it never match it. With over 1,000,000 handles open it takes a very long time to F10 step-through them all.

I am willing to submit dxdiag files if that would help the cause (maybe a certain build of windows etc...)
