### ISSUE TITLE
[Request Feature] Manual Kill Mutex Button

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [TheCheatsrichter/Gw2_Launchbuddy#81]
Basically title.  Sometimes I get the "Already running" error.  So I think if LaunchBuddy had a built in button to manually kill off the Mutex  instead of me needing to do it through Process Explorer.  This would save a ton of time.  I know LaunchBuddy is supposed to kill of the Mutex automatically, but sometimes it bugs out.  So I think having this button would help with that when these rng bugs occur.

**Comment by SaiyanOfDarkness** [comment]
I was thinking, maybe it would be better if LB could work with [Handle](https://docs.microsoft.com/en-us/sysinternals/downloads/handle).  And then the Manual Kill Mutex button would run a script that triggers Handle to close the Mutex.  Since LB is not always smooth in terms of killing mutex off and bugs out sometimes.

**Comment by KairuByte** [comment]
Handle requires running as admin, which is actually how I got involved with LB to begin with. Running as admin isn’t a solution in my mind, it’s a design flaw...

That said, I’ve been working on the problem a bit recently and am hoping to have a better way to handle the mutex soon.

**Comment by KairuByte** [comment]
Short term, would running LB with a command line option work? I'm horrible at UI and @TheCheatsrichter is focused on 1.8 UI. I could make it something simple like LaunchBuddy.exe -s --killmutex

**Comment by KairuByte** [comment]
Actually, I took a look at this and with the way the code is laid out in 1.7 it doesn't make sense to try to rearrange to get a proper kill mutex going from LB on startup. But yes that's what I was thinking, just killing the mutex on any process named whatever the main client is named. Ran into too many problems trying to fully implement it though. I'll see about working it into 1.8, which decouples a lot of the code from the previous coupling points that makes this more difficult.

**Comment by SaiyanOfDarkness** [comment]
Speaking of 1.8, thought I'd ask here.  Is there going to be an account import option on 1.8, or is that still being worked on?  I ask because I have at least 35 accounts to add, and doing them manually takes a long time.  Especially when LB's encryption updates, and doesn't keep the previous saved info when changing versions.
