### ISSUE TITLE
Use symbolic links for Local.dat

### ISSUE THREAD

**Issue by Archomeda** [TheCheatsrichter/Gw2_Launchbuddy#83]
I've looked at your application, but as long as I have to provide my email and password manually, I'm not going to use it.
Sure, it might be encrypted on disk, but command line arguments are visible to *every* application that's running on your PC.

I've seen the FAQ and it's mentioned that the current system was chosen because of multiboxing and that Guild Wars 2 locks the Local.dat file, preventing multiboxing. However, Windows has the ability to use symbolic links, which are well-known in Unix based operating systems. You only have to manage multiple Local.dat files that are uniquely named. Every time before you start Guild Wars 2, overwrite the Local.dat symlink with a new one that points to the Local.dat file that you want.

When Guild Wars 2 is started, it opens the file to where that symbolic link is pointing to (instead of Local.dat itself), as can be observed in Process Explorer.
This would solve the multiboxing issue in combination with using Local.dat, and make it a lot more secure for the users to use multiple accounts.
However, I haven't checked if symlinks can be successfully created without admin privileges. My local PowerShell script runs fine (on an account with admin privileges, but without elevation), but I don't know if it would work correctly in Launchbuddy.

**Comment by Archomeda** [comment]
No problem! 😄 
From looking at the code, I noticed that it takes quite some effort to change it.

**Comment by SaiyanOfDarkness** [comment]
This should now be added, as ANet removed the -email and -password shortcut commands.  At least when I monitored the program it creates a .symlink file and copies the .dat file over.
