### ISSUE TITLE
Option missing in graphic settings

### ISSUE THREAD

**Issue by KurtySuit** [TheCheatsrichter/Gw2_Launchbuddy#84]
Ambiente occlusion and Light Adaptation are missing in the graphic settings

https://i.imgur.com/0k2LjqQ.png

**Comment by TheCheatsrichter** [comment]
Very interesting.
LB actually reads the GFX.Settings file located at %appdata%/Guild Wars 2/EXENAME.xml.
That file normally stores all possible GFX settings except these new ones. Seems to be an inconsistency by Gw2 itself. These settings might get stored elsewhere (my bet is Local.dat).
