### ISSUE TITLE
[Request] Bring back the old Cinema Mode from 1.5.2

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [TheCheatsrichter/Gw2_Launchbuddy#87]
I highly dislike these huge avatars on the account list (in front of the loginwindow image).

Also forcing the settings to go full screen as well isn't necessary, and the smaller window was just fine.

Not Preferred
![](https://i.imgur.com/XdWKGcg.png)

Preferred
![](https://i.imgur.com/khCOc37.png)

**Comment by TheCheatsrichter** [comment]
![unbenannt](https://user-images.githubusercontent.com/15090699/48292211-c3166280-e479-11e8-8829-975fa7185ea4.PNG)

Upcoming version will use a better scaled ListView.
