### ISSUE TITLE
Remember clientport checkbox setting

### ISSUE THREAD

**Issue by kazerniel** [TheCheatsrichter/Gw2_Launchbuddy#88]
Currently the clientport checkbox always gets unselected when I close LB. Is there any way to make the checkbox remember that it was selected?

Also it would be nice to be able to save launch arguments with account profiles. Say, if I launch the game with my minimal graphics setup I also want to be able to mute all sound, but *only then*.

**Comment by KairuByte** [comment]
> Currently the clientport checkbox always gets unselected when I close LB. Is there any way to make the checkbox remember that it was selected?

I think the current worry on this is that it may break launch if the accepted values change. It's being looked into in 1.8, but I wouldn't say it's definitely going to happen.

> Also it would be nice to be able to save launch arguments with account profiles. Say, if I launch the game with my minimal graphics setup I also want to be able to mute all sound, but only then.

I believe what you are asking for is intended for 1.8.
