### ISSUE TITLE
Add hotkeys for faster window switching

### ISSUE THREAD

**Issue by SkilledAlpaca** [TheCheatsrichter/Gw2_Launchbuddy#89]
Instead of clicking on the account, it'd be nice to be able to hit a hotkey to go to the next/previous account or even a hotkey to go to the third account. For example if you have 4 accounts open, pressing CTRL+3 will take you to the third loaded account and so forth for 1-4. I'd like the cycle method personally as I only run two accounts and a single button to swap would be nice.

**Comment by KairuByte** [comment]
This was talked about previously, and while it’s not on the milestones list it’s definitely planned.
