### ISSUE TITLE
V1.7.0 Spaces in Password

### ISSUE THREAD

**Issue by nevaahe** [TheCheatsrichter/Gw2_Launchbuddy#90]
If there is a space in the password it will freeze on the whitescreen as if the password was invalid. I have 5 accounts, 4 of which have spaces, 1 does not. The one without a space worked fine, the other 4 did not. I changed the password on an additional account to test and it worked fine. 

I think there is a parenthesis being omitted in the command line arguments. as I did not have this problem with v1.6 and below

**Comment by KairuByte** [comment]
I just pushed a fix to the repo for this, though you'll have to compile it locally if you want to test before the next release.

Short term workaround for this though, is to put double quotes around your password "like this" when entering it into LB.
