### ISSUE TITLE
[Request] Option to automatically delete gw2cache folders before loading client.

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [TheCheatsrichter/Gw2_Launchbuddy#93]
So using LB for a while and I noticed there seems to be a lot of gw2cache folders in my %temp% folder when loading multiple clients at once.  Just thought it might be a good idea if there was an option to have LB automatically remove those folders before starting the clients up.  That way the trading post can load properly without getting a blank screen.  I normally have to go in manually and do this quite often, but it would be nice if LB had this feature.

**Comment by KairuByte** [comment]
o.0 I've never run into this issue at all, actually. What are the symptoms of too many cache folders out of curiosity? I'd have just assumed the client would always create a new unique one, and focus on that.

**Comment by SaiyanOfDarkness** [comment]
You would think so normally, but not always.  When too many cache folders are present, the gemstore does not load at all, no menus, nothing.  You still get the tabs on top like Promotions, Toys, etc, but they all load a blank page.  The trading post however still loads and you can search things to buy, but when it comes to the gemstore it's completely blank.

Another thing to keep in mind, is loading multiple clients.  The folder in use can't be deleted if the game is running.  So there would have to be some check in place first before that command was run.  Maybe only have it run if gw2.exe wasn't in the actively running list, instead of it trying to run for each client you start?

**Comment by KairuByte** [comment]
Interesting. 

I’m not sure on how to implement it to be honest. We could just do it on initial launch on the assumption that if we don’t have control over any clients, none are live. That check hasn’t been in place for a few releases though I don’t believe. Might be time to put it back in place.

**Comment by SaiyanOfDarkness** [comment]
Right now I've been using a .bat file to automatically clear my gw2cache folders using this code..

`for /D %%f in ("%temp%\gw2cache*") do rmdir %%f /s /q
exit`

This opens the cmd prompt window, deletes the folders, and then exits right away.

Most computers would direct to the same location as long as they are on Windows.  Maybe something similar could be used in this case?

**Comment by KairuByte** [comment]
Likely yes, my only concern might be the need for elevated permissions, though I doubt that’s a common occurrence if ever.
