### ISSUE TITLE
Instance Window Sizing

### ISSUE THREAD

**Issue by MinorMissDemeanor** [TheCheatsrichter/Gw2_Launchbuddy#95]
While I appreciate the "artistic" instance control window, the space would be better served by allowing for 5 instance control without having to use a window scroll bar.  Ideally, I would like to see the window height user customizable to suit the control of different quantities of instances (1-xx).
Thank-you

**Comment by MinorMissDemeanor** [comment]
Actually - that's not quite what I am after.
The "Instance Manager/Selection" window is of a fixed size, so rather than growing or shrinking with the number of instances open, it remains of a fixed size.  It appears (after trying this on multiple different setups) that the maximum number of instances that the window can switch between without creating a scroll bar is 4.  If you add a fifth instance, as soon as you activate it in the instance manager, it generates a scroll bar that you have to utilize to access the first instance.
My suggestion was to either allow user input for the height of the instance manager window or, have LB create the height of the instance manager window based on the number of instances open (with perhaps an override to prevent oversizing the window for the screen)

**Comment by SaiyanOfDarkness** [comment]
Oh the LB UI thing.  Yeah would be cool if you could resize that.  Very limited right now.

**Comment by SeparGW2** [comment]
In addition to resizing, I would also like to be able to show only the icons.  If they could be presented in a horizontal format, I would put them below the minimap.

**Comment by sebastiantest** [comment]
I also think a horizontal version could fit better into the game ui of guild wars 2, here is a small mockup. I guess it could be implemented in a way that it auto detects which display style will be used ( I guess based on the width/height ratio?)
<img width="1924" alt="horizontal instance list" src="https://user-images.githubusercontent.com/3963593/79045911-04321980-7c0e-11ea-8145-9d6070920858.png">

**Comment by SeparGW2** [comment]
If development is still going on, this would be useful.
