### ISSUE TITLE
Remove Button under Hotkeys doesn't do anything.

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [TheCheatsrichter/Gw2_Launchbuddy#98]
So I hit Add.. and the hotkey section drop down menu is empty, and left side says "No Key Set"  When I click on remove button it doesn't actually remove any of those items that were added.

**Comment by vonat** [comment]
Because I couldn't remove hotkey item, I did set up twice with the same hotkey. Launcbuddy never run again. How can I delete LaunchBuddy settings? Where are the data? Where the information are store (in .ini file or in registry) ?

**Comment by TheCheatsrichter** [comment]
OS Version?
Hotkeys get stored with your account data. Delete %appdat%/Gw2 Launchbuddy/accs.xml to reset all settings

**Comment by TheCheatsrichter** [comment]
Thanks for the screen. Might have something to do with the OS as all my test machines run on win 10.
I'll have a closer look at this error this weekend.

**Comment by SaiyanOfDarkness** [comment]
Installed that framework.. still blank for me.

**Comment by SkilledAlpaca** [comment]
I have the same issue on Windows Version10.0.17763 Build 17763. Attempting to use the Hotkey gives a "Did not execute correctly" error.

**Comment by SaiyanOfDarkness** [comment]
Just to add on.. The drop down menu for Advanced Settings > Set Process Priority show up normally, but the one inside the Hotkey section does not.
